import { type FormEvent, type ReactNode, useEffect, useState } from 'react'
import { getAccountProfile, getSetupStatus, loginWebAccount, recoverLocalAccount, registerWebAccount, type SetupStatus, unlockLocalAccount } from '../services/accountService'
import SetupWizard from './SetupWizard'
import wealthosIcon from '../../../assets/branding/wealthos-app-icon.svg'
import { useLanguage } from '../context/LanguageContext'

export default function SetupGate({children}:{children:ReactNode}){
  const{direction,t,language}=useLanguage()
  const copy={statusError:t('Unable to read local setup status.'),preparing:t('Preparing your private workspace…'),workspace:t('PRIVATE LOCAL WORKSPACE'),recover:t('Recover WealthOS'),unlock:t('Unlock WealthOS'),saveCode:t('Save your new recovery code'),recoveryCode:t('Recovery code'),newPassword:t('New password'),localPassword:t('Local password'),password:t('Password'),saved:t('I saved the code'),back:t('Back'),reset:t('Reset password'),useRecovery:t('Use recovery code'),unlockAction:t('Unlock'),recoveryError:t('Recovery could not be completed.'),passwordError:t('The local password is incorrect.')}
  const[status,setStatus]=useState<SetupStatus|null>(null),[webMode,setWebMode]=useState(false),[webAuthenticated,setWebAuthenticated]=useState(false),[loadError,setLoadError]=useState(''),[actionError,setActionError]=useState(''),[password,setPassword]=useState(''),[recovering,setRecovering]=useState(false),[recoveryCode,setRecoveryCode]=useState(''),[replacement,setReplacement]=useState(''),[newCode,setNewCode]=useState('')
  useEffect(()=>{getAccountProfile().then(()=>{setWebMode(true);setWebAuthenticated(true)}).catch(()=>getSetupStatus().then(setStatus).catch(error=>{if(error instanceof Error&&error.message.includes('401'))setWebMode(true);else setLoadError(copy.statusError)}))},[copy.statusError])
  if(webMode&&!webAuthenticated)return <WebAuthGate direction={direction} locale={language} onAuthenticated={()=>setWebAuthenticated(true)}/>
  if(webMode&&webAuthenticated)return children
  if(loadError)return <div className="app-route-loading">{loadError}</div>
  if(!status)return <div className="app-route-loading">{copy.preparing}</div>
  if(!status.completed)return <SetupWizard status={status} onComplete={()=>getSetupStatus().then(setStatus)}/>
  if(status.requires_unlock&&!status.unlocked)return <main className="setup-wizard" dir={direction}><section className="setup-wizard__card"><header><img className="setup-wizard__brand" src={wealthosIcon} alt="WealthOS"/><div><small>{copy.workspace}</small><h1>{recovering?copy.recover:copy.unlock}</h1></div></header><div className="setup-wizard__body">{newCode?<><h2>{copy.saveCode}</h2><div className="setup-wizard__notice"><strong dir="ltr">{newCode}</strong></div></>:recovering?<><label>{copy.recoveryCode}<input dir="ltr" value={recoveryCode} onChange={event=>setRecoveryCode(event.target.value)}/></label><label>{copy.newPassword}<input type="password" value={replacement} onChange={event=>setReplacement(event.target.value)}/></label></>:<><h2>{copy.localPassword}</h2><label>{copy.password}<input type="password" value={password} onChange={event=>setPassword(event.target.value)}/></label></>}{actionError&&<p className="setup-wizard__error">{actionError}</p>}</div><footer>{newCode?<button onClick={()=>getSetupStatus().then(setStatus)}>{copy.saved}</button>:recovering?<><button className="secondary" onClick={()=>{setRecovering(false);setActionError('')}}>{copy.back}</button><button onClick={()=>{setActionError('');recoverLocalAccount(recoveryCode,replacement).then(result=>setNewCode(result.recovery_code)).catch(()=>setActionError(copy.recoveryError))}}>{copy.reset}</button></>:<><button className="secondary" onClick={()=>{setRecovering(true);setActionError('')}}>{copy.useRecovery}</button><button onClick={()=>{setActionError('');unlockLocalAccount(password).then(()=>getSetupStatus()).then(setStatus).catch(()=>setActionError(copy.passwordError))}}>{copy.unlockAction}</button></>}</footer></section></main>
  return children
}

function WebAuthGate({direction,locale,onAuthenticated}:{direction:'ltr'|'rtl';locale:'ar'|'en';onAuthenticated:()=>void}){
  const[mode,setMode]=useState<'login'|'register'>('login'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[inviteCode,setInviteCode]=useState(''),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false)
  async function submit(event:FormEvent){event.preventDefault();setError('');setSubmitting(true);try{if(mode==='register')await registerWebAccount(username,password,locale,inviteCode);else await loginWebAccount(username,password);onAuthenticated()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to authenticate.')}finally{setSubmitting(false)}}
  return <main className="setup-wizard" dir={direction}><section className="setup-wizard__card"><header><img className="setup-wizard__brand" src={wealthosIcon} alt="WealthOS"/><div><small>PRIVATE WEALTH WORKSPACE</small><h1>{mode==='login'?'Sign in to WealthOS':'Create your WealthOS account'}</h1></div></header><form onSubmit={submit}><div className="setup-wizard__body"><label>Username<input autoComplete="username" value={username} minLength={3} maxLength={64} required onChange={event=>setUsername(event.target.value)}/></label><label>Password<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} minLength={12} maxLength={256} required onChange={event=>setPassword(event.target.value)}/></label>{mode==='register'&&<label>Invite code<input type="password" autoComplete="off" value={inviteCode} minLength={16} required onChange={event=>setInviteCode(event.target.value)}/></label>}{error&&<p className="setup-wizard__error">{error}</p>}</div><footer><button className="secondary" type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Create account':'Use existing account'}</button><button type="submit" disabled={submitting}>{submitting?'Please wait…':mode==='login'?'Sign in':'Register'}</button></footer></form></section></main>
}
