import { useState } from 'react'
import { completeSetup, type SetupRequest, type SetupStatus } from '../services/accountService'
import { saveUserProfile } from '../pages/userProfile'
import './SetupWizard.css'
import wealthosIcon from '../../../assets/branding/wealthos-app-icon.svg'
import { useLanguage } from '../context/LanguageContext'
import { countryOptions, defaultCountry } from '../utils/countryOptions'
import WizardSelect from './WizardSelect'

const copy={
  en:{title:'Set up WealthOS',workspace:'PRIVATE WEALTH WORKSPACE',next:'Continue',back:'Back',finish:'Finish setup',identity:'Local identity',name:'Name',email:'Email',password:'Optional local password',currencies:'Currencies',baseCurrency:'Base currency',searchCurrencies:'Search currencies',investorProfile:'Investor profile',nationality:'Nationality',residence:'Country of residence',taxResidence:'Tax residence',searchCountries:'Search countries',localData:'Local data',localDataDescription:'WealthOS stores this private workspace locally for this Windows account.',existingData:'Existing financial data was found.',priorBeta:'A prior beta database was found and remains untouched.',chooseData:'Choose explicitly. Nothing will be deleted or silently merged.',resumeExisting:'Resume existing data',startClean:'Start clean and leave prior beta data untouched',reviewMigration:'Pause for migration review',dataAcknowledgement:'I understand where my local data is stored.',finalReview:'Final review',baseCurrencyReview:'Base currency',enabled:'Enabled',data:'Data',choiceRequired:'Choice required',newWorkspace:'New local workspace',unableToComplete:'Unable to complete setup.',recoveryWorkspace:'PRIVATE LOCAL WORKSPACE',recoveryTitle:'Save your recovery code',recoveryDescription:'This code is shown once. Store it offline; it can reset your local password.',recoverySaved:'I saved the code'},
  ar:{title:'إعداد WealthOS',workspace:'مساحة الثروة الخاصة',next:'متابعة',back:'رجوع',finish:'إكمال الإعداد',identity:'الهوية المحلية',name:'الاسم',email:'البريد الإلكتروني',password:'كلمة مرور محلية اختيارية',currencies:'العملات',baseCurrency:'العملة الأساسية',searchCurrencies:'ابحث عن عملة',investorProfile:'ملف المستثمر',nationality:'الجنسية',residence:'بلد الإقامة',taxResidence:'الإقامة الضريبية',searchCountries:'ابحث عن دولة',localData:'البيانات المحلية',localDataDescription:'يحفظ WealthOS مساحة العمل الخاصة هذه محليًا ضمن حساب Windows الحالي.',existingData:'تم العثور على بيانات مالية موجودة.',priorBeta:'تم العثور على قاعدة بيانات من نسخة بيتا سابقة وستبقى دون تغيير.',chooseData:'اختر بوضوح. لن تُحذف أي بيانات ولن تُدمج تلقائيًا.',resumeExisting:'متابعة استخدام البيانات الموجودة',startClean:'البدء ببيانات جديدة مع إبقاء بيانات البيتا السابقة دون تغيير',reviewMigration:'إيقاف الإعداد لمراجعة ترحيل البيانات',dataAcknowledgement:'أفهم مكان حفظ بياناتي المحلية.',finalReview:'المراجعة النهائية',baseCurrencyReview:'العملة الأساسية',enabled:'العملات المفعّلة',data:'البيانات',choiceRequired:'يلزم اختيار أحد الخيارات',newWorkspace:'مساحة عمل محلية جديدة',unableToComplete:'تعذر إكمال الإعداد.',recoveryWorkspace:'مساحة عمل محلية خاصة',recoveryTitle:'احفظ رمز الاسترداد',recoveryDescription:'يظهر هذا الرمز مرة واحدة. احفظه في مكان منفصل وغير متصل بالإنترنت؛ إذ يمكن استخدامه لإعادة تعيين كلمة المرور المحلية.',recoverySaved:'حفظت الرمز'},
}
const currencies=['SAR','USD','AED','EUR','GBP']
const currencyOptions=currencies.map(value=>({value,label:value}))

export default function SetupWizard({status,onComplete}:{status:SetupStatus;onComplete:()=>void}){
  const{setLanguage}=useLanguage()
  const[step,setStep]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[recoveryCode,setRecoveryCode]=useState<string|null>(null)
  const[data,setData]=useState<SetupRequest>({full_name:status.profile?.full_name??'',email:status.profile?.email??'',local_password:null,preferred_language:'en',base_currency_code:'SAR',enabled_currency_codes:['SAR'],nationality:defaultCountry,country_of_residence:defaultCountry,tax_residence:defaultCountry,investor_type:'INDIVIDUAL',local_data_acknowledged:false,existing_data_choice:status.has_existing_data||status.legacy_data_found?null:'START_CLEAN'})
  const t=copy[data.preferred_language]
  const countries=countryOptions(data.preferred_language)
  const update=<K extends keyof SetupRequest>(key:K,value:SetupRequest[K])=>setData(current=>({...current,[key]:value}))
  async function finish(){setBusy(true);setMessage('');try{const result=await completeSetup(data);saveUserProfile({fullName:result.profile.full_name,email:result.profile.email},result.profile.id);setLanguage(data.preferred_language);if(result.recovery_code){setRecoveryCode(result.recovery_code)}else{onComplete()}}catch{setMessage(t.unableToComplete)}finally{setBusy(false)}}
  if(recoveryCode)return <main className="setup-wizard" dir={data.preferred_language==='ar'?'rtl':'ltr'}><section className="setup-wizard__card"><header><img className="setup-wizard__brand" src={wealthosIcon} alt="WealthOS"/><div><small>{t.recoveryWorkspace}</small><h1>{t.recoveryTitle}</h1></div></header><div className="setup-wizard__body"><p>{t.recoveryDescription}</p><div className="setup-wizard__notice"><strong dir="ltr">{recoveryCode}</strong></div></div><footer><button onClick={onComplete}>{t.recoverySaved}</button></footer></section></main>
  return <main className="setup-wizard" dir={data.preferred_language==='ar'?'rtl':'ltr'}>
    <section className="setup-wizard__card"><header><img className="setup-wizard__brand" src={wealthosIcon} alt="WealthOS"/><div><small>{t.workspace}</small><h1>{t.title}</h1><p>{step+1} / 6</p></div></header>
      <div className="setup-wizard__progress"><i style={{width:`${((step+1)/6)*100}%`}}/></div>
      {step===0&&<div className="setup-wizard__body"><h2>Language / اللغة</h2><div className="setup-wizard__choices"><button className={data.preferred_language==='en'?'active':''} onClick={()=>update('preferred_language','en')}>English</button><button className={data.preferred_language==='ar'?'active':''} onClick={()=>update('preferred_language','ar')}>العربية</button></div></div>}
      {step===1&&<div className="setup-wizard__body"><h2>{t.identity}</h2><label>{t.name}<input value={data.full_name} onChange={e=>update('full_name',e.target.value)}/></label><label>{t.email}<input type="email" value={data.email} onChange={e=>update('email',e.target.value)}/></label><label>{t.password}<input type="password" onChange={e=>update('local_password',e.target.value||null)}/></label></div>}
      {step===2&&<div className="setup-wizard__body"><h2>{t.currencies}</h2><label>{t.baseCurrency}<WizardSelect value={data.base_currency_code} options={currencyOptions} searchLabel={t.searchCurrencies} onChange={value=>{update('base_currency_code',value);if(!data.enabled_currency_codes.includes(value))update('enabled_currency_codes',[...data.enabled_currency_codes,value])}}/></label><div className="setup-wizard__checks">{currencies.map(c=><label key={c}><input type="checkbox" checked={data.enabled_currency_codes.includes(c)} disabled={c===data.base_currency_code} onChange={e=>update('enabled_currency_codes',e.target.checked?[...data.enabled_currency_codes,c]:data.enabled_currency_codes.filter(x=>x!==c))}/>{c}</label>)}</div></div>}
      {step===3&&<div className="setup-wizard__body"><h2>{t.investorProfile}</h2><div className="setup-wizard__country-grid"><label>{t.nationality}<WizardSelect value={data.nationality??defaultCountry} options={countries} searchLabel={t.searchCountries} onChange={value=>update('nationality',value)}/></label><label>{t.residence}<WizardSelect value={data.country_of_residence??defaultCountry} options={countries} searchLabel={t.searchCountries} onChange={value=>update('country_of_residence',value)}/></label></div><label>{t.taxResidence}<WizardSelect value={data.tax_residence??defaultCountry} options={countries} searchLabel={t.searchCountries} onChange={value=>update('tax_residence',value)}/></label></div>}
      {step===4&&<div className="setup-wizard__body"><h2>{t.localData}</h2><p>{t.localDataDescription}</p>{(status.has_existing_data||status.legacy_data_found)&&<div className="setup-wizard__notice"><strong>{status.has_existing_data?t.existingData:t.priorBeta}</strong><p>{t.chooseData}</p>{status.has_existing_data&&<label><input type="radio" checked={data.existing_data_choice==='RESUME_EXISTING'} onChange={()=>update('existing_data_choice','RESUME_EXISTING')}/>{t.resumeExisting}</label>}{status.legacy_data_found&&!status.has_existing_data&&<label><input type="radio" checked={data.existing_data_choice==='START_CLEAN'} onChange={()=>update('existing_data_choice','START_CLEAN')}/>{t.startClean}</label>}<label><input type="radio" checked={data.existing_data_choice==='REVIEW_MIGRATION'} onChange={()=>update('existing_data_choice','REVIEW_MIGRATION')}/>{t.reviewMigration}</label></div>}<label className="setup-wizard__ack"><input type="checkbox" checked={data.local_data_acknowledged} onChange={e=>update('local_data_acknowledged',e.target.checked)}/>{t.dataAcknowledgement}</label></div>}
      {step===5&&<div className="setup-wizard__body"><h2>{t.finalReview}</h2><dl><dt>{t.name}</dt><dd>{data.full_name}</dd><dt>{t.baseCurrencyReview}</dt><dd>{data.base_currency_code}</dd><dt>{t.enabled}</dt><dd>{data.enabled_currency_codes.join(', ')}</dd><dt>{t.data}</dt><dd>{status.has_existing_data?(data.existing_data_choice??t.choiceRequired):t.newWorkspace}</dd></dl>{message&&<p className="setup-wizard__error">{message}</p>}</div>}
      <footer>{step>0&&<button className="secondary" onClick={()=>setStep(step-1)}>{t.back}</button>}<button disabled={busy||(step===4&&(!data.local_data_acknowledged||((status.has_existing_data||status.legacy_data_found)&&!data.existing_data_choice)))} onClick={()=>step===5?void finish():setStep(step+1)}>{step===5?t.finish:t.next}</button></footer>
    </section>
  </main>
}
