/* eslint-disable react-refresh/only-export-components */
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import { updatePreferredLanguage } from '../services/accountService'

export type Language = 'en' | 'ar'

const arabic: Record<string, string> = {
  'Credit management':'إدارة الائتمان',
  'Track balances, utilization, statements, and upcoming payments.':'تابع الأرصدة ونسب الاستخدام وكشوف الحساب والمدفوعات القادمة.',
  'Credit Used':'الرصيد المستخدم',
  'Posted Cards':'بطاقات مُرحّلة',
  'Available Credit':'الائتمان المتاح',
  'Of':'من',
  'Utilization':'نسبة الاستخدام',
  'Monthly DBR Obligation':'الالتزام الشهري لنسبة عبء الدين',
  'Payment Due':'استحقاق السداد',
  'Day':'اليوم',
  'Billing Dates Not Set':'تواريخ الفوترة غير محددة',
  'Remove':'إزالة',
  'Pay credit card':'سداد بطاقة ائتمانية',
  'Record a card payment':'تسجيل سداد بطاقة',
  'Add credit card':'إضافة بطاقة ائتمانية',
  'Connect a new card':'ربط بطاقة جديدة',
  'Review statement':'مراجعة كشف الحساب',
  'Reconcile recent charges':'تسوية العمليات الأخيرة',
  'cannot be removed yet. Pay the full outstanding balance of':'لا يمكن إزالتها الآن. سدّد كامل الرصيد المستحق وقدره',
  'first.':'أولًا.',
  'from active credit cards? Its transaction history will be retained.':'من البطاقات الائتمانية النشطة؟ سيُحتفظ بسجل عملياتها.',
  'was closed successfully.':'تم إغلاقها بنجاح.',
  'Unable to remove this credit card.':'تعذر إزالة هذه البطاقة الائتمانية.',
  'Current Data':'البيانات الحالية',
  'Loading Posted Information':'جارٍ تحميل المعلومات المُرحّلة',
  'Data Unavailable':'البيانات غير متاحة',
  'Workspace':'مساحة العمل',
  'Wealth':'الثروة',
  'Intelligence':'التحليلات',
  'System':'النظام',
  'Home':'الرئيسية',
  'Investing':'الاستثمار',
  'Bank Accounts':'الحسابات البنكية',
  'Credit Cards':'البطاقات الائتمانية',
  'Properties':'العقارات',
  'Accounting':'المحاسبة',
  'Reporting':'التقارير',
  'Settings':'الإعدادات',
  'Executive Summary':'الملخص التنفيذي',
  'Stocks':'الأسهم',
  'Deposits':'الودائع',
  'Investment Cash Flows':'التدفقات النقدية الاستثمارية',
  'Alternative Investments':'الاستثمارات البديلة',
  'Saving Circles':'الجمعيات المالية',
  'Cash':'النقد',
  'Brokers':'الوسطاء','Broker added successfully. Create its first portfolio below.':'تمت إضافة الوسيط بنجاح. أنشئ محفظته الأولى أدناه.','Portfolio created successfully.':'تم إنشاء المحفظة بنجاح.','Portfolio updated successfully.':'تم تحديث المحفظة بنجاح.','Portfolio removed successfully.':'تمت إزالة المحفظة بنجاح.','Manage brokers and the portfolios held with each provider.':'أدر الوسطاء والمحافظ المحتفظ بها لدى كل مزود.','Registered Brokers':'الوسطاء المسجلون','Loading brokers...':'جارٍ تحميل الوسطاء...','No Brokers Registered':'لا يوجد وسطاء مسجلون','Add a broker before creating an investment portfolio.':'أضف وسيطًا قبل إنشاء محفظة استثمارية.','Financial Institution':'المؤسسة المالية','Country not specified':'الدولة غير محددة','Via':'عبر','portfolios':'محافظ','Add Portfolio':'إضافة محفظة','Create A Portfolio With':'إنشاء محفظة لدى','Portfolio number is required. Select the currency actually used by this portfolio.':'رقم المحفظة مطلوب. اختر العملة المستخدمة فعليًا في هذه المحفظة.','Portfolio Name':'اسم المحفظة','Portfolio Number':'رقم المحفظة','IBAN (Optional)':'الآيبان (اختياري)','Portfolio Currency':'عملة المحفظة','This permanently closes the broker and every portfolio held under it.':'يؤدي هذا إلى إغلاق الوسيط وكل محفظة لديه نهائيًا.','Financial Consequences':'الآثار المالية','All open positions under this broker will be closed and removed from your wealth.':'ستُغلق جميع المراكز المفتوحة لدى هذا الوسيط وتُزال من ثروتك.','All brokerage cash under its portfolios will be removed.':'سيُزال كل نقد الوساطة في محافظه.','No money will be returned to any bank account or Cash On Hand.':'لن تُعاد أي أموال إلى حساب بنكي أو النقد المتاح.','The written-off value will remain recorded in the accounting audit trail.':'ستظل القيمة المشطوبة مسجلة في سجل التدقيق المحاسبي.','Keep Broker':'الاحتفاظ بالوسيط','Update the broker website and rates used for future activity.':'حدّث موقع الوسيط والنسب المستخدمة للأنشطة المستقبلية.','Commission Rate':'نسبة العمولة','VAT On Commission':'ضريبة القيمة المضافة على العمولة','Dividend Withholding Tax':'ضريبة الاستقطاع على التوزيعات','Leave blank to use profile default':'اتركه فارغًا لاستخدام إعداد الملف الافتراضي','VAT applies to the brokerage service, while dividend withholding tax applies to eligible distributions. Leave the withholding field blank to follow the investor profile. Previously posted activity remains unchanged.':'تُطبق ضريبة القيمة المضافة على خدمة الوساطة، وتُطبق ضريبة الاستقطاع على التوزيعات المؤهلة. اترك حقل الاستقطاع فارغًا لاتباع ملف المستثمر. لا تتغير الأنشطة المُرحّلة سابقًا.','Update this portfolio without changing its broker.':'حدّث هذه المحفظة دون تغيير وسيطها.','Keep':'احتفاظ','Enter number':'أدخل الرقم','IBAN':'الآيبان','Leave blank':'اتركه فارغًا','Leave the portfolio number and IBAN blank to keep their current values. Currency can change only before funding or trading.':'اترك رقم المحفظة والآيبان فارغين للاحتفاظ بقيمهما الحالية. لا يمكن تغيير العملة إلا قبل التمويل أو التداول.','This removes the portfolio from':'يؤدي هذا إلى إزالة المحفظة من','Protection Check':'فحص الحماية','The portfolio must have no open positions.':'يجب ألا تحتوي المحفظة على مراكز مفتوحة.','Its brokerage cash balance must be zero.':'يجب أن يكون رصيد نقد الوساطة فيها صفرًا.','Historical trades remain preserved in the audit trail.':'تظل التداولات التاريخية محفوظة في سجل التدقيق.','Keep Portfolio':'الاحتفاظ بالمحفظة','Select Account':'اختر الحساب',
  'Financial Platforms':'المنصات المالية',
  'Monthly Snapshots':'اللقطات الشهرية',
  'Property Income':'دخل العقارات',
  'Property Expenses':'مصروفات العقارات',
  'Library':'المكتبة',
  'Index':'الفهرس',
  'Accounting Summary':'ملخص المحاسبة',
  'Review Queue':'قائمة المراجعة',
  'General Ledger':'دفتر الأستاذ العام',
  'Journal Entries':'قيود اليومية',
  'Reconciliation':'التسوية',
  'Private Wealth':'الثروة الخاصة',
  'Search WealthOS':'البحث في WealthOS',
  'Search WealthOS...':'ابحث في WealthOS...',
  'Quick Destinations':'وجهات سريعة',
  'Investment Positions':'المراكز الاستثمارية',
  'Display Currency':'عملة العرض',
  'Manage Currencies':'إدارة العملات',
  'Notifications':'الإشعارات','Lock WealthOS':'قفل WealthOS','Recent Searches':'عمليات البحث الأخيرة','Clear':'مسح',
  'Close':'إغلاق',
  'Need Attention':'تحتاج إلى انتباه',
  'Needs attention':'تحتاج إلى انتباه',
  'All Clear':'كل شيء سليم',
  'No pending notifications.':'لا توجد إشعارات معلقة.',
  'Review':'مراجعة',
  'Saved safely for later review':'حُفظت بأمان للمراجعة لاحقًا',
  'Back':'عودة',
  'Back to previous page':'العودة إلى الصفحة السابقة',
  'Page navigation':'التنقل بين الصفحات',
  'Open Profile Settings':'فتح إعدادات الملف الشخصي',
  'Toggle navigation':'إظهار أو إخفاء القائمة',
  'Switch Theme':'تغيير المظهر',
  'PRIVATE WEALTH DASHBOARD':'لوحة إدارة الثروة الخاصة',
  'Consolidated assets, liquidity, obligations, and performance.':'نظرة موحدة على الأصول والسيولة والالتزامات والأداء.',
  'Portfolio management':'إدارة المحافظ',
  'Monitor portfolios, positions, performance, and investment income.':'متابعة المحافظ والمراكز والأداء والدخل الاستثماري.',
  'Financial Health':'الصحة المالية',
  'Estimated from assets & liabilities':'تقدير مبني على الأصول والالتزامات',
  'Health Score':'مؤشر الصحة',
  'Available Cash':'النقد المتاح',
  'Liquidity':'السيولة',
  'Risk Level':'مستوى المخاطر',
  'Healthy':'سليم',
  'Watch':'تحت المراقبة',
  'At Risk':'معرّض للخطر',
  'Low':'منخفض',
  'Moderate':'متوسط',
  'High':'مرتفع',
  'Net Worth':'صافي الثروة',
  'Wealth trend':'مسار الثروة',
  'Performance':'الأداء',
  'Investments':'الاستثمارات',
  'Return':'العائد',
  'Focus Today':'تركيز اليوم',
  'Quick Actions':'العمليات السريعة',
  'Recent Activity':'النشاط الأخير',
  'View all':'عرض الكل',
  'View All':'عرض الكل',
  'Complete':'إكمال',
  'Previous Focus page':'صفحة التركيز السابقة',
  'Next Focus page':'صفحة التركيز التالية',
  'Import financial document':'استيراد مستند مالي',
  'PDF, image, XLSX or CSV':'PDF أو صورة أو XLSX أو CSV',
  'Browse':'استعراض',
  'No pending reviews':'لا توجد مراجعات معلقة',
  'Or describe a transaction':'أو صف العملية',
  'Posted Operation':'عملية مُرحّلة',
  'Financial timeline':'التسلسل المالي',
  'One clear timeline for posted movements across your wealth.':'تسلسل واضح لجميع الحركات المُرحّلة في ثروتك.',
  'Total activity':'إجمالي النشاط',
  'Latest posted events':'أحدث العمليات المُرحّلة',
  'Money in':'الأموال الداخلة',
  'Income events':'عمليات دخل',
  'Money out':'الأموال الخارجة',
  'Outgoing events':'عمليات خارجة',
  'Search activity':'ابحث في النشاط',
  'Transfer':'تحويل',
  'No Posted Activity':'لا يوجد نشاط مُرحّل',
  'No Posted Activity Yet':'لا يوجد نشاط مُرحّل حتى الآن',
  'Completed operations will appear here.':'ستظهر العمليات المكتملة هنا.',
  'operations awaiting review':'عمليات بانتظار المراجعة',
  'Every financial document analyzed by WealthOS and the operations found inside it.':'كل مستند مالي حلله WealthOS والعمليات التي عُثر عليها داخله.',
  'Documents':'المستندات',
  'Analyzed Files':'ملفات محللة',
  'Extracted Operations':'العمليات المستخرجة',
  'Across All Documents':'عبر جميع المستندات',
  'Awaiting Review':'بانتظار المراجعة',
  'Open Review Queue':'فتح قائمة المراجعة',
  'Library Is Clear':'المكتبة خالية',
  'Privacy-First Library':'مكتبة تراعي الخصوصية أولًا',
  'The original document is read locally in your browser. WealthOS stores its file record and extracted financial operations for review and audit.':'يُقرأ المستند الأصلي محليًا في متصفحك. يحفظ WealthOS سجل الملف والعمليات المالية المستخرجة للمراجعة والتدقيق.',
  'Uploaded Documents':'المستندات المرفوعة',
  'Newest documents appear first.':'تظهر أحدث المستندات أولًا.',
  'Search Documents Or Amounts':'ابحث في المستندات أو المبالغ',
  'Loading Your Library…':'جارٍ تحميل مكتبتك…',
  'No Documents Yet':'لا توجد مستندات حتى الآن',
  'Add your first PDF, image, spreadsheet, or CSV from this page.':'أضف أول ملف PDF أو صورة أو جدول بيانات أو CSV من هذه الصفحة.',
  'Add First Document':'إضافة أول مستند',
  'No Matching Documents':'لا توجد مستندات مطابقة',
  'Try a file name, operation, amount, or currency.':'جرّب اسم ملف أو عملية أو مبلغًا أو عملة.',
  'Reading':'جارٍ القراءة',
  'Add Document':'إضافة مستند',
  'Refresh':'تحديث',
  'Operations':'عمليات',
  'Confirmed':'مؤكدة',
  'Ignored':'متجاهلة',
  'confirmed':'مؤكدة',
  'ignored':'متجاهلة',
  'PENDING REVIEW':'بانتظار المراجعة',
  'COMPLETED':'مكتمل',
  'REMOVED':'محذوف',
  'PENDING':'معلّقة',
  'CONFIRMED':'مؤكدة',
  'IGNORED':'متجاهلة',
  'DUPLICATE':'مكررة',
  'ALREADY POSTED':'مُرحّلة سابقًا',
  'Document Actions':'إجراءات المستند',
  'Posted accounting records remain protected after removal.':'تظل السجلات المحاسبية المُرحّلة محمية بعد الحذف.',
  'Delete Document':'حذف المستند',
  'Amount Not Found':'لم يُعثر على المبلغ',
  'Amount not found':'لم يُعثر على المبلغ',
  'Date Not Found':'لم يُعثر على التاريخ',
  'No operations were extracted from this document.':'لم تُستخرج أي عمليات من هذا المستند.',
  'Delete Imported Document?':'حذف المستند المستورد؟',
  'This removes the document and every unposted review draft extracted from it.':'سيؤدي ذلك إلى حذف المستند وكل مسودات المراجعة غير المُرحّلة المستخرجة منه.',
  'Posted operations, ledger entries, and their duplicate-protection fingerprints remain safely preserved.':'ستظل العمليات المُرحّلة وقيود دفتر الأستاذ وبصمات منع التكرار محفوظة بأمان.',
  'Keep Document':'الاحتفاظ بالمستند',
  'Deleting…':'جارٍ الحذف…',
  'Unable to load the document library.':'تعذر تحميل مكتبة المستندات.',
  'The document could not be analyzed.':'تعذر تحليل المستند.',
  'The document could not be deleted.':'تعذر حذف المستند.',
  'Accounting workspace':'مساحة العمل المحاسبية',
  'Review imported operations before they are posted to the General Ledger.':'راجع العمليات المستوردة قبل ترحيلها إلى دفتر الأستاذ العام.',
  'Pending review':'بانتظار المراجعة',
  'Across':'عبر',
  'files':'ملفات',
  'High confidence':'ثقة مرتفعة',
  'Ready for confirmation':'جاهزة للتأكيد',
  'Reminders due':'تذكيرات مستحقة',
  'Every 3 days':'كل 3 أيام',
  'Imported operations':'العمليات المستوردة',
  'Drafts only — nothing below has been posted.':'مسودات فقط — لم يُرحّل أي مما يلي.',
  'Loading review queue…':'جارٍ تحميل قائمة المراجعة…',
  'No pending operations':'لا توجد عمليات معلقة',
  'Your review queue is clear.':'قائمة المراجعة خالية.',
  'awaiting review':'بانتظار المراجعة',
  'Delete File':'حذف الملف',
  'confidence':'ثقة',
  'Ready':'جاهزة',
  'Ignore':'تجاهل',
  'Delete Imported File?':'حذف الملف المستورد؟',
  'All unposted operations from this file will leave the queue.':'ستُزال جميع العمليات غير المُرحّلة في هذا الملف من القائمة.',
  'Previously posted accounting records and duplicate-protection fingerprints remain preserved.':'ستظل السجلات المحاسبية المُرحّلة سابقًا وبصمات منع التكرار محفوظة.',
  'Keep File':'الاحتفاظ بالملف',
  'Unable to load review queue.':'تعذر تحميل قائمة المراجعة.',
  'Imported document not found.':'لم يُعثر على المستند المستورد.',
  'Imported operation not found.':'لم يُعثر على العملية المستوردة.',
  'Unsupported review status.':'حالة المراجعة غير مدعومة.',
  'This imported operation is already linked to another posted operation.':'هذه العملية المستوردة مرتبطة مسبقًا بعملية مُرحّلة أخرى.',
  'Document intelligence':'تحليل المستندات',
  'Review imported operations':'مراجعة العمليات المستوردة',
  'Close import review':'إغلاق مراجعة الاستيراد',
  'Local, review-first analysis.':'تحليل محلي يبدأ بالمراجعة.',
  'The file is read in your browser and nothing is posted automatically.':'يُقرأ الملف في متصفحك ولا يُرحّل أي شيء تلقائيًا.',
  'Reading the actual file…':'جارٍ قراءة الملف الفعلي…',
  'OCR progress':'تقدم التعرف الضوئي على النص',
  'Extracting rows and financial data':'جارٍ استخراج الصفوف والبيانات المالية',
  'Analysis failed':'فشل التحليل',
  'Awaiting decision':'بانتظار القرار',
  'No readable text was found in this file.':'لم يُعثر على نص قابل للقراءة في هذا الملف.',
  'Text was extracted, but no financial operations could be identified confidently.':'تم استخراج النص، لكن تعذر تحديد عمليات مالية بدرجة ثقة كافية.',
  'Unrecognized card':'بطاقة غير معروفة',
  'Define during review':'عرّفها أثناء المراجعة',
  'Review & Post':'مراجعة وترحيل',
  'All operations have a decision':'اتُخذ قرار بشأن جميع العمليات',
  'unrecognized card can now be defined without interrupting the review.':'يمكن الآن تعريف بطاقة غير معروفة دون مقاطعة المراجعة.',
  'unrecognized cards can now be defined without interrupting the review.':'يمكن الآن تعريف بطاقات غير معروفة دون مقاطعة المراجعة.',
  'No new cards need to be defined.':'لا توجد بطاقات جديدة تحتاج إلى تعريف.',
  'Could not save review':'تعذر حفظ المراجعة',
  'Imported operations pages':'صفحات العمليات المستوردة',
  'Previous page':'الصفحة السابقة',
  'Next page':'الصفحة التالية',
  'Page':'صفحة',
  'Showing':'عرض',
  'of':'من',
  'Continue to card setup':'المتابعة إلى إعداد البطاقة',
  'Adding To Library…':'جارٍ الإضافة إلى المكتبة…',
  'Review Later':'المراجعة لاحقًا',
  'This operation has not been archived yet. Please wait and try again.':'لم تُحفظ هذه العملية بعد. انتظر ثم حاول مجددًا.',
  'The decision could not be saved.':'تعذر حفظ القرار.',
  'Please wait while WealthOS adds this document to your library.':'انتظر بينما يضيف WealthOS هذا المستند إلى مكتبتك.',
  'This file type is not supported.':'نوع الملف هذا غير مدعوم.',
  'No readable rows were found in this legacy XLS workbook.':'لم يُعثر على صفوف قابلة للقراءة في ملف XLS القديم هذا.',
  'The spreadsheet is empty or could not be decoded.':'جدول البيانات فارغ أو تعذر فك ترميزه.',
  'No readable rows were found in this XLS file. Save it as XLSX or CSV and try again.':'لم يُعثر على صفوف قابلة للقراءة في ملف XLS هذا. احفظه بصيغة XLSX أو CSV ثم حاول مجددًا.',
  'Card payment':'سداد بطاقة',
  'Property':'عقار',
  'Unclassified':'غير مصنفة',
  'Loading WealthOS...':'جارٍ تحميل WealthOS...',
  'Failed to load financial data':'تعذر تحميل البيانات المالية',
  'No portfolio data.':'لا توجد بيانات للمحفظة.',
  'Performance period':'فترة الأداء',
  'Last updated':'آخر تحديث',
  'Monthly Snapshot':'اللقطة الشهرية',
  'Saved':'محفوظة',
  'Current':'الحالية',
  'Wealth Trend':'مسار الثروة',
  'Wealth and investment trend':'مسار الثروة والاستثمارات',
  'Building history':'جارٍ بناء السجل',
  'Assets, liquidity, obligations, and risk':'الأصول والسيولة والالتزامات والمخاطر',
  'Priorities':'الأولويات',
  'items':'عناصر',
  'Amount':'المبلغ',
  'Restore Hidden Priorities':'استعادة الأولويات المخفية',
  'Hide All Priorities':'إخفاء كل الأولويات',
  'Restore All':'استعادة الكل',
  'Hide All':'إخفاء الكل',
  'Open Operation':'فتح العملية',
  'Open':'فتح',
  'That’s everything for now':'هذا كل شيء حاليًا',
  'You’re all caught up':'لا توجد عناصر معلقة',
  'Bank accounts and credit cards':'الحسابات البنكية والبطاقات الائتمانية',
  'Accounts':'حسابات',
  'Cards':'بطاقات',
  'Total Balance':'إجمالي الرصيد',
  'Inflow':'التدفقات الداخلة',
  'Outflow':'التدفقات الخارجة',
  'Total Limit':'إجمالي الحد الائتماني',
  'Used':'المستخدم',
  'Remaining':'المتبقي',
  'Available':'المتاح',
  'Wealth Allocation':'توزيع الثروة',
  'View all assets':'عرض جميع الأصول',
  'Total assets by class':'إجمالي الأصول حسب الفئة',
  'Class':'الفئة',
  'Value':'القيمة',
  'Weight':'الوزن',
  'ETFs':'صناديق المؤشرات',
  'Funds':'الصناديق',
  'Bonds & Sukuk':'السندات والصكوك',
  'REITs':'الصناديق العقارية المتداولة',
  'Private Credit':'الائتمان الخاص',
  'Real Estate':'العقارات',
  'Savings & Lending':'الادخار والإقراض',
  'Other Assets':'أصول أخرى',
  'Completed activity':'نشاط مكتمل',
  'Credit card payment recorded successfully':'تم تسجيل سداد البطاقة الائتمانية بنجاح',
  'View':'عرض',
  'Reminder due':'تذكير مستحق',
  'imported operations need review':'عمليات مستوردة تحتاج إلى مراجعة',
  'review reminders due':'تذكيرات مراجعة مستحقة',
  'Trade':'تداول',
  'Buy or sell investment securities.':'شراء أو بيع الأوراق المالية الاستثمارية.',
  'Income':'الدخل',
  'Record a new income transaction.':'تسجيل عملية دخل جديدة.',
  'Expense':'المصروفات',
  'Record a new expense transaction.':'تسجيل عملية صرف جديدة.',
  'Transfer Funds':'تحويل أموال',
  'Transfer funds between your accounts.':'تحويل الأموال بين حساباتك.',
  'Add Broker':'إضافة وسيط',
  'Register a broker for investment trades.':'تسجيل وسيط لعمليات الاستثمار.',
  'Fund Brokerage Cash':'تمويل رصيد الوساطة',
  'Move cash from your bank account into brokerage cash.':'نقل النقد من حسابك البنكي إلى رصيد الوساطة.',
  'Withdraw Brokerage Cash':'سحب رصيد الوساطة',
  'Move available brokerage cash back to your bank account.':'إعادة رصيد الوساطة المتاح إلى حسابك البنكي.',
  'Credit Card Payment':'سداد بطاقة ائتمانية',
  'Pay a credit card balance.':'سداد رصيد بطاقة ائتمانية.',
  'Buy Other Asset':'شراء أصل آخر',
  'Acquire a long-term asset.':'اقتناء أصل طويل الأجل.',
  'Buy Property':'شراء عقار',
  'Edit Property':'تعديل العقار',
  'Property Name':'اسم العقار',
  'Property name or reference':'اسم العقار أو مرجعه',
  'Property Usage':'استخدام العقار',
  'Select Property Usage':'اختر استخدام العقار',
  'Primary Residence':'مسكن رئيسي',
  'Vacation Home':'منزل للعطلات',
  'Real Estate Transaction Tax':'ضريبة التصرفات العقارية',
  'Sale Amount':'مبلغ البيع',
  'Selling Costs':'تكاليف البيع',
  'Leave blank if not applicable':'اتركه فارغًا إذا لم ينطبق',
  'Related Asset':'الأصل المرتبط',
  'Recommended':'موصى به',
  'Select Related Asset':'اختر الأصل المرتبط',
  'Linked to':'مرتبط بـ',
  'Rent Frequency':'دورية الإيجار',
  'Next Rent Due Date':'تاريخ استحقاق الإيجار التالي',
  'Semi-annual':'نصف سنوي',
  'Short-term Rent':'إيجار قصير الأجل',
  'Commercial Rent':'إيجار تجاري',
  'Residential Rent':'إيجار سكني',
  'Purchase and post a property to the real estate ledger.':'اشترِ عقارًا ورحّله إلى سجل العقارات.',
  'Sell Asset':'بيع أصل',
  'Dispose of a long-term asset.':'التصرف في أصل طويل الأجل.',
  'Manual Journal':'قيد يدوي',
  'Create an advanced journal entry.':'إنشاء قيد محاسبي متقدم.',
  'Operation':'العملية',
  'Operation not found.':'العملية غير موجودة.',
  'Back to Dashboard':'العودة إلى لوحة التحكم',
  'Add Bank Account':'إضافة حساب بنكي',
  'Bank account details':'بيانات الحساب البنكي',
  'Connect or create a bank account.':'ربط حساب بنكي أو إنشاء حساب جديد.',
  'Liquidity management':'إدارة السيولة',
  'A consolidated view of cash, bank balances, and liquidity.':'عرض موحد للنقد وأرصدة الحسابات البنكية والسيولة.',
  'Add New':'إضافة جديد',
  'Bank Balances':'أرصدة الحسابات البنكية',
  'Posted Accounts':'حسابات مُرحّلة',
  'Monthly Inflow':'التدفقات الداخلة الشهرية',
  'Monthly Outflow':'التدفقات الخارجة الشهرية',
  'Current Month':'الشهر الحالي',
  'Current Overview':'النظرة الحالية',
  'Workspace Overview':'نظرة مساحة العمل',
  'Latest Posted Information':'أحدث المعلومات المُرحّلة',
  'View Activity':'عرض النشاط',
  'No Posted Records':'لا توجد سجلات مُرحّلة',
  'Use Add New to begin':'استخدم «إضافة جديد» للبدء',
  'Quick actions':'إجراءات سريعة',
  'Common tasks':'مهام شائعة',
  'Add bank account':'إضافة حساب بنكي',
  'Connect or create an account':'ربط حساب أو إنشاء حساب جديد',
  'Transfer funds':'تحويل الأموال',
  'Move money between accounts':'نقل الأموال بين الحسابات',
  'Reconcile account':'تسوية الحساب',
  'Review unmatched entries':'مراجعة القيود غير المتطابقة',
  'Enter the transaction details below.':'أدخل تفاصيل العملية أدناه.',
  'Transaction preview':'معاينة العملية',
  'Live operation summary':'ملخص مباشر للعملية',
  'Ready for review':'جاهز للمراجعة',
  'Values update from the operation details.':'تتحدث القيم وفق تفاصيل العملية.',
  'Before you execute':'قبل التنفيذ',
  'Validation':'التحقق',
  'Automatic':'تلقائي',
  'Ledger impact':'الأثر المحاسبي',
  'Balanced':'متوازن',
  'Audit trail':'سجل التدقيق',
  'Recorded':'مسجل',
  'WealthOS intelligence':'تحليلات WealthOS',
  'Related accounts and assets are checked before posting.':'يتم التحقق من الحسابات والأصول المرتبطة قبل الترحيل.',
  'Opening Balance':'الرصيد الافتتاحي',
  'New Bank Account':'حساب بنكي جديد',
  'Account Setup':'إعداد الحساب',
  'Bank':'البنك',
  'Not Selected':'غير محدد',
  'Account Type':'نوع الحساب',
  'Ledger Impact':'الأثر على دفتر الأستاذ',
  'No Opening Entry':'لا يوجد قيد افتتاحي',
  'Balanced Opening Entry':'قيد افتتاحي متوازن',
  'Bank name':'اسم البنك',
  'Current Account':'حساب جاري',
  'Savings Account':'حساب توفير',
  'Deposit Account':'حساب وديعة',
  'Digital Bank Account':'حساب بنكي رقمي',
  'Other':'أخرى',
  'Account Name':'اسم الحساب',
  'Optional':'اختياري',
  'e.g. Primary Account':'مثال: الحساب الرئيسي',
  'IBAN Or Account Number':'رقم الآيبان أو الحساب',
  'IBAN or account number':'رقم الآيبان أو الحساب',
  'Currency':'العملة',
  'Balance Date':'تاريخ الرصيد',
  'Primary Account':'الحساب الرئيسي',
  'Use This Account Automatically When Funding':'استخدام هذا الحساب تلقائيًا عند التمويل',
  'The account will be available for balance and liquidity tracking.':'سيكون الحساب متاحًا لتتبع الرصيد والسيولة.',
  'Saving…':'جارٍ الحفظ…',
  'Bank name is required.':'اسم البنك مطلوب.',
  'IBAN or account number must contain at least 4 characters when provided.':'يجب ألا يقل رقم الآيبان أو الحساب عن 4 أحرف عند إدخاله.',
  'Bank account saved and its opening balance was posted successfully.':'تم حفظ الحساب البنكي وترحيل رصيده الافتتاحي بنجاح.',
  'Unable to save the bank account.':'تعذر حفظ الحساب البنكي.',
  'CURRENT':'جاري',
  'SAVINGS':'توفير',
  'DEPOSIT':'وديعة',
  'DIGITAL':'رقمي',
  'OTHER':'أخرى',
  'Bank Opening Balance':'الرصيد الافتتاحي للحساب البنكي',
  'Add or correct the documented opening balance without changing later transactions.':'إضافة الرصيد الافتتاحي الموثق أو تصحيحه دون تغيير العمليات اللاحقة.',
  'Add Opening Balance':'إضافة رصيد افتتاحي',
  'Correct Opening Balance':'تصحيح الرصيد الافتتاحي',
  'Accounting impact':'الأثر المحاسبي',
  'Previous opening balance':'الرصيد الافتتاحي السابق',
  'Difference to post':'الفرق الذي سيُرحّل',
  'Current balance after correction':'الرصيد الحالي بعد التصحيح',
  'Bank Account':'الحساب البنكي',
  'Current opening balance':'الرصيد الافتتاحي الحالي',
  'Correct opening balance':'الرصيد الافتتاحي الصحيح',
  'Original opening date':'تاريخ الرصيد الافتتاحي الأصلي',
  'Opening balance date':'تاريخ الرصيد الافتتاحي',
  'Correction date':'تاريخ التصحيح',
  'Reason':'السبب',
  'Explain why the opening balance is being changed':'اشرح سبب تغيير الرصيد الافتتاحي',
  'Only the difference will be posted; later transactions will remain unchanged.':'سيُرحّل الفرق فقط، وستبقى العمليات اللاحقة دون تغيير.',
  'Use this only for money that existed before WealthOS.':'استخدم هذا الخيار فقط للأموال التي كانت موجودة قبل WealthOS.',
  'Opening balance saved successfully.':'تم حفظ الرصيد الافتتاحي بنجاح.',
  'Opening balance corrected as a prior-period adjustment.':'تم تصحيح الرصيد الافتتاحي كتسوية لفترة سابقة.',
  'Unable to save the opening balance.':'تعذر حفظ الرصيد الافتتاحي.',
  'Loading bank account…':'جارٍ تحميل الحساب البنكي…',
  'Select a bank account':'اختر حسابًا بنكيًا',
  'Bank account not found.':'الحساب البنكي غير موجود.',
  'Unable to load bank accounts.':'تعذر تحميل الحسابات البنكية.',
  'Investment Assets':'الأصول الاستثمارية',
  'Review balances, expected returns, payout schedules, and maturity dates.':'راجع الأرصدة والعوائد المتوقعة وجداول صرف العوائد وتواريخ الاستحقاق.',
  'Add Deposit':'إضافة وديعة',
  'Active Deposits':'الودائع النشطة',
  'Currently Tracked':'تحت المتابعة حاليًا',
  'Posted Deposit Assets':'أصول الودائع المُرحّلة',
  'Weighted Annual Return':'متوسط العائد السنوي المرجّح',
  'Next Maturity':'الاستحقاق القادم',
  'No Maturity Date':'لا يوجد تاريخ استحقاق',
  'Deposit Positions':'مراكز الودائع',
  'Every active deposit and savings product recorded in WealthOS.':'كل وديعة ومنتج ادخاري نشط مسجل في WealthOS.',
  'Deposit':'الوديعة',
  'Balance':'الرصيد',
  'Maturity':'الاستحقاق',
  'Modify':'تعديل',
  'Edit':'تعديل',
  'Break':'فك الوديعة',
  'Open Ended':'مفتوحة المدة',
  'No Deposits Yet':'لا توجد ودائع حتى الآن',
  'Add a deposit to track its balance, return, and maturity.':'أضف وديعة لمتابعة رصيدها وعائدها واستحقاقها.',
  'Loading deposits…':'جارٍ تحميل الودائع…',
  'Unable to load deposits':'تعذر تحميل الودائع',
  'TERM_DEPOSIT':'وديعة لأجل',
  'INCOME_SAVINGS':'ادخار بعائد',
  'Wadaie':'ودائع',
  'Monthly Deposit':'وديعة شهرية',
  'Deposit Details':'بيانات الوديعة',
  'Edit Deposit':'تعديل الوديعة',
  'Current Deposit Balance':'الرصيد الحالي للوديعة',
  'Term Deposit':'وديعة لأجل',
  'Income-Producing Savings':'ادخار مدر للدخل',
  'Provider Not Selected':'لم يتم تحديد المزود',
  'Deposit Position':'مركز الوديعة',
  'Financial Impact':'الأثر المالي',
  'Estimated Return':'العائد المتوقع',
  'Funding Account':'حساب التمويل',
  'Provider':'المزود',
  'Product Name':'اسم المنتج',
  'Product Type':'نوع المنتج',
  'e.g. Dinar, Abyan Or A Bank':'مثال: دينار أو أبيان أو بنك',
  'e.g. Monthly Income Deposit':'مثال: وديعة الدخل الشهرية',
  'Select Bank Account':'اختر حسابًا بنكيًا',
  'Deposit Amount':'مبلغ الوديعة',
  'Select Funding Account':'اختر حساب التمويل',
  'Annual Return %':'العائد السنوي %',
  'Payout Frequency':'دورية صرف العائد',
  'Income Destination':'وجهة العائد',
  'Quarterly':'ربع سنوي',
  'At Maturity':'عند الاستحقاق',
  'Same As Funding Account':'نفس حساب التمويل',
  'Maturity Date':'تاريخ الاستحقاق',
  'Funding Date':'تاريخ التمويل',
  'Adjust Balance':'تصحيح الرصيد',
  'Auto Renew':'تجديد تلقائي',
  'Renew the principal at maturity':'تجديد أصل المبلغ عند الاستحقاق',
  'Days':'يومًا',
  'Estimated Annual Return':'العائد السنوي المتوقع',
  'Balance Adjustment':'تصحيح الرصيد',
  'Posts the difference to or from the original funding account.':'يُرحّل الفرق إلى حساب التمويل الأصلي أو منه.',
  'Corrected Balance':'الرصيد الصحيح',
  'Adjustment Date':'تاريخ التصحيح',
  'DD/MM/YYYY':'يوم/شهر/سنة',
  'Why is this correction needed?':'لماذا يلزم هذا التصحيح؟',
  'Cancel':'إلغاء',
  'Posting…':'جارٍ الترحيل…',
  'Post Adjustment':'ترحيل التصحيح',
  'Add a bank account before creating a deposit.':'أضف حسابًا بنكيًا قبل إنشاء وديعة.',
  'Balance changes remain protected and use posted accounting corrections.':'تظل تغييرات الرصيد محمية وتُعالج بتصحيحات محاسبية مُرحّلة.',
  'Funding moves from the selected bank account into a tracked deposit asset.':'ينتقل التمويل من الحساب البنكي المحدد إلى أصل وديعة قيد المتابعة.',
  'Save Changes':'حفظ التغييرات',
  'Complete the required deposit details.':'أكمل بيانات الوديعة المطلوبة.',
  'Deposit details updated successfully.':'تم تحديث بيانات الوديعة بنجاح.',
  'Deposit created and funded successfully.':'تم إنشاء الوديعة وتمويلها بنجاح.',
  'Unable to save the deposit.':'تعذر حفظ الوديعة.',
  'Deposit not found.':'لم يتم العثور على الوديعة.',
  'Enter a valid corrected balance.':'أدخل رصيدًا صحيحًا صالحًا.',
  'Enter a valid adjustment date and a brief reason.':'أدخل تاريخ تصحيح صالحًا وسببًا موجزًا.',
  'Deposit balance adjusted and the accounting correction was posted.':'تم تصحيح رصيد الوديعة وترحيل التصحيح المحاسبي.',
  'Unable to adjust the deposit balance.':'تعذر تصحيح رصيد الوديعة.',
  'About deposit balance adjustments':'حول تصحيحات رصيد الوديعة',
  'Use this only to correct a mismatch with the provider. WealthOS keeps the original transaction and posts the difference to or from the funding bank account.':'استخدم هذا فقط لتصحيح اختلاف مع المزود. يحتفظ WealthOS بالعملية الأصلية ويرحّل الفرق إلى حساب التمويل أو منه.',
  'Operation readiness':'جاهزية العملية',
  'Preflight Check':'فحص ما قبل الترحيل',
  'Required Fields':'الحقول المطلوبة',
  'Missing Details':'بيانات ناقصة',
  'Journal Entry':'قيد اليومية',
  'Waiting for Values':'بانتظار القيم',
  'Audit Trail':'سجل التدقيق',
  'Will Be Recorded':'سيتم تسجيله',
  'Pending':'معلّق',
  'Operation Recorded':'تم تسجيل العملية',
  'Complete Required Details':'أكمل البيانات المطلوبة',
  'Funding account was not found.':'لم يتم العثور على حساب التمويل.',
  'Income destination account was not found.':'لم يتم العثور على حساب وجهة العائد.',
  'Deposit and selected bank accounts must use the same currency.':'يجب أن تستخدم الوديعة والحسابات البنكية المحددة العملة نفسها.',
  'Deposit amount exceeds the selected bank account balance.':'مبلغ الوديعة يتجاوز رصيد الحساب البنكي المحدد.',
  'The deposit ledger account is not configured. Apply the latest database update and try again.':'حساب دفتر الودائع غير مهيأ. طبّق آخر تحديث لقاعدة البيانات ثم حاول مجددًا.',
  'The income destination must use the deposit currency.':'يجب أن تستخدم وجهة العائد عملة الوديعة.',
  'The corrected balance is already the current balance.':'الرصيد الصحيح يساوي الرصيد الحالي بالفعل.',
  'The funding account does not have enough balance for this correction.':'لا يحتوي حساب التمويل على رصيد كافٍ لهذا التصحيح.',
  'Break Deposit':'فك الوديعة',
  'Close a deposit and post the actual settlement received.':'أغلق الوديعة ورحّل مبلغ التسوية الفعلي المستلم.',
  'Closes the deposit and returns the actual settlement to the selected bank account.':'يغلق الوديعة ويعيد مبلغ التسوية الفعلي إلى الحساب البنكي المحدد.',
  'Select Deposit':'اختر وديعة',
  'Destination Bank Account':'الحساب البنكي المستلم',
  'Amount Received':'المبلغ المستلم',
  'Transaction Date':'تاريخ العملية',
  'Post Break Deposit':'ترحيل فك الوديعة',
  'Break Deposit Posted Successfully.':'تم ترحيل فك الوديعة بنجاح.',
  'Unable to break deposit.':'تعذر فك الوديعة.',
  'Add a clear audit reference':'أضف مرجعًا واضحًا للتدقيق',
  'Active deposit was not found.':'لم يتم العثور على وديعة نشطة.',
  'Amount received cannot exceed the current deposit balance.':'لا يمكن أن يتجاوز المبلغ المستلم رصيد الوديعة الحالي.',
  'Destination bank account was not found.':'لم يتم العثور على الحساب البنكي المستلم.',
  'Destination account must use the deposit currency.':'يجب أن يستخدم الحساب المستلم عملة الوديعة نفسها.',
  'Receiving Asset':'الأصل المستلم',
  'Cash On Hand':'النقد المتاح باليد',
  'Fund a term deposit or income-producing savings product.':'موّل وديعة لأجل أو منتج ادخار مُدرًا للدخل.',
  'Set up cash owned before WealthOS or post a documented opening-balance correction.':'سجّل النقد المملوك قبل WealthOS أو رحّل تصحيحًا موثقًا للرصيد الافتتاحي.',
  'Record Inheritance':'تسجيل ميراث',
  'Record inherited cash, property, investments, or other assets without treating them as operating income.':'سجّل النقد أو العقارات أو الاستثمارات أو الأصول الأخرى الموروثة دون اعتبارها دخلًا تشغيليًا.',
  'Cash On Hand Asset':'أصل النقد المتاح',
  'Current Cash On Hand':'النقد المتاح حاليًا',
  'Opening Cash Balance':'رصيد النقد الافتتاحي',
  'Correction Reason':'سبب التصحيح',
  'Opening Balance Description':'وصف الرصيد الافتتاحي',
  'Protected Balance Correction':'تصحيح رصيد محمي',
  'Opening Asset — Not Income':'أصل افتتاحي — وليس دخلًا',
  'Use this only to correct the recorded Cash On Hand balance. The reason and accounting entry remain in the audit trail.':'استخدم هذا فقط لتصحيح رصيد النقد المتاح المسجل. يبقى السبب والقيد المحاسبي في سجل التدقيق.',
  'Record only cash already owned before starting WealthOS. Future cash must come from a real operation such as a withdrawal, income, or asset sale.':'سجّل فقط النقد المملوك قبل بدء استخدام WealthOS. يجب أن يأتي النقد اللاحق من عملية فعلية مثل السحب أو الدخل أو بيع أصل.',
  'Post Cash Correction':'ترحيل تصحيح النقد',
  'Create Cash Asset':'إنشاء أصل نقدي',
  'Unable to load Cash On Hand.':'تعذر تحميل النقد المتاح.',
  'Cash On Hand balance adjusted successfully.':'تم تصحيح رصيد النقد المتاح بنجاح.',
  'Cash On Hand opening asset created successfully.':'تم إنشاء أصل النقد الافتتاحي بنجاح.',
  'Unable to save the Cash On Hand asset.':'تعذر حفظ أصل النقد المتاح.',
  'Bank debit card details':'بيانات بطاقة الخصم البنكية',
  'Linked Account':'الحساب المرتبط',
  'Select an account':'اختر حسابًا',
  'New Debit Card':'بطاقة خصم جديدة',
  'Linked Bank Account':'الحساب البنكي المرتبط',
  'Card Name':'اسم البطاقة',
  'e.g. Primary Mada Card':'مثال: بطاقة مدى الرئيسية',
  'Last 4 Digits':'آخر 4 أرقام',
  'Card Network':'شبكة البطاقة',
  'Mada':'مدى',
  'Visa Debit':'فيزا خصم',
  'Mastercard Debit':'ماستركارد خصم',
  'From Linked Account':'من الحساب المرتبط',
  'The card will inherit the linked account currency and balance.':'ستستخدم البطاقة عملة الحساب المرتبط ورصيده.',
  'Linking…':'جارٍ الربط…',
  'Link Debit Card':'ربط بطاقة الخصم',
  'Debit card linked successfully.':'تم ربط بطاقة الخصم بنجاح.',
  'Unable to link the debit card.':'تعذر ربط بطاقة الخصم.',
  'Asset Type':'نوع الأصل','Comments':'ملاحظات','Matures':'يستحق في','MONTHLY':'شهري','QUARTERLY':'ربع سنوي','SEMI ANNUAL':'نصف سنوي','ANNUAL':'سنوي','AT MATURITY':'عند الاستحقاق','Units':'وحدات','Buy':'شراء','Sell':'بيع',
  'Select Asset Type':'اختر نوع الأصل',
  'Vehicle':'مركبة',
  'Gold & Precious Metals':'الذهب والمعادن الثمينة',
  'Equipment':'معدات',
  'Art & Collectibles':'الفنون والمقتنيات',
  'Other Asset':'أصل آخر',
  'Asset Name':'اسم الأصل',
  'e.g. Toyota Land Cruiser, Gold Bar':'مثال: تويوتا لاندكروزر أو سبيكة ذهب',
  'Payment Source':'مصدر الدفع',
  'Available Cash On Hand':'النقد المتاح حاليًا',
  'Purchase Amount':'مبلغ الشراء',
  'Purchase Date':'تاريخ الشراء',
  'Notes':'ملاحظات',
  'Optional details or reference':'تفاصيل أو مرجع اختياري',
  'Purchase amount exceeds the available balance of':'مبلغ الشراء يتجاوز الرصيد المتاح وقدره',
  'Post Purchase':'ترحيل الشراء',
  'Other Asset Purchase Posted Successfully.':'تم ترحيل شراء الأصل الآخر بنجاح.',
  'Unable to post the asset purchase.':'تعذر ترحيل شراء الأصل.',
  'Property valuation':'تقييم العقار',
  'Updated Value':'القيمة المحدّثة',
  'Select a property':'اختر عقارًا',
  'Valuation Impact':'أثر التقييم',
  'Difference':'الفرق',
  'Ledger':'دفتر الأستاذ',
  'Balanced Revaluation Entry':'قيد إعادة تقييم متوازن',
  'Select Property':'اختر عقارًا',
  'Market Value':'القيمة السوقية',
  'Valuation Date':'تاريخ التقييم',
  'Valuation Source / Notes':'مصدر التقييم / ملاحظات',
  'e.g. Certified valuation or market estimate':'مثال: تقييم معتمد أو تقدير سوقي',
  'Changes update the property value, wealth, and balance sheet together.':'تُحدّث التغييرات قيمة العقار والثروة والميزانية معًا.',
  'Update Valuation':'تحديث التقييم',
  'Unable to load properties.':'تعذر تحميل العقارات.',
  'Property valuation updated and posted to the ledger.':'تم تحديث تقييم العقار وترحيله إلى دفتر الأستاذ.',
  'Unable to update the valuation.':'تعذر تحديث التقييم.',
  'Current Statement Balance':'رصيد كشف الحساب الحالي',
  'Enter the amount actually paid to the bank. WealthOS tracks the payment and remaining card balance.':'أدخل المبلغ المدفوع فعليًا للبنك. يتتبع WealthOS الدفعة والرصيد المتبقي للبطاقة.',
  'Credit Card':'البطاقة الائتمانية',
  'Select Credit Card':'اختر بطاقة ائتمانية',
  'Payment Account':'حساب الدفع',
  'Amount Paid':'المبلغ المدفوع',
  'Payment Date':'تاريخ الدفع',
  'Description':'الوصف',
  'Post Payment':'ترحيل الدفعة',
  'Credit Card Payment Posted Successfully.':'تم ترحيل دفعة البطاقة الائتمانية بنجاح.',
  'Unable to post the card payment.':'تعذر ترحيل دفعة البطاقة.',
  'Search':'بحث',
  'Search your real WealthOS records, operations, and destinations.':'ابحث في سجلات WealthOS وعملياته ووجهاته الفعلية.',
  'Search accounts, cards, deposits, investments, operations…':'ابحث في الحسابات والبطاقات والودائع والاستثمارات والعمليات…',
  'Results For':'نتائج البحث عن',
  'Loading your records…':'جارٍ تحميل سجلاتك…',
  'Enter a word or name to begin.':'أدخل كلمة أو اسمًا للبدء.',
  'matching results':'نتائج مطابقة',
  'matching result':'نتيجة مطابقة',
  'No Matching Results':'لا توجد نتائج مطابقة',
  'Try the name of an account, card, deposit, broker, investment, operation, or page.':'جرّب اسم حساب أو بطاقة أو وديعة أو وسيط أو استثمار أو عملية أو صفحة.',
  'Every WealthOS page and operation in one place.':'كل صفحات WealthOS وعملياته في مكان واحد.',
  'Find Any Page Or Operation':'ابحث عن أي صفحة أو عملية',
  'Results':'نتائج',
  'Pages':'صفحات',
  'Destinations':'وجهات',
  'Accounting & Intelligence':'المحاسبة والتحليلات',
  'Financial Operations':'العمليات المالية',
  'Coming Soon':'قريبًا',
  'No Matching Destination':'لا توجد وجهة مطابقة',
  'Try the name of a page, task, or financial operation.':'جرّب اسم صفحة أو مهمة أو عملية مالية.',
  'Manage your account, security, and financial preferences.':'أدر حسابك وأمانه وتفضيلاتك المالية.',
  'Account owner':'مالك الحساب',
  'Account security':'أمان الحساب',
  'Protected':'محمي',
  'Password management available':'إدارة كلمة المرور متاحة',
  'Personal':'شخصية',
  'Private wealth profile':'ملف ثروة خاص',
  'Settings center':'مركز الإعدادات',
  'Select what you want to manage.':'اختر ما تريد إدارته.',
  'Profile':'الملف الشخصي',
  'Manage your name and account email.':'أدر اسمك وبريد حسابك.',
  'Email & Password':'البريد وكلمة المرور',
  'Update sign-in details and account protection.':'حدّث بيانات الدخول وحماية الحساب.',
  'Currencies':'العملات',
  'Choose reporting and transaction currencies.':'اختر عملات التقارير والعمليات.',
  'Data & Account':'البيانات والحساب',
  'Download a backup or permanently delete your account.':'نزّل نسخة احتياطية أو احذف حسابك نهائيًا.',
  'Privacy First':'الخصوصية أولًا',
  'Your financial records are owned by your account. You can download a backup or permanently delete them at any time.':'سجلاتك المالية مملوكة لحسابك. يمكنك تنزيل نسخة احتياطية أو حذفها نهائيًا في أي وقت.',
  'Account Settings':'إعدادات الحساب',
  'Manage your identity, residence, and default investment tax treatment.':'أدر هويتك وإقامتك والمعالجة الضريبية الافتراضية للاستثمار.',
  'Personal Information':'المعلومات الشخصية',
  'These details identify you across WealthOS.':'تعرّفك هذه البيانات في WealthOS.',
  'Full Name':'الاسم الكامل',
  'Email Address':'البريد الإلكتروني',
  'Nationality':'الجنسية',
  'Country Of Residence':'بلد الإقامة',
  'Tax Profile':'الملف الضريبي',
  'The default applies to future distributions unless a broker has its own override.':'يُطبق الافتراضي على التوزيعات المستقبلية ما لم يكن للوسيط إعداد خاص.',
  'Tax Residence':'الإقامة الضريبية',
  'Investor Type':'نوع المستثمر',
  'Individual':'فرد',
  'Entity':'منشأة',
  'Default Dividend Withholding Tax %':'ضريبة الاستقطاع الافتراضية للتوزيعات %',
  'Profile and tax settings saved.':'تم حفظ الملف والإعدادات الضريبية.',
  'Unable to load the profile.':'تعذر تحميل الملف الشخصي.',
  'Unable to save the profile.':'تعذر حفظ الملف الشخصي.',
  'Account Control':'التحكم بالحساب',
  'Download your information or permanently close your WealthOS account.':'نزّل معلوماتك أو أغلق حساب WealthOS نهائيًا.',
  'Account Backup':'النسخة الاحتياطية للحساب',
  'Download a complete copy of your financial records for safekeeping or analysis in Excel and other tools.':'نزّل نسخة كاملة من سجلاتك المالية للحفظ أو التحليل في Excel وغيره.',
  'Download Backup':'تنزيل النسخة الاحتياطية',
  'Delete Account':'حذف الحساب',
  'This permanently deletes the account and all financial data. This action cannot be undone.':'يحذف هذا الحساب وجميع البيانات المالية نهائيًا، ولا يمكن التراجع عنه.',
  'Confirm Account Email':'تأكيد بريد الحساب',
  'Type DELETE To Confirm':'اكتب DELETE للتأكيد',
  'Download a backup before continuing if you may need these records later.':'نزّل نسخة احتياطية قبل المتابعة إن كنت قد تحتاج هذه السجلات لاحقًا.',
  'Permanently Delete Account':'حذف الحساب نهائيًا',
  'Account Deleted':'تم حذف الحساب',
  'Your WealthOS account and all associated financial data have been permanently deleted.':'تم حذف حساب WealthOS وكل البيانات المالية المرتبطة به نهائيًا.',
  'Loading account email…':'جارٍ تحميل بريد الحساب…',
  'WealthOS could not connect to your account. Please try again.':'تعذر اتصال WealthOS بحسابك. حاول مرة أخرى.',
  'Backup downloaded successfully.':'تم تنزيل النسخة الاحتياطية بنجاح.',
  'WealthOS could not prepare your backup. Please try again.':'تعذر على WealthOS تجهيز النسخة الاحتياطية. حاول مرة أخرى.',
  'Unable to delete account.':'تعذر حذف الحساب.',
  'Control your local password and account protection.':'تحكم بكلمة المرور المحلية وحماية الحساب.',
  'Change password':'تغيير كلمة المرور',
  'Your password is never stored in the browser.':'لا تُخزّن كلمة مرورك في المتصفح.',
  'Current password':'كلمة المرور الحالية',
  'New password':'كلمة المرور الجديدة',
  'Confirm password':'تأكيد كلمة المرور',
  'Save this replacement recovery code offline. It is shown only here.':'احفظ رمز الاسترداد البديل دون اتصال. لن يظهر إلا هنا.',
  'Hide':'إخفاء',
  'Show':'إظهار',
  'passwords':'كلمات المرور',
  'Disable password':'تعطيل كلمة المرور',
  'Update password':'تحديث كلمة المرور',
  'New passwords do not match.':'كلمتا المرور الجديدتان غير متطابقتين.',
  'Password changed. Save the new recovery code.':'تم تغيير كلمة المرور. احفظ رمز الاسترداد الجديد.',
  'Password change failed.':'فشل تغيير كلمة المرور.',
  'Password disable failed.':'فشل تعطيل كلمة المرور.',
  'Use your current password and at least 12 characters for the new password.':'استخدم كلمة المرور الحالية واجعل الجديدة 12 حرفًا على الأقل.',
  'e.g. Saudi Arabian':'مثال: سعودي',
  'e.g. Saudi Arabia':'مثال: المملكة العربية السعودية',
  'Country of tax residence':'بلد الإقامة الضريبية',
  'Add Credit Card':'إضافة بطاقة ائتمانية',
  'Define a credit card detected in an imported operation.':'عرّف بطاقة ائتمانية اكتُشفت في عملية مستوردة.',
  'Add Bank Debit Card':'إضافة بطاقة خصم بنكية',
  'Link a debit card to its bank account.':'اربط بطاقة الخصم بحسابها البنكي.',
  'Add Property Valuation':'إضافة تقييم عقاري',
  'Update the current market value of a property.':'حدّث القيمة السوقية الحالية للعقار.',
  'New Loan':'قرض جديد',
  'Record financing, received funds, fees, and repayment terms.':'سجّل التمويل والمبالغ المستلمة والرسوم وشروط السداد.',
  'Manage Loans':'إدارة القروض','Processing…':'جارٍ التنفيذ…','The operation was completed and posted to the general ledger.':'اكتملت العملية ورُحّلت إلى دفتر الأستاذ العام.','Unable to complete the operation.':'تعذر إكمال العملية.','Active loans':'القروض النشطة','Financing facilities':'تسهيلات التمويل','Outstanding balance':'الرصيد القائم','Current principal':'أصل المبلغ الحالي','Monthly obligations':'الالتزامات الشهرية','Included in the debt burden ratio':'مضمّن في نسبة عبء الدين','Liabilities and loans':'الالتزامات والقروض','Financing terms and upcoming obligations':'شروط التمويل والالتزامات القادمة','New loan':'قرض جديد','Loading loans…':'جارٍ تحميل القروض…','No loans recorded':'لا توجد قروض مسجلة','Add financing to include it in liabilities and financial health.':'أضف تمويلًا لإدراجه ضمن الالتزامات والصحة المالية.','month':'شهر','Early settlement':'تسوية مبكرة','Refinance':'إعادة تمويل','Void':'إلغاء','Manage loan':'إدارة القرض','Name':'الاسم','Annual rate %':'النسبة السنوية %','Term in months':'المدة بالأشهر','Monthly payment':'الدفعة الشهرية','First payment':'أول دفعة','Settlement amount':'مبلغ التسوية','Any amount above the balance is recorded as a financing cost, while a discount is recorded separately.':'يُسجل أي مبلغ يتجاوز الرصيد كتكلفة تمويل، بينما يُسجل الخصم بشكل منفصل.','New lender':'المموّل الجديد','New principal':'أصل المبلغ الجديد','Fees':'الرسوم','Loan type':'نوع القرض','Short term':'قصير الأجل','Long term':'طويل الأجل','This does not erase the record.':'هذا لا يمحو السجل.','A reversing entry will be posted and the loan will remain in the audit trail with a voided status.':'سيُرحّل قيد عكسي وسيبقى القرض في سجل التدقيق بحالة ملغاة.','Review and confirm':'راجع وأكد',
  'Edit, settle, refinance, or reverse an existing loan.':'عدّل قرضًا قائمًا أو سدّده أو أعد تمويله أو اعكسه.',
  'Profile, currencies, security, backup, and account controls.':'الملف الشخصي والعملات والأمان والنسخ الاحتياطي والتحكم بالحساب.',
  'Investments, deposits, allocation, and market positions.':'الاستثمارات والودائع والتوزيع والمراكز السوقية.',
  'Review listed securities and investment positions.':'راجع الأوراق المالية المدرجة والمراكز الاستثمارية.',
  'Cash on hand, bank balances, and brokerage cash.':'النقد المتاح وأرصدة البنوك ونقد الوساطة.',
  'Balances, cash inflows, and cash outflows.':'الأرصدة والتدفقات النقدية الداخلة والخارجة.',
  'Credit limits, used balances, and payments.':'الحدود الائتمانية والأرصدة المستخدمة والمدفوعات.',
  'Balance sheet, income statement, cash flow, and liabilities.':'الميزانية وقائمة الدخل والتدفقات النقدية والالتزامات.',
  'Every posted debit and credit.':'كل مبلغ مدين ودائن مُرحّل.',
  'Balanced entries created by posted operations.':'قيود متوازنة أنشأتها العمليات المُرحّلة.',
  'Live financial reports generated from posted entries.':'تقارير مالية مباشرة مولّدة من القيود المُرحّلة.',
  'Documents analyzed by WealthOS and their extracted operations.':'مستندات حللها WealthOS والعمليات المستخرجة منها.',
  'Every WealthOS page and financial operation in one place.':'كل صفحات WealthOS وعملياته المالية في مكان واحد.',
  'Manual journal entry':'قيد يومية يدوي',
  'Expense posted successfully.':'تم ترحيل المصروف بنجاح.',
  'Journal entry posted successfully.':'تم ترحيل قيد اليومية بنجاح.',
  'Unable to post journal entry.':'تعذر ترحيل قيد اليومية.',
  'Expense details':'بيانات المصروف',
  'Expense category':'فئة المصروف',
  'Debit account':'الحساب المدين',
  'Select debit account':'اختر الحساب المدين',
  'Payment account':'حساب الدفع',
  'Credit account':'الحساب الدائن',
  'Select credit account':'اختر الحساب الدائن',
  'Posting date':'تاريخ الترحيل',
  'Post expense':'ترحيل المصروف',
  'Post entry':'ترحيل القيد',
  'Financial intelligence':'الذكاء المالي',
  'Report Studio':'استوديو التقارير',
  'Build focused reports from your income, cash flows, and investment activity.':'أنشئ تقارير مركزة من دخلك وتدفقاتك النقدية وأنشطتك الاستثمارية.',
  'Save template':'حفظ القالب',
  'Export':'تصدير',
  'Build your report':'أنشئ تقريرك',
  'Choose what you want to analyze.':'اختر ما تريد تحليله.',
  'Report type':'نوع التقرير',
  'Period':'الفترة',
  'Quarter':'ربع السنة',
  'YTD':'منذ بداية السنة',
  'Custom':'مخصص',
  'Date range':'نطاق التاريخ',
  'to':'إلى',
  'Income sources':'مصادر الدخل',
  'Metrics to include':'المؤشرات المضمنة',
  'Scope':'النطاق',
  'All portfolios & assets':'جميع المحافظ والأصول',
  'Report currency':'عملة التقرير',
  'Generate report':'إنشاء التقرير',
  'Income & reinvestment':'الدخل وإعادة الاستثمار',
  'Cash flow statement':'قائمة التدفقات النقدية',
  'Portfolio performance':'أداء المحفظة',
  'Income by asset':'الدخل حسب الأصل',
  'Expense analysis':'تحليل المصروفات',
  'Net worth movement':'حركة صافي الثروة',
  'Custom report':'تقرير مخصص',
  'Income received':'الدخل المحصل',
  'Reinvested amount':'المبلغ المعاد استثماره',
  'Cash retained':'النقد المحتفظ به',
  'Yield':'العائد',
  'Fees & taxes':'الرسوم والضرائب',
  'Net cash flow':'صافي التدفق النقدي',
  'Dividends':'توزيعات الأرباح',
  'Deposit interest':'فوائد الودائع',
  'Fund distributions':'توزيعات الصناديق',
  'Private credit':'الائتمان الخاص',
  'Rental income':'دخل الإيجارات',
  'Customized Wealth Report':'تقرير الثروة المخصص',
  'selected metrics':'مؤشرات محددة',
  'data sources':'مصادر بيانات',
  'Updated':'آخر تحديث',
  'Reset':'إعادة الضبط',
  'Refreshing…':'جارٍ التحديث…',
  'Total income':'إجمالي الدخل',
  'Received during period':'المحصل خلال الفترة',
  'Reinvested':'المعاد استثماره',
  'of income':'من الدخل',
  'Retained cash':'النقد المحتفظ به',
  'Available liquidity':'السيولة المتاحة',
  'Income allocation':'توزيع الدخل',
  'How received income was used':'كيفية استخدام الدخل المحصل',
  'Retained as cash':'محتفظ به نقدًا',
  'Income source breakdown':'تفصيل مصادر الدخل',
  'Income, reinvestment, and remaining cash by source':'الدخل وإعادة الاستثمار والنقد المتبقي حسب المصدر',
  'Build a new report':'أنشئ تقريرًا جديدًا',
  'Select the report type, sources, metrics, period, and currency, then generate a fresh report.':'حدد نوع التقرير والمصادر والمؤشرات والفترة والعملة، ثم أنشئ التقرير.',
  'Edit Bank Account':'تعديل الحساب البنكي',
  'Account Number Correction':'تصحيح رقم الحساب',
  'Same Account Identity':'هوية الحساب نفسها',
  'Correction reason is required.':'سبب التصحيح مطلوب.',
  'Explain why the account number is being corrected':'اشرح سبب تصحيح رقم الحساب',
  'All previous transactions remain linked to this account. Repeated corrections may reduce accounting record quality.':'ستبقى جميع العمليات السابقة مرتبطة بهذا الحساب. قد يؤثر تكرار التصحيح في جودة السجل المحاسبي.',
  'Bank account updated successfully.':'تم تحديث الحساب البنكي بنجاح.',
  'IBAN or account number must contain at least 4 characters.':'يجب ألا يقل رقم الآيبان أو الحساب عن 4 أحرف.',
  'This bank account is already registered. Merging requires a separate workflow.':'هذا الحساب البنكي مسجل مسبقًا. يتطلب الدمج مسارًا مستقلًا.',
  'Cash on hand':'نقد باليد',
  'Bank cash':'نقد بنكي',
  'Brokerage cash':'نقد الوساطة',
  'Cash account':'حساب نقدي',
  'Loading cash…':'جارٍ تحميل النقد…',
  'Unable to load cash:':'تعذر تحميل النقد:',
  'Cash Assets':'الأصول النقدية',
  'View cash on hand, bank balances, and brokerage cash in one place.':'اعرض النقد باليد والأرصدة البنكية ونقد الوساطة في مكان واحد.',
  'Move Cash':'نقل النقد',
  'Total Cash':'إجمالي النقد',
  'Total':'الإجمالي',
  'Available across cash accounts':'المتاح عبر الحسابات النقدية',
  'Physical cash asset':'أصل نقدي فعلي',
  'Bank balances':'الأرصدة البنكية',
  'posted accounts':'حسابات مُرحّلة',
  'Drawn by investment purchases':'مسحوب بسبب مشتريات استثمارية',
  'Available for trading':'متاح للتداول',
  'Cash Sources':'مصادر النقد',
  'Live balances from posted accounting operations.':'أرصدة حية من العمليات المحاسبية المُرحّلة.',
  'Bank account':'حساب بنكي',
  'Classification':'التصنيف',
  'Financial Intelligence':'الذكاء المالي',
  'Build focused reports from your income, cash flow, and financial activity.':'أنشئ تقارير مركزة من دخلك وتدفقاتك النقدية وأنشطتك المالية.',
  'Save Template':'حفظ القالب',
  'Build Your Report':'أنشئ تقريرك',
  'Report Type':'نوع التقرير',
  'This month':'هذا الشهر',
  'THIS MONTH':'هذا الشهر',
  'Year To Date':'منذ بداية السنة',
  'Date Range':'نطاق التاريخ',
  'To':'إلى',
  'Income Sources':'مصادر الدخل','Source':'المصدر',
  'Included Metrics':'المؤشرات المضمنة',
  'All Portfolios & Assets':'جميع المحافظ والأصول',
  'Report Currency':'عملة التقرير',
  'Generate Report':'إنشاء التقرير',
  'Income & Reinvestment':'الدخل وإعادة الاستثمار',
  'Cash Flow Statement':'قائمة التدفقات النقدية',
  'Portfolio Performance':'أداء المحفظة',
  'Income By Asset':'الدخل حسب الأصل',
  'Expense Analysis':'تحليل المصروفات',
  'Net Worth Movement':'حركة صافي الثروة',
  'Custom Report':'تقرير مخصص',
  'Income Collected':'الدخل المحصل',
  'Amount Reinvested':'المبلغ المعاد استثماره',
  'Cash Retained':'النقد المحتفظ به',
  'Fees & Taxes':'الرسوم والضرائب',
  'Net Cash Flow':'صافي التدفق النقدي',
  'Deposit Interest':'فوائد الودائع',
  'Fund Distributions':'توزيعات الصناديق',
  'Rental Income':'دخل الإيجارات',
  'Custom Wealth Report':'تقرير الثروة المخصص',
  'Selected Metrics':'مؤشرات محددة',
  'Data Sources':'مصادر بيانات',
  'Last Updated':'آخر تحديث',
  'Total Income':'إجمالي الدخل',
  'Collected During The Period':'المحصل خلال الفترة',
  'Of Income':'من الدخل',
  'Available Liquidity':'السيولة المتاحة',
  'Income Allocation':'توزيع الدخل',
  'How collected income is used':'كيفية استخدام الدخل المحصل',
  'Held As Cash':'محتفظ به نقدًا',
  'Income Source Breakdown':'تفصيل مصادر الدخل',
  'Build A New Report':'أنشئ تقريرًا جديدًا',
  'Select the report type, sources, metrics, period, and currency, then generate your report.':'حدد نوع التقرير والمصادر والمؤشرات والفترة والعملة، ثم أنشئ التقرير.',
  'Saudi Riyal':'الريال السعودي',
  'US Dollar':'الدولار الأمريكي',
  'Euro':'اليورو',
  'British Pound':'الجنيه الإسترليني',
  'Japanese Yen':'الين الياباني',
  'UAE Dirham':'الدرهم الإماراتي',
  'Kuwaiti Dinar':'الدينار الكويتي',
  'Loading positions…':'جارٍ تحميل المراكز…',
  'Unable to load positions:':'تعذر تحميل المراكز:',
  'No portfolio positions found.':'لم يُعثر على مراكز استثمارية.',
  'Review listed holdings, market values, allocation, and unrealized performance.':'راجع المراكز المدرجة والقيم السوقية والتوزيع والأداء غير المحقق.',
  'Positions':'المراكز',
  'Market value':'القيمة السوقية',
  'Unrealized return':'العائد غير المحقق',
  'No Market Prices Yet':'لا توجد أسعار سوقية بعد',
  'Latest Available By Exchange':'آخر سعر متاح حسب السوق',
  'Previous Close':'الإغلاق السابق',
  'Live':'مباشر',
  'Delayed':'متأخر',
  'As Of':'كما في',
  'Invalid position route.':'مسار المركز غير صالح.',
  'Loading position...':'جارٍ تحميل المركز...',
  'Failed to load position:':'تعذر تحميل المركز:',
  'Position not found.':'لم يُعثر على المركز.',
  'Investment Income':'دخل الاستثمار','All Cash Flows':'جميع التدفقات النقدية','Upcoming':'قادم','Unable to load investment cash flows.':'تعذر تحميل التدفقات النقدية الاستثمارية.','Distribution':'توزيع','Interest & Yield':'فوائد وعوائد','Principal Return':'استرداد أصل المبلغ','Maturity Proceeds':'متحصلات الاستحقاق','WEEKLY':'أسبوعي','IRREGULAR':'غير منتظم','Investment Property':'عقار استثماري',
  'Distributions, rent, yield, principal returns, and maturity proceeds in one place.':'التوزيعات والإيجارات والعوائد واسترداد الأصل ومتحصلات الاستحقاق في مكان واحد.',
  'Expected Net Cash':'صافي النقد المتوقع',
  'upcoming events':'أحداث قادمة',
  'Awaiting Receipt':'بانتظار التحصيل',
  'Due dates already reached':'مواعيد الاستحقاق قد حلّت',
  'Received':'تم التحصيل',
  'Posted investment income':'دخل استثماري مُرحّل',
  'Loading investment cash flows…':'جارٍ تحميل التدفقات النقدية الاستثمارية…',
  'Asset':'الأصل',
  'Cash Flow':'التدفق النقدي',
  'Gross':'الإجمالي قبل الاستقطاعات',
  'Tax':'الضريبة',
  'Net':'الصافي',
  'Status':'الحالة',
  'No cash flows in this view':'لا توجد تدفقات نقدية في هذا العرض',
  'Upcoming and posted investment proceeds will appear here.':'ستظهر هنا متحصلات الاستثمار القادمة والمُرحّلة.',
  'Accounting distinction':'تمييز محاسبي',
  'Distributions, rent, and yield are income. Principal returns and saving-circle payouts reduce the related asset instead of creating income.':'التوزيعات والإيجارات والعوائد دخل. أما استرداد الأصل ودفعات الجمعيات فتخفض الأصل المرتبط بدلًا من إنشاء دخل.',
  'Alternatives':'البدائل',
  'Portfolio Management':'إدارة المحفظة',
  'Record Property Income':'تسجيل دخل عقار',
  'Record Property Expense':'تسجيل مصروف عقار',
  'Add Property':'إضافة عقار',
  'Property Value':'قيمة العقار',
  'active properties':'عقارات نشطة',
  'Posted Property Income':'دخل العقارات المُرحّل',
  'Recorded through Income':'مسجّل عبر الدخل',
  'Investment properties only':'العقارات الاستثمارية فقط',
  'Net Property Income':'صافي دخل العقارات',
  'Income less linked expenses':'الدخل بعد خصم المصروفات المرتبطة',
  'Loading property records…':'جارٍ تحميل سجلات العقارات…',
  'Property Performance':'أداء العقارات',
  'Executive view of property value, income, costs, and net return.':'نظرة تنفيذية على قيمة العقارات ودخلها وتكاليفها وصافي عائدها.',
  'Rental income already posted through the Income workspace.':'دخل الإيجارات المُرحّل سابقًا عبر مساحة عمل الدخل.',
  'Investment-property costs already posted through the Expense workspace.':'تكاليف العقارات الاستثمارية المُرحّلة سابقًا عبر مساحة عمل المصروفات.',
  'One accounting record shared across Properties, Income, and Expense.':'سجل محاسبي واحد مشترك بين العقارات والدخل والمصروفات.',
  'Expenses':'المصروفات',
  'Actions':'الإجراءات',
  'No properties have been added yet.':'لم تُضف أي عقارات بعد.',
  'Use the action above to record the first entry.':'استخدم الإجراء أعلاه لتسجيل أول قيد.',
  'Shared accounting source':'مصدر محاسبي مشترك',
  'These pages do not duplicate transactions. They display entries recorded in Income and Expense, filtered by their linked property.':'لا تكرر هذه الصفحات العمليات. بل تعرض القيود المسجلة في الدخل والمصروفات بعد تصفيتها بحسب العقار المرتبط.',
  'Personal attention center':'مركز المتابعة الشخصية',
  'Focus':'التركيز',
  'Real upcoming obligations and distribution events.':'الالتزامات وأحداث التوزيع القادمة الفعلية.',
  'Live items':'عناصر مباشرة',
  'Upcoming distributions':'توزيعات قادمة',
  'Next 30 days':'الثلاثون يومًا القادمة',
  'High priority':'أولوية عالية',
  'Act soon':'تصرّف قريبًا',
  'All focus items':'جميع عناصر التركيز',
  'Ordered from your posted data':'مرتبة من بياناتك المُرحّلة',
  'All':'الكل',
  'Medium':'متوسط',
  'No live items match this filter.':'لا توجد عناصر مباشرة تطابق هذا المرشح.',
  'Rent Collection':'تحصيل الإيجار',
  'Due Today':'مستحق اليوم',
  'Due Tomorrow':'مستحق غدًا',
  'Your consolidated wealth dashboard':'لوحة ثروتك الموحدة',
  'Search every record and destination':'ابحث في كل سجل ووجهة',
  'Uploaded financial documents and extracted operations':'المستندات المالية المرفوعة والعمليات المستخرجة',
  'All available financial operations':'كل العمليات المالية المتاحة',
  'Items that need your attention':'العناصر التي تحتاج إلى انتباهك',
  'Posted financial activity':'النشاط المالي المُرحّل',
  'Wealth allocation, deposits, and investments':'توزيع الثروة والودائع والاستثمارات',
  'Listed securities and market positions':'الأوراق المالية المدرجة والمراكز السوقية',
  'Distributions, rent, yield, principal returns, and maturities':'التوزيعات والإيجارات والعوائد واسترداد الأصل والاستحقاقات',
  'Property executive summary and values':'الملخص التنفيذي للعقارات وقيمها',
  'Rental income linked to properties':'دخل الإيجار المرتبط بالعقارات',
  'Maintenance and investment-property costs':'تكاليف الصيانة والعقارات الاستثمارية',
  'Deposit balances, returns, and maturities':'أرصدة الودائع وعوائدها واستحقاقاتها',
  'Crowdfunding, private sukuk, private credit, and managed portfolios':'التمويل الجماعي والصكوك الخاصة والائتمان الخاص والمحافظ المدارة',
  'Contributions, payout order, and circle receivables':'المساهمات وترتيب الاستلام ومستحقات الجمعيات',
  'Managed portfolios, crowdfunding, sukuk, and saving providers':'مقدمو المحافظ المدارة والتمويل الجماعي والصكوك والادخار',
  'Cash on hand, bank balances, and brokerage cash':'النقد باليد والأرصدة البنكية ونقد الوساطة',
  'Registered investment brokers':'وسطاء الاستثمار المسجلون',
  'Bank balances and cash movement':'الأرصدة البنكية وحركة النقد',
  'Credit balances, limits, statements, and upcoming payments':'أرصدة الائتمان وحدوده وكشوفه والمدفوعات القادمة',
  'Cash flow, balance sheet, and income statement':'التدفق النقدي والميزانية وقائمة الدخل',
  'Imported operations awaiting review':'عمليات مستوردة بانتظار المراجعة',
  'Every posted debit and credit':'كل مدين ودائن مُرحّل',
  'Balanced entries from real operations':'قيود متوازنة من عمليات فعلية',
  'Bank and card matching':'مطابقة البنوك والبطاقات',
  'Save flexible monthly summaries without locking transactions':'احفظ ملخصات شهرية مرنة دون قفل العمليات',
  'Live reports from posted entries':'تقارير مباشرة من القيود المُرحّلة',
  'Workspace settings overview':'نظرة عامة على إعدادات مساحة العمل',
  'Personal details and user identity':'البيانات الشخصية وهوية المستخدم',
  'Security':'الأمان',
  'Password and account protection':'كلمة المرور وحماية الحساب',
  'Enabled and base currencies':'العملات المفعلة والأساسية',
  'Backup and account deletion':'النسخ الاحتياطي وحذف الحساب',
  'Investment Providers':'مقدمو خدمات الاستثمار',
  'Managed portfolios, crowdfunding, sukuk, real estate, and saving-circle providers.':'مقدمو المحافظ المدارة والتمويل الجماعي والصكوك والعقارات والجمعيات المالية.',
  'Search platforms in Arabic or English':'ابحث عن المنصات بالعربية أو الإنجليزية',
  'Website':'الموقع الإلكتروني',
  'Savings & Receivables':'الادخار والمستحقات',
  'Track contributions, payout order, and the amount still owed to or by each circle.':'تابع المساهمات وترتيب الاستلام والمبلغ المتبقي لك أو عليك في كل جمعية.',
  'Add Saving Circle':'إضافة جمعية مالية',
  'Active Circles':'الجمعيات النشطة',
  'Net Circle Receivable':'صافي مستحقات الجمعيات',
  'Circle':'الجمعية',
  'Installment':'القسط',
  'Progress':'التقدم',
  'Payout':'الاستلام',
  'No saving circles recorded yet.':'لم تُسجل أي جمعيات مالية بعد.',
  'Existing paid installments move from bank cash into a circle receivable.':'تُنقل الأقساط المدفوعة سابقًا من النقد البنكي إلى مستحقات الجمعية.',
  'Platform':'المنصة',
  'Hakbah or manual circle':'هكبة أو جمعية يدوية',
  'Circle Name':'اسم الجمعية',
  'Funding Bank':'البنك المموّل',
  'Installment Amount':'مبلغ القسط',
  'Frequency':'الدورية',
  'Monthly':'شهري',
  'Weekly':'أسبوعي',
  'Total Installments':'إجمالي الأقساط',
  'Payout Installment':'قسط الاستلام',
  'Already Paid':'المدفوع سابقًا',
  'Start Date':'تاريخ البدء',
  'Payout Date':'تاريخ الاستلام',
  'Add Circle':'إضافة الجمعية',
  'Unable to add saving circle.':'تعذر إضافة الجمعية المالية.',
  'Private Markets':'الأسواق الخاصة',
  'Crowdfunding, private sukuk, private credit, managed portfolios, and fractional real estate.':'التمويل الجماعي والصكوك الخاصة والائتمان الخاص والمحافظ المدارة والعقارات المجزأة.',
  'Add Investment':'إضافة استثمار',
  'Active Investments':'الاستثمارات النشطة',
  'Current Value':'القيمة الحالية',
  'Platforms Used':'المنصات المستخدمة',
  'Investment':'الاستثمار',
  'Expected Return':'العائد المتوقع',
  'No alternative investments recorded yet.':'لم تُسجل استثمارات بديلة بعد.',
  'Add Alternative Investment':'إضافة استثمار بديل',
  'The principal will move from the selected bank into the appropriate investment ledger.':'سينتقل أصل المبلغ من البنك المحدد إلى دفتر الاستثمار المناسب.',
  'Investment Name':'اسم الاستثمار',
  'Investment Type':'نوع الاستثمار',
  'Expected Annual Return %':'العائد السنوي المتوقع %',
  'Investment Date':'تاريخ الاستثمار',
  'Distribution Frequency':'دورية التوزيع',
  'Next Distribution':'التوزيع القادم',
  'Unable to add investment.':'تعذر إضافة الاستثمار.',
  'Debt Crowdfunding':'تمويل جماعي بالدين',
  'Equity Crowdfunding':'تمويل جماعي بالملكية',
  'Real Estate Crowdfunding':'تمويل جماعي عقاري',
  'P2p Lending':'إقراض من نظير إلى نظير',
  'Private Equity':'ملكية خاصة',
  'Venture Capital':'رأس مال جريء',
  'Private Sukuk':'صكوك خاصة',
  'Managed Portfolio':'محفظة مدارة',
  'Semi Annual':'نصف سنوي',
  'Annual':'سنوي',
  'UPCOMING':'قادم',
  'AWAITING':'بانتظار التحصيل',
  'RECEIVED':'تم التحصيل',
  'DIVIDEND':'توزيعات أرباح',
  'RENT':'إيجار',
  'YIELD':'عائد',
  'PRINCIPAL RETURN':'استرداد أصل المبلغ',
  'One-time':'مرة واحدة',
  'Record Receipt':'تسجيل التحصيل',
  'high':'عالية',
  'medium':'متوسطة',
  'low':'منخفضة',
  'Understand your cash movement and consolidated financial position.':'افهم حركة النقد ومركزك المالي الموحّد.',
  'Accounting views':'عروض المحاسبة',
  'Balance Sheet':'الميزانية',
  'Liabilities & Loans':'الالتزامات والقروض',
  'Displayed period':'الفترة المعروضة',
  'Current live period':'الفترة الحية الحالية',
  'Compare months, quarters, and years':'مقارنة الأشهر والأرباع والسنوات',
  'Cash Inflow':'التدفقات النقدية الداخلة',
  'Cash Outflow':'التدفقات النقدية الخارجة',
  'Posted':'مُرحّل',
  'Positive':'موجب',
  'Negative':'سالب',
  'Posted operations':'العمليات المُرحّلة',
  'Cash Flow Movement':'حركة التدفق النقدي',
  'Confirmed movements from posted operations':'الحركات المؤكدة من العمليات المُرحّلة',
  'External cash inflow':'تدفق نقدي خارجي داخل',
  'External cash outflow':'تدفق نقدي خارجي خارج',
  'In':'داخل',
  'Out':'خارج',
  'Net Cash Movement':'صافي حركة النقد',
  'Income & Expenses':'الدخل والمصروفات',
  'Recognized Income':'الدخل المعترف به',
  'Recognized Expenses':'المصروفات المعترف بها',
  'Scheduled Debt Payments':'دفعات الدين المجدولة',
  'Total Assets':'إجمالي الأصول',
  'Total Liabilities':'إجمالي الالتزامات',
  'From posted operations':'من العمليات المُرحّلة',
  'of assets':'من الأصول',
  'Assets minus liabilities':'الأصول ناقص الالتزامات',
  'Assets':'الأصول',
  'Posted debit balances and reclassified items':'الأرصدة المدينة المُرحّلة والبنود المعاد تصنيفها',
  'No posted assets':'لا توجد أصول مُرحّلة',
  'Liabilities & Net Worth':'الالتزامات وصافي الثروة',
  "Liabilities plus the owner's net position":'الالتزامات مضافًا إليها صافي مركز المالك',
  'No posted liabilities':'لا توجد التزامات مُرحّلة',
  'Liabilities + Net Worth':'الالتزامات + صافي الثروة',
  'Search and review every posted debit and credit movement.':'ابحث وراجع كل حركة مدينة ودائنة مُرحّلة.',
  'Review balanced entries generated by actual operations.':'راجع القيود المتوازنة الناتجة عن العمليات الفعلية.',
  'Match account and card transactions with WealthOS records.':'طابق عمليات الحسابات والبطاقات مع سجلات WealthOS.',
  'Unable to load posted journal entries.':'تعذر تحميل قيود اليومية المُرحّلة.',
  'Account code':'رمز الحساب',
  'Debit':'مدين',
  'Credit':'دائن',
  'Related reference':'المرجع المرتبط',
  'Search in':'البحث في',
  'All dates':'كل التواريخ',
  'All accounts':'كل الحسابات',
  'Loading posted records…':'جارٍ تحميل السجلات المُرحّلة…',
  'Posted operation':'عملية مُرحّلة',
  'No reconciliation items yet.':'لا توجد بنود تسوية بعد.',
  'No posted records match the filters.':'لا توجد سجلات مُرحّلة تطابق المرشحات.',
  'Unable to perform reconciliation.':'تعذر تنفيذ التسوية.',
  'Matched':'مطابق',
  'Confirmed posted operations':'عمليات مُرحّلة مؤكدة',
  'Suggested Matches':'مطابقات مقترحة',
  'Amount and date match':'المبلغ والتاريخ متطابقان',
  'Needs Review':'يحتاج إلى مراجعة',
  'Reconciliation Results':'نتائج التسوية',
  'Match imported statement transactions with actual posted journal entries.':'طابق عمليات الكشف المستوردة مع قيود اليومية الفعلية المُرحّلة.',
  'Search reconciled transactions':'البحث في العمليات المسوّاة',
  'Performing reconciliation…':'جارٍ تنفيذ التسوية…',
  'Reconciliation failed':'فشلت التسوية',
  'No date':'بلا تاريخ',
  'Imported operation':'عملية مستوردة',
  'Suggested':'مقترح',
  'No statement transactions need reconciliation':'لا توجد عمليات كشف تحتاج إلى تسوية',
  'Import a bank or card statement to see its transactions here.':'استورد كشف بنك أو بطاقة لعرض عملياته هنا.',
  'Financial preferences':'التفضيلات المالية',
  'Choose your reporting currency and every currency used across your wealth.':'اختر عملة التقارير وكل عملة مستخدمة ضمن ثروتك.',
  'Base reporting currency':'عملة التقارير الأساسية',
  'Net worth and consolidated financial statements use this currency.':'يستخدم صافي الثروة والقوائم المالية الموحدة هذه العملة.',
  'Enabled currencies':'العملات المفعلة',
  'Select every currency you expect to use. You can change this later.':'حدد كل عملة تتوقع استخدامها. يمكنك تغيير ذلك لاحقًا.',
  'Base':'أساسية',
  'Multi-currency accounting':'محاسبة متعددة العملات',
  'Every transaction keeps its original currency, exchange rate, and value in your base currency.':'تحتفظ كل عملية بعملتها الأصلية وسعر الصرف وقيمتها بعملتك الأساسية.',
  'Exchange rates':'أسعار الصرف',
  'Rates shown in this prototype are indicative. A live rate provider will replace them before production use.':'الأسعار المعروضة في هذا النموذج إرشادية. سيحل محلها مزود أسعار مباشر قبل الاستخدام الإنتاجي.',
  'Loading…':'جارٍ التحميل…',
  'Account':'الحساب',
  'Accounts Payable':'الحسابات الدائنة',
  'Accounts Receivable':'الحسابات المدينة',
  'Accrued Expenses':'المصروفات المستحقة',
  'Advisory Fees':'رسوم الاستشارات',
  'Bank Fees':'الرسوم البنكية',
  'Bonds':'السندات',
  'Books & Supplies':'الكتب والمستلزمات',
  'Brokerage Fees':'رسوم الوساطة',
  'Business Income':'دخل الأعمال',
  'Capital Contributions':'المساهمات الرأسمالية',
  'Capital Gains':'الأرباح الرأسمالية',
  'Capital Injection':'ضخ رأس المال',
  'Cash & Cash Equivalents':'النقد وما في حكمه',
  'Cashback & Rewards':'الاسترداد النقدي والمكافآت',
  'Credit Card Fees':'رسوم بطاقات الائتمان',
  'Crowdfunding Investments':'استثمارات التمويل الجماعي',
  'Crypto':'الأصول المشفرة',
  'Current Liabilities':'الالتزامات المتداولة',
  'Current Year Earnings':'أرباح السنة الحالية',
  'Digital Wallets':'المحافظ الرقمية',
  'Dividend Income':'دخل توزيعات الأرباح',
  'Donations & Gifts':'التبرعات والهدايا',
  'Education Expenses':'مصروفات التعليم',
  'Entertainment':'الترفيه',
  'Equity':'حقوق الملكية',
  'Finance Costs':'تكاليف التمويل',
  'Fixed Assets':'الأصول الثابتة',
  'Food & Groceries':'الطعام والبقالة',
  'Foreign Currency Cash':'نقد بالعملات الأجنبية',
  'Fuel':'الوقود',
  'General Insurance':'التأمين العام',
  'Health Insurance':'التأمين الصحي',
  'Healthcare Expenses':'مصروفات الرعاية الصحية',
  'Home Maintenance':'صيانة المنزل',
  'Home Services':'الخدمات المنزلية',
  'Housing Expenses':'مصروفات السكن',
  'Income Taxes':'ضرائب الدخل',
  'Inherited Wealth':'الثروة الموروثة',
  'Interest Income':'دخل الفوائد',
  'Investment Expenses':'مصروفات الاستثمار',
  'Liabilities':'الالتزامات',
  'Living Expenses':'مصروفات المعيشة',
  'Loan Interest':'فوائد القروض',
  'Long-Term Liabilities':'الالتزامات طويلة الأجل',
  'Long-Term Loans':'القروض طويلة الأجل',
  'Market Data & Subscriptions':'بيانات السوق والاشتراكات',
  'Medical':'العلاج',
  'Miscellaneous Expenses':'مصروفات متنوعة',
  'Mutual Funds':'صناديق الاستثمار',
  'Options':'عقود الخيارات',
  'Other Current Assets':'أصول متداولة أخرى',
  'Other Current Liabilities':'التزامات متداولة أخرى',
  'Other Education Expenses':'مصروفات تعليم أخرى',
  'Other Expenses':'مصروفات أخرى',
  'Other Finance Costs':'تكاليف تمويل أخرى',
  'Other Fixed Assets':'أصول ثابتة أخرى',
  'Other Healthcare Expenses':'مصروفات رعاية صحية أخرى',
  'Other Housing Expenses':'مصروفات سكن أخرى',
  'Other Income':'دخل آخر',
  'Other Investment Expenses':'مصروفات استثمار أخرى',
  'Other Investments':'استثمارات أخرى',
  'Other Living Expenses':'مصروفات معيشة أخرى',
  'Other Long-Term Liabilities':'التزامات طويلة الأجل أخرى',
  'Other Taxes':'ضرائب أخرى',
  'Other Transportation Expenses':'مصروفات نقل أخرى',
  'Owner Drawings':'مسحوبات المالك',
  "Owner's Equity":'حقوق ملكية المالك',
  'Parking & Tolls':'مواقف ورسوم طرق',
  'Personal Capital':'رأس المال الشخصي',
  'Personal Care':'العناية الشخصية',
  'Pharmacy':'الصيدلية',
  'Property Taxes':'ضرائب العقارات',
  'Public Transportation':'النقل العام',
  'Retained Earnings':'الأرباح المحتجزة',
  'Revenue':'الإيرادات',
  'Salary Income':'دخل الراتب',
  'Saudi Stocks':'الأسهم السعودية',
  'Shopping':'التسوق',
  'Short-Term Loans':'القروض قصيرة الأجل',
  'Taxes':'الضرائب',
  'Time Deposits':'الودائع لأجل',
  'Transportation Expenses':'مصروفات النقل',
  'Travel':'السفر',
  'Tuition & Schooling':'الرسوم الدراسية والتعليم',
  'US Stocks':'الأسهم الأمريكية',
  'Utilities':'المرافق',
  'Vehicle Insurance':'تأمين المركبات',
  'Vehicle Maintenance':'صيانة المركبات',
  'Vehicles':'المركبات',
  'Review this investment position, valuation, performance, and trade history.':'راجع هذا المركز الاستثماري وتقييمه وأداءه وسجل تداولاته.',
  'Quantity':'الكمية',
  'Average Cost':'متوسط التكلفة',
  'Market Price':'سعر السوق',
  'Price As Of':'السعر كما في',
  'Cost Basis':'أساس التكلفة',
  'Unrealized P/L':'الربح/الخسارة غير المحققة',
  'Exchange':'السوق',
  'Security Type':'نوع الورقة المالية',
  'Trade History':'سجل التداول',
  'No trades available.':'لا توجد تداولات.',
  'Date':'التاريخ',
  'Side':'الجانب',
  'Price':'السعر',
  'Commission':'العمولة',
  'Symbol':'الرمز',
  'Fair Value':'القيمة العادلة',
  'BUY':'شراء',
  'SELL':'بيع',
  'STOCK':'سهم',
  'ETF':'صندوق مؤشرات',
  'REIT':'صندوق عقاري متداول',
  'Saudi Exchange':'السوق المالية السعودية',
  'Nasdaq':'ناسداك',
  'New York Stock Exchange':'بورصة نيويورك',
  'NYSE American':'بورصة نيويورك الأمريكية',
  'Short-term loan':'قرض قصير الأجل',
  'Long-term loan':'قرض طويل الأجل',
  'Mortgage':'رهن عقاري',
  'Complete all required fields before creating the loan.':'أكمل جميع الحقول المطلوبة قبل إنشاء القرض.',
  'The amount received plus fees must equal the loan principal.':'يجب أن يساوي المبلغ المستلم مضافًا إليه الرسوم أصل مبلغ القرض.',
  'Loan created and posted to the General Ledger.':'تم إنشاء القرض وترحيله إلى دفتر الأستاذ العام.',
  'Unable to create the loan.':'تعذر إنشاء القرض.',
  'Enter loan details to build the preview.':'أدخل بيانات القرض لبناء المعاينة.',
  'Financing Summary':'ملخص التمويل',
  'Principal Amount':'أصل المبلغ',
  'Net Amount Received':'صافي المبلغ المستلم',
  'Upfront Fees':'الرسوم المقدمة',
  'Monthly Payment':'الدفعة الشهرية',
  'Expected Total Repayment':'إجمالي السداد المتوقع',
  'Expected Financing Cost':'تكلفة التمويل المتوقعة',
  'Balanced accounting entry':'قيد محاسبي متوازن',
  'Amounts are not balanced':'المبالغ غير متوازنة',
  'Bank financing plus fees equals the loan liability.':'التمويل البنكي مضافًا إليه الرسوم يساوي التزام القرض.',
  'Liability Account':'حساب الالتزام',
  'First Payment':'أول دفعة',
  'Not set':'غير محدد',
  'Annual Rate':'المعدل السنوي',
  'Loan Name':'اسم القرض',
  'Home financing':'تمويل المنزل',
  'Lender':'المموّل',
  'Bank or finance company':'بنك أو شركة تمويل',
  'Loan Type':'نوع القرض',
  'Loan Principal':'أصل مبلغ القرض',
  'Receiving Bank Account':'الحساب البنكي المستلم',
  'Annual Rate %':'المعدل السنوي %',
  'Term in Months':'المدة بالأشهر',
  'First Payment Date':'تاريخ أول دفعة',
  'Financing is posted to the primary bank account and the liability is created automatically.':'يُرحّل التمويل إلى الحساب البنكي الرئيسي ويُنشأ الالتزام تلقائيًا.',
  'Creating…':'جارٍ الإنشاء…',
  'Review & Create Loan':'مراجعة وإنشاء القرض',
  'Unable to prepare the monthly snapshot.':'تعذر إعداد اللقطة الشهرية.',
  'Saving monthly snapshot…':'جارٍ حفظ اللقطة الشهرية…',
  'Monthly snapshot saved. You can continue editing operations and save a newer version when needed.':'تم حفظ اللقطة الشهرية. يمكنك متابعة تعديل العمليات وحفظ نسخة أحدث عند الحاجة.',
  'Unable to save this monthly snapshot.':'تعذر حفظ هذه اللقطة الشهرية.',
  'Personal Wealth Record':'سجل الثروة الشخصية',
  'Review and save a flexible summary for each month without locking your operations.':'راجع واحفظ ملخصًا مرنًا لكل شهر دون قفل عملياتك.',
  'Snapshot Month':'شهر اللقطة',
  'Preparing period…':'جارٍ إعداد الفترة…',
  'Data matches':'البيانات متطابقة',
  'Review required':'المراجعة مطلوبة',
  'Save Newer Version':'حفظ نسخة أحدث',
  'Save Snapshot':'حفظ اللقطة',
  'Operating Cash Flow':'التدفق النقدي التشغيلي',
  'Posted cash movements':'الحركات النقدية المُرحّلة',
  'Investing Cash Flow':'التدفق النقدي الاستثماري',
  'Asset purchases and proceeds':'مشتريات الأصول ومتحصلاتها',
  'Net Change in Cash':'صافي التغير في النقد',
  'For the selected month':'للشهر المحدد',
  'Closing Net Worth':'صافي الثروة الختامي',
  'Balance sheet snapshot':'لقطة الميزانية',
  'Data Quality Check':'فحص جودة البيانات',
  'Differences must be resolved before saving the snapshot.':'يجب معالجة الفروقات قبل حفظ اللقطة.',
  'Records':'السجلات',
  'Balanced Journal Entries':'قيود يومية متوازنة',
  'entries need review':'قيد يحتاج إلى مراجعة',
  'All posted entries are balanced':'جميع القيود المُرحّلة متوازنة',
  'Snapshot History':'سجل اللقطات',
  'Saved versions do not prevent you from correcting personal operations.':'النسخ المحفوظة لا تمنعك من تصحيح عملياتك الشخصية.',
  'Saved at':'حُفظت في',
  'Verification code':'رمز التحقق',
  'Draft':'مسودة',
  'No monthly snapshots have been saved yet.':'لا توجد لقطات شهرية محفوظة حتى الآن.',
  'Switch to Arabic':'التبديل إلى العربية',
  'Switch to English':'التبديل إلى الإنجليزية',
  'Good Morning':'صباح الخير',
  'Good Afternoon':'نهارك سعيد',
  'Good Evening':'مساء الخير',
  'Wishing You A Productive Morning':'نتمنى لك صباحًا مثمرًا',
  'Wishing You A Successful Day':'نتمنى لك يومًا موفقًا',
  'A Calm Financial Evening':'أمسية مالية هادئة',
  'Unable to read local setup status.':'تعذر قراءة حالة الإعداد المحلية.',
  'Preparing your private workspace…':'جارٍ تجهيز مساحة العمل الخاصة…',
  'PRIVATE LOCAL WORKSPACE':'مساحة عمل محلية خاصة',
  'Recover WealthOS':'استرداد WealthOS',
  'Unlock WealthOS':'فتح WealthOS',
  'Save your new recovery code':'احفظ رمز الاسترداد الجديد',
  'Recovery code':'رمز الاسترداد',
  'Local password':'كلمة المرور المحلية',
  'Password':'كلمة المرور',
  'I saved the code':'حفظت الرمز',
  'Reset password':'إعادة تعيين كلمة المرور',
  'Use recovery code':'استخدام رمز الاسترداد',
  'Unlock':'فتح',
  'Recovery could not be completed.':'تعذر إكمال الاسترداد.',
  'The local password is incorrect.':'كلمة المرور المحلية غير صحيحة.',
  'Payment Method':'طريقة السداد',
  'Bank Transfer':'تحويل بنكي',
  'Cheque':'شيك',
  'Cheque Proceeds':'حصيلة الشيك',
  'Deposit into a bank account':'إيداع في حساب بنكي',
  'Keep as cash on hand':'الاحتفاظ بها كنقد في الصندوق',
  'Current month · Posted':'الشهر الحالي · مُرحّل',
  'Total Expenses':'إجمالي المصروفات',
  'Net Surplus':'صافي الفائض',
  'Margin':'هامش',
  'No posted income':'لا يوجد دخل مُرحّل',
  'Income Statement':'قائمة الدخل',
  'Income and expenses recognized from posted entries':'الدخل والمصروفات المعترف بها من القيود المُرحّلة',
  'No posted income or expenses':'لا يوجد دخل أو مصروفات مُرحّلة',
}

type LanguageContextValue = { language: Language; direction: 'ltr'|'rtl'; setLanguage:(language:Language)=>void; toggleLanguage:()=>void; t:(text:string)=>string }
const LanguageContext=createContext<LanguageContextValue|null>(null)

export function LanguageProvider({children}:{children:ReactNode}){
  const [language,setLanguageState]=useState<Language>(()=>localStorage.getItem('wealthos-language')==='ar'?'ar':'en')
  const setLanguage=useCallback((next:Language)=>{setLanguageState(next);localStorage.setItem('wealthos-language',next)},[])
  useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr'},[language])
  const value=useMemo<LanguageContextValue>(()=>({language,direction:language==='ar'?'rtl':'ltr',setLanguage,toggleLanguage:()=>{const previous=language;const next=language==='ar'?'en':'ar';setLanguage(next);void updatePreferredLanguage(next).catch(()=>setLanguage(previous))},t:(text)=>language==='ar'?(arabic[text]??text):text}),[language,setLanguage])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage(){const value=useContext(LanguageContext);if(!value)throw new Error('useLanguage must be used within LanguageProvider');return value}
