"""Update accounts table

Revision ID: 11b19d7b7427
Revises: 70396bf480fe
Create Date: 2026-07-13 23:25:34.871912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b19d7b7427'
down_revision: Union[str, Sequence[str], None] = '70396bf480fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('normal_balance', sa.String(length=10), nullable=False))
    op.add_column('accounts', sa.Column('is_header', sa.Boolean(), nullable=False))
    op.add_column('accounts', sa.Column('allow_posting', sa.Boolean(), nullable=False))
    # SQLite cannot execute ``ALTER COLUMN ... TYPE`` directly. Alembic's
    # batch operation recreates the table on SQLite and emits a normal ALTER
    # on PostgreSQL, keeping this historical migration portable.
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column('account_type',
                   existing_type=sa.VARCHAR(length=30),
                   type_=sa.String(length=20),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column('account_type',
                   existing_type=sa.String(length=20),
                   type_=sa.VARCHAR(length=30),
                   existing_nullable=False)
    op.drop_column('accounts', 'allow_posting')
    op.drop_column('accounts', 'is_header')
    op.drop_column('accounts', 'normal_balance')
    # ### end Alembic commands ###
