import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { Building2, Check, ChevronDown, Plus, Search } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { createBroker, getBrokerCatalog, getBrokers, type BrokerCatalogItem } from '../services/brokerService'
import OperationForm from './OperationForm'
import { useLanguage } from '../context/LanguageContext'
import { formatDisplayInteger, formatDisplayPercent } from '../utils/localeFormat'
import './AddBrokerOperation.css'

const arabicMap:Record<string,string>={أ:'ا',إ:'ا',آ:'ا',ى:'ي',ة:'ه',ؤ:'و',ئ:'ي'}
const normalize=(value:string)=>value.trim().toLowerCase().replace(/[أإآىةؤئ]/g,char=>arabicMap[char]??char).replace(/[^a-z0-9\u0600-\u06ff]/g,'')
function distance(left:string,right:string){const row=Array.from({length:right.length+1},(_,i)=>i);for(let i=1;i<=left.length;i++){let diagonal=row[0];row[0]=i;for(let j=1;j<=right.length;j++){const above=row[j];row[j]=left[i-1]===right[j-1]?diagonal:Math.min(diagonal,above,row[j-1])+1;diagonal=above}}return row[right.length]}
function isClose(query:string,item:BrokerCatalogItem){const candidate=normalize(query);if(!candidate)return false;return[item.name,...item.aliases].some(label=>{const known=normalize(label);return candidate===known||(Math.min(candidate.length,known.length)>=4&&(candidate.includes(known)||known.includes(candidate)))||distance(candidate,known)/Math.max(candidate.length,known.length)<=.28})}

export default function AddBrokerOperation(){
  const navigate=useNavigate()
  const{t,language}=useLanguage()
  const[catalog,setCatalog]=useState<BrokerCatalogItem[]>([]),[registered,setRegistered]=useState<string[]>([])
  const[query,setQuery]=useState(''),[selected,setSelected]=useState<BrokerCatalogItem|null>(null),[customMode,setCustomMode]=useState(false)
  const[country,setCountry]=useState(''),[website,setWebsite]=useState(''),[menuOpen,setMenuOpen]=useState(false)
  const[commissionRate,setCommissionRate]=useState('')
  const[commissionTaxRate,setCommissionTaxRate]=useState('')
  const[dividendWithholdingTaxRate,setDividendWithholdingTaxRate]=useState('')
  const[message,setMessage]=useState(''),[saved,setSaved]=useState(false),[submitting,setSubmitting]=useState(false)
  const rootRef=useRef<HTMLDivElement>(null)
  useEffect(()=>{Promise.all([getBrokerCatalog(),getBrokers()]).then(([items,brokers])=>{setCatalog(items);setRegistered(brokers.map(item=>normalize(item.name)))}).catch(()=>setMessage(t('Unable to load the broker directory.')))},[t])
  useEffect(()=>{const close=(event:MouseEvent)=>{if(!rootRef.current?.contains(event.target as Node))setMenuOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[])
  const matches=useMemo(()=>{const value=normalize(query);return(value?catalog.filter(item=>[item.name,...item.aliases].some(label=>normalize(label).includes(value))):catalog).slice(0,12)},[catalog,query])
  const closeMatch=useMemo(()=>selected?null:catalog.find(item=>isClose(query,item))??null,[catalog,query,selected])
  const alreadyAdded=registered.includes(normalize(selected?.name??query)),canUseCustom=query.trim().length>=2&&!closeMatch&&!selected
  function choose(item:BrokerCatalogItem){setSelected(item);setQuery(item.name);setCountry(item.country);setWebsite(item.website);setCommissionRate(item.default_commission_rate==null?'':String(item.default_commission_rate));setCommissionTaxRate(item.default_commission_tax_rate==null?'':String(item.default_commission_tax_rate));setDividendWithholdingTaxRate('');setCustomMode(false);setMenuOpen(false);setMessage('')}
  function changeQuery(value:string){setQuery(value);setSelected(null);setCustomMode(false);setCountry('');setWebsite('');setCommissionRate('');setCommissionTaxRate('');setMenuOpen(true);setSaved(false);setMessage('')}
  async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(submitting||alreadyAdded||(!selected&&!customMode)||commissionRate===''||commissionTaxRate==='')return;setSubmitting(true);setMessage('');setSaved(false);try{const name=selected?.name??query.trim();const created=await createBroker({name,country:selected?.country??country.trim(),website:selected?.website??website.trim(),commission_rate:Number(commissionRate),commission_tax_rate:Number(commissionTaxRate),dividend_withholding_tax_rate:dividendWithholdingTaxRate===''?null:Number(dividendWithholdingTaxRate)});navigate(`/investing/brokers?addPortfolio=${created.id}&created=1`)}catch(error){setMessage(t(error instanceof Error?error.message:'Unable to add broker.'));setSubmitting(false)}}
  const preview=<><div className="standard-operation__preview"><span>{t('Investing reference')}</span><strong>{selected?.name||query.trim()||t('New broker')}</strong><small>{t('This broker becomes available in Trade after saving.')}</small></div><div className="income-operation__effects"><h4>{t('Reference details')}</h4><p><span>{t('Country')}</span><strong>{country||t('Not specified')}</strong></p><p><span>{t('Storage')}</span><strong>{t('Broker registry')}</strong></p><p><span>{t('Financial impact')}</span><strong>{t('None until a trade is posted')}</strong></p></div></>
  return<OperationForm title={t('Broker Details')} onSubmit={handleSubmit} preview={preview}>
    <div className="broker-picker" ref={rootRef}><label htmlFor="broker-search">{t('Broker Name')} <abbr className="broker-required-mark" title={t('Required')}>*</abbr></label><div className={`broker-picker__input ${selected?'is-selected':''}`}><Search size={17}/><input id="broker-search" required autoComplete="off" value={query} disabled={submitting} onFocus={()=>setMenuOpen(true)} onChange={event=>changeQuery(event.target.value)} placeholder={t('Search Saudi or US brokers')}/><button type="button" aria-label={t('Open broker list')} onClick={()=>setMenuOpen(open=>!open)}><ChevronDown size={16}/></button></div>
      {menuOpen&&<div className="broker-picker__menu"><div className="broker-picker__menu-head"><span>{t('Broker Directory')}</span><small>{formatDisplayInteger(catalog.length,language)} {t('verified options')}</small></div><div className="broker-picker__results">{matches.map(item=><button type="button" key={item.name} onClick={()=>choose(item)}><span><Building2 size={16}/></span><div><strong>{item.name}</strong><small>{t(item.country)}{item.execution_partner?` · ${t('Via')} ${item.execution_partner}`:''}</small><small className="broker-picker__fees"><b>{t('Commission')}</b> {item.default_commission_rate==null?t('Confirm With Broker'):formatDisplayPercent(item.default_commission_rate,5,language)}<i/> <b>{t('VAT')}</b> {item.default_commission_tax_rate==null?t('Confirm With Broker'):formatDisplayPercent(item.default_commission_tax_rate,2,language)}</small></div>{registered.includes(normalize(item.name))?<em>{t('Added')}</em>:<Check size={15}/>}</button>)}{!matches.length&&<p>{t('No directory result for')} “{query}”.</p>}</div>{canUseCustom&&<button className="broker-picker__custom" type="button" onClick={()=>{setCustomMode(true);setMenuOpen(false)}}><Plus size={15}/> {t('Add')} “{query.trim()}” {t('As A Different Broker')}</button>}</div>}
      {closeMatch&&!selected&&<p className="broker-picker__warning">{t('Did you mean')} <button type="button" onClick={()=>choose(closeMatch)}>{closeMatch.name}</button>? {t('Select the official broker from the list.')}</p>}{alreadyAdded&&query&&<p className="broker-picker__warning">{t('This broker is already registered.')}</p>}</div>
    {selected&&<div className="broker-auto-fill" role="status"><Check size={15}/><span><strong>{selected.name}</strong> {t('selected.')}</span><span>{t('Commission:')} <b>{commissionRate===''?t('Needs Confirmation'):formatDisplayPercent(Number(commissionRate),5,language)}</b></span><span>{t('VAT:')} <b>{commissionTaxRate===''?t('Needs Confirmation'):formatDisplayPercent(Number(commissionTaxRate),2,language)}</b></span></div>}
    <div className="broker-details-row"><div><label>{t('Country')}</label><input value={country} readOnly={Boolean(selected)} disabled={submitting||(!selected&&!customMode)} onChange={event=>setCountry(event.target.value)} placeholder={t(customMode?'Enter country':'Selected automatically')}/></div><div><label>{t('Website')}</label><input type="url" value={website} readOnly={Boolean(selected)} disabled={submitting||(!selected&&!customMode)} onChange={event=>setWebsite(event.target.value)} placeholder={t(customMode?'Website URL optional':'Selected automatically')}/></div></div>
    <div className="broker-rates-row"><div><label><span className="broker-field-label">{t('Commission Rate %')} <abbr className="broker-required-mark" title={t('Required')}>*</abbr></span>{selected&&commissionRate!==''?<small>{t('Auto-Filled')}</small>:selected?.commission_source?<small>{t('Plan Dependent')}</small>:null}</label><input required type="number" min="0" max="100" step="0.00001" value={commissionRate} disabled={submitting||(!selected&&!customMode)} onChange={event=>setCommissionRate(event.target.value)} placeholder={t('Broker Commission %')}/></div><div><label><span className="broker-field-label">{t('VAT On Commission %')} <abbr className="broker-required-mark" title={t('Required')}>*</abbr></span>{selected?.commission_tax_source?<small>{t('Auto-Filled')}</small>:null}</label><input required type="number" min="0" max="100" step="0.01" value={commissionTaxRate} disabled={submitting||(!selected&&!customMode)} onChange={event=>setCommissionTaxRate(event.target.value)} placeholder={t('VAT %')}/></div><div><label>{t('Dividend Withholding Tax %')} <small>{t('Optional Override')}</small></label><input type="number" min="0" max="100" step="0.01" value={dividendWithholdingTaxRate} disabled={submitting||(!selected&&!customMode)} onChange={event=>setDividendWithholdingTaxRate(event.target.value)} placeholder={t('Profile default')}/></div></div>
    <button type="submit" disabled={submitting||alreadyAdded||(!selected&&!customMode)||commissionRate===''||commissionTaxRate==='' }>{t(submitting?'Saving...':'Add Broker')}</button>{message&&<p className={saved?'broker-picker__success':'broker-picker__warning'}>{message}</p>}
  </OperationForm>
}
