/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState, type FormEvent } from 'react'
import { useSearchParams } from 'react-router-dom'
import { CalendarClock, Info, Landmark, Sprout } from 'lucide-react'
import OperationForm from './OperationForm'
import { adjustDepositBalance, createDeposit, updateDeposit } from '../services/accountingService'
import { useFinancialSummary } from '../hooks/useFinancialSummary'
import { useCurrency, type Currency } from '../context/CurrencyContext'
import OperationPreflight from '../components/ui/OperationPreflight'
import { formatWealthDate, normalizeWealthDateInput, parseWealthDate } from '../utils/dateFormat'
import { postingReference, toLocalDateTime, useImportedOperationDraft } from '../hooks/useImportedOperationDraft'
import { useLanguage } from '../context/LanguageContext'

const today=()=>new Date().toISOString().slice(0,10)
const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)
const amountInput=(value:string)=>{const cleaned=value.replace(/[^\d.]/g,'');const[whole='',...decimal]=cleaned.split('.');const grouped=whole.replace(/\B(?=(\d{3})+(?!\d))/g,',');return cleaned.includes('.')?`${grouped}.${decimal.join('').slice(0,2)}`:grouped}
const amountValue=(value:string)=>value.replace(/,/g,'').replace(/[^\d.]/g,'')
const actualDays=(start:string,end:string)=>{if(!start||!end)return 0;const[fromYear,fromMonth,fromDay]=start.split('-').map(Number);const[toYear,toMonth,toDay]=end.split('-').map(Number);return Math.max(0,Math.round((Date.UTC(toYear,toMonth-1,toDay)-Date.UTC(fromYear,fromMonth-1,fromDay))/86400000))}

function FieldInfo(){const[open,setOpen]=useState(false);const{t}=useLanguage();return <span className={`operation-field__info${open?' is-open':''}`} role="button" tabIndex={0} aria-label={t('About deposit balance adjustments')} aria-expanded={open} data-tooltip={t('Use this only to correct a mismatch with the provider. WealthOS keeps the original transaction and posts the difference to or from the funding bank account.')} onClick={event=>{event.preventDefault();setOpen(value=>!value)}} onMouseLeave={()=>setOpen(false)} onBlur={()=>setOpen(false)}><Info size={13}/></span>}

export default function DepositOperation(){
  const imported=useImportedOperationDraft()
  const[searchParams]=useSearchParams();const editId=searchParams.get('edit');const editMode=Boolean(editId)
  const financial=useFinancialSummary();const{formatMoney}=useCurrency();const{t}=useLanguage();const banks=financial.data?.bank_accounts??[]
  const[form,setForm]=useState({provider_name:'',product_name:imported.draft?.description??'',product_type:'TERM_DEPOSIT' as 'TERM_DEPOSIT'|'INCOME_SAVINGS',funding_bank_account_id:'',income_bank_account_id:'',principal_amount:imported.draft?.amount==null?'':String(Math.abs(imported.draft.amount)),annual_return_rate:'',payout_frequency:'MONTHLY' as 'MONTHLY'|'QUARTERLY'|'AT_MATURITY',start_date:(toLocalDateTime(imported.draft?.transaction_date)||localNow()).slice(0,10)||today(),maturity_date:'',auto_renew:false,transaction_date:toLocalDateTime(imported.draft?.transaction_date)||localNow()})
  const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);const[adjusting,setAdjusting]=useState(false);const[adjustment,setAdjustment]=useState({corrected_balance:'',adjustment_date:formatWealthDate(new Date()),reason:''})
  useEffect(()=>{if(!editMode||!financial.data)return;const item=financial.data.deposits.find(deposit=>String(deposit.id)===editId);if(!item){setMessage(t('Deposit not found.'));return}setForm(current=>({...current,provider_name:item.provider_name,product_name:item.product_name,product_type:item.product_type,funding_bank_account_id:String(item.funding_bank_account_id),income_bank_account_id:String(item.income_bank_account_id??item.funding_bank_account_id),principal_amount:String(item.current_balance),annual_return_rate:String(item.annual_return_rate),payout_frequency:item.payout_frequency as typeof current.payout_frequency,start_date:item.start_date,maturity_date:item.maturity_date??'',auto_renew:item.auto_renew}));setAdjustment(current=>({...current,corrected_balance:String(item.current_balance)}))},[editMode,editId,financial.data,t])
  const funding=banks.find(item=>String(item.id)===form.funding_bank_account_id);const destination=banks.find(item=>String(item.id)===(form.income_bank_account_id||form.funding_bank_account_id));const amount=Number(form.principal_amount)||0
  const depositDays=form.product_type==='TERM_DEPOSIT'?actualDays(form.start_date,form.maturity_date):0;const estimatedReturn=amount*(Number(form.annual_return_rate)||0)/100*(form.product_type==='TERM_DEPOSIT'?depositDays/365:1);const currency=(funding?.currency_code??'SAR') as Currency
  const valid=Boolean(funding&&destination&&form.provider_name.trim()&&form.product_name.trim()&&amount>=0&&form.start_date&&(form.product_type==='INCOME_SAVINGS'||form.maturity_date)&&destination.currency_code===funding.currency_code&&(!editMode?amount>0&&amount<=funding.current_balance:true))
  const set=(key:string,value:string|boolean)=>setForm(current=>({...current,[key]:value}));const compatibleBanks=banks.filter(item=>!funding||item.currency_code===funding.currency_code)
  async function submit(event:FormEvent){event.preventDefault();setMessage('');if(!valid)return setMessage(t('Complete the required deposit details.'));setSaving(true);try{if(editMode&&editId){await updateDeposit(Number(editId),{provider_name:form.provider_name.trim(),product_name:form.product_name.trim(),product_type:form.product_type,income_bank_account_id:Number(form.income_bank_account_id||form.funding_bank_account_id),annual_return_rate:Number(form.annual_return_rate)||0,payout_frequency:form.payout_frequency,start_date:form.start_date,maturity_date:form.product_type==='TERM_DEPOSIT'?form.maturity_date:null,auto_renew:form.auto_renew});setMessage(t('Deposit details updated successfully.'))}else{const posted=await createDeposit({provider_name:form.provider_name.trim(),product_name:form.product_name.trim(),product_type:form.product_type,funding_bank_account_id:Number(form.funding_bank_account_id),income_bank_account_id:Number(form.income_bank_account_id||form.funding_bank_account_id),principal_amount:amount,annual_return_rate:Number(form.annual_return_rate)||0,payout_frequency:form.payout_frequency,start_date:form.start_date,maturity_date:form.product_type==='TERM_DEPOSIT'?form.maturity_date:null,auto_renew:form.auto_renew,currency_code:funding!.currency_code,transaction_date:new Date(form.transaction_date).toISOString()});await imported.confirm(postingReference(posted,'deposit'),'DEPOSIT',posted.id);setMessage(t('Deposit created and funded successfully.'))}await financial.refresh()}catch(error){setMessage(t(error instanceof Error?error.message:'Unable to save the deposit.'))}finally{setSaving(false)}}
  async function saveAdjustment(){if(!editId)return;const corrected=Number(adjustment.corrected_balance);const date=parseWealthDate(adjustment.adjustment_date);if(!Number.isFinite(corrected)||corrected<0){setMessage(t('Enter a valid corrected balance.'));return}if(!date||adjustment.reason.trim().length<3){setMessage(t('Enter a valid adjustment date and a brief reason.'));return}setSaving(true);setMessage('');try{const deposit=await adjustDepositBalance(Number(editId),{corrected_balance:corrected,adjustment_date:date.toISOString(),reason:adjustment.reason.trim()});set('principal_amount',String(deposit.current_balance));setMessage(t('Deposit balance adjusted and the accounting correction was posted.'));setAdjusting(false);setAdjustment({corrected_balance:String(deposit.current_balance),adjustment_date:formatWealthDate(new Date()),reason:''});await financial.refresh()}catch(error){setMessage(t(error instanceof Error?error.message:'Unable to adjust the deposit balance.'))}finally{setSaving(false)}}
  return <OperationForm title={t(editMode?'Edit Deposit':'Deposit Details')} onSubmit={event=>void submit(event)} preview={<><div className="standard-operation__preview"><span>{t(editMode?'Current Deposit Balance':form.product_type==='TERM_DEPOSIT'?'Term Deposit':'Income-Producing Savings')}</span><strong>{formatMoney(amount,currency)}</strong><small>{form.provider_name?(form.provider_name==='Wadaie'?t('Wadaie'):form.provider_name):t('Provider Not Selected')}</small></div><div className="income-operation__effects"><h4>{t(editMode?'Deposit Position':'Financial Impact')}</h4><p><span>{t('Estimated Return')}</span><strong>{formatMoney(estimatedReturn,currency)}</strong></p><p><span>{t('Maturity')}</span><strong>{form.maturity_date||t('Open Ended')}</strong></p><p><span>{t('Funding Account')}</span><strong>{funding?.account_name||t('Not Selected')}</strong></p></div>{!editMode&&<OperationPreflight requiredComplete={valid} balanced={valid} recorded={message===t('Deposit created and funded successfully.')}/>}</>}>
    <div className="standard-operation__grid deposit-operation__grid">
      <label><span>{t('Provider')}</span><input required value={form.provider_name} onChange={e=>set('provider_name',e.target.value)} placeholder={t('e.g. Dinar, Abyan Or A Bank')}/></label><label><span>{t('Product Name')}</span><input required value={form.product_name} onChange={e=>set('product_name',e.target.value)} placeholder={t('e.g. Monthly Income Deposit')}/></label><label><span>{t('Product Type')}</span><select value={form.product_type} onChange={e=>set('product_type',e.target.value)}><option value="TERM_DEPOSIT">{t('Term Deposit')}</option><option value="INCOME_SAVINGS">{t('Income-Producing Savings')}</option></select></label>
      <label><span>{t('Funding Account')}</span><select required disabled={editMode} value={form.funding_bank_account_id} onChange={e=>setForm(current=>({...current,funding_bank_account_id:e.target.value,income_bank_account_id:''}))}><option value="">{t('Select Bank Account')}</option>{banks.map(bank=><option value={bank.id} key={bank.id}>{bank.account_name} · {bank.bank_name} · {formatMoney(bank.current_balance,bank.currency_code as Currency)}</option>)}</select></label><label><span>{t('Deposit Amount')}</span><input required readOnly={editMode} type="text" inputMode="decimal" value={amountInput(form.principal_amount)} onChange={e=>set('principal_amount',amountValue(e.target.value))} placeholder="0.00"/></label><label><span>{t('Currency')}</span><input value={funding?.currency_code??t('Select Funding Account')} readOnly/></label>
      <label><span>{t('Annual Return %')}</span><input type="number" min="0" max="100" step="0.01" value={form.annual_return_rate} onChange={e=>set('annual_return_rate',e.target.value)} placeholder="0.00"/></label><label><span>{t('Payout Frequency')}</span><select value={form.payout_frequency} onChange={e=>set('payout_frequency',e.target.value)}><option value="MONTHLY">{t('Monthly')}</option><option value="QUARTERLY">{t('Quarterly')}</option><option value="AT_MATURITY">{t('At Maturity')}</option></select></label><label><span>{t('Income Destination')}</span><select value={form.income_bank_account_id} onChange={e=>set('income_bank_account_id',e.target.value)} disabled={!funding}><option value="">{t('Same As Funding Account')}</option>{compatibleBanks.map(bank=><option value={bank.id} key={bank.id}>{bank.account_name} · {bank.bank_name}</option>)}</select></label>
      <label><span>{t('Start Date')}</span><input required type="date" value={form.start_date} onChange={e=>set('start_date',e.target.value)}/></label><label><span>{t('Maturity Date')} {form.product_type==='INCOME_SAVINGS'?<em className="operation-field__optional">{t('Optional')}</em>:null}</span><input type="date" min={form.start_date} required={form.product_type==='TERM_DEPOSIT'} value={form.maturity_date} onChange={e=>set('maturity_date',e.target.value)} disabled={form.product_type==='INCOME_SAVINGS'}/></label>{!editMode?<label><span>{t('Funding Date')}</span><input required type="datetime-local" value={form.transaction_date} onChange={e=>set('transaction_date',e.target.value)}/></label>:<div className="deposit-operation__balance-tools"><button className="credit-card-operation__adjust" type="button" onClick={()=>{setAdjusting(value=>!value);setAdjustment(current=>({...current,corrected_balance:form.principal_amount}))}}>{t('Adjust Balance')}</button><FieldInfo/></div>}
      <button className={`deposit-operation__renew${form.auto_renew?' is-selected':''}`} type="button" role="checkbox" aria-checked={form.auto_renew} onClick={()=>set('auto_renew',!form.auto_renew)}><CalendarClock size={16}/><span><strong>{t('Auto Renew')}</strong><small>{t('Renew the principal at maturity')}</small></span><i>{form.auto_renew?'✓':''}</i></button><div className="deposit-operation__return"><Sprout size={17}/><span><small>{form.product_type==='TERM_DEPOSIT'?`${t('Estimated Return')} · ${depositDays} ${t('Days')}`:t('Estimated Annual Return')}</small><strong>{formatMoney(estimatedReturn,currency)}</strong></span></div>
    </div>
    {adjusting&&<section className="credit-card-operation__adjustment"><header><strong>{t('Balance Adjustment')}</strong><small>{t('Posts the difference to or from the original funding account.')}</small></header><div><label><span>{t('Corrected Balance')}</span><input type="text" inputMode="decimal" value={amountInput(adjustment.corrected_balance)} onChange={e=>setAdjustment(current=>({...current,corrected_balance:amountValue(e.target.value)}))}/></label><label><span>{t('Adjustment Date')}</span><input inputMode="numeric" maxLength={10} placeholder={t('DD/MM/YYYY')} value={adjustment.adjustment_date} onChange={e=>setAdjustment(current=>({...current,adjustment_date:normalizeWealthDateInput(e.target.value)}))}/></label><label><span>{t('Reason')}</span><input maxLength={240} placeholder={t('Why is this correction needed?')} value={adjustment.reason} onChange={e=>setAdjustment(current=>({...current,reason:e.target.value}))}/></label></div><footer><button type="button" onClick={()=>setAdjusting(false)}>{t('Cancel')}</button><button type="button" disabled={saving} onClick={()=>void saveAdjustment()}>{t(saving?'Posting…':'Post Adjustment')}</button></footer></section>}
    {!banks.length&&!financial.loading?<div className="deposit-operation__notice"><Landmark size={17}/>{t('Add a bank account before creating a deposit.')}</div>:null}<div className="income-operation__actions"><span>{message||t(editMode?'Balance changes remain protected and use posted accounting corrections.':'Funding moves from the selected bank account into a tracked deposit asset.')}</span><button type="submit" disabled={saving||!valid}>{t(saving?'Saving…':editMode?'Save Changes':'Add Deposit')}</button></div>
  </OperationForm>
}
