import { useState, type FormEvent } from 'react'
import OperationForm from './OperationForm'
import { recordInheritance, type InheritanceRequest, type PropertyIncomeType } from '../services/accountingService'
import { useFinancialSummary } from '../hooks/useFinancialSummary'
import { useCurrency, type Currency } from '../context/CurrencyContext'
import { useLanguage } from '../context/LanguageContext'

const displayAmount=(value:string)=>{const cleaned=value.replace(/[^\d.]/g,'');const[whole='',...decimal]=cleaned.split('.');const grouped=whole.replace(/\B(?=(\d{3})+(?!\d))/g,',');return cleaned.includes('.')?`${grouped}.${decimal.join('').slice(0,2)}`:grouped}
const cleanAmount=(value:string)=>value.replaceAll(',','').replace(/[^\d.]/g,'')

export default function InheritanceOperation(){
  const financial=useFinancialSummary();const{formatMoney}=useCurrency();const{t}=useLanguage()
  const[timing,setTiming]=useState<InheritanceRequest['timing']>('RECEIVED_AFTER_START');const[assetType,setAssetType]=useState<InheritanceRequest['asset_type']>('BANK_ACCOUNT');const[amount,setAmount]=useState('');const[date,setDate]=useState('');const[description,setDescription]=useState('');const[assetName,setAssetName]=useState('');const[bankId,setBankId]=useState('');const[propertyUsage,setPropertyUsage]=useState<NonNullable<InheritanceRequest['property_usage']>|''>('');const[incomeType,setIncomeType]=useState<PropertyIncomeType|''>('');const[saving,setSaving]=useState(false);const[message,setMessage]=useState('')
  const banks=financial.data?.bank_accounts??[]
  const valid=Boolean(Number(amount)>0&&date&&description.trim().length>=3&&(assetType!=='BANK_ACCOUNT'||bankId)&&(assetType==='CASH_ON_HAND'||assetType==='BANK_ACCOUNT'||assetName.trim())&&(assetType!=='PROPERTY'||(propertyUsage&&(propertyUsage!=='INVESTMENT_PROPERTY'||incomeType))))
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!valid)return;setSaving(true);setMessage('');try{await recordInheritance({timing,asset_type:assetType,amount:Number(amount),transaction_date:new Date(date).toISOString(),description:description.trim(),asset_name:assetName.trim()||null,bank_account_id:assetType==='BANK_ACCOUNT'?Number(bankId):null,property_usage:assetType==='PROPERTY'?propertyUsage as NonNullable<InheritanceRequest['property_usage']>:null,property_income_type:assetType==='PROPERTY'&&propertyUsage==='INVESTMENT_PROPERTY'?incomeType as PropertyIncomeType:null});setMessage(t('Inheritance recorded successfully.'));setAmount('');setDescription('');setAssetName('');await financial.refresh()}catch{setMessage(t('Unable to record the inheritance.'))}finally{setSaving(false)}}
  return <OperationForm title={t('Record Inheritance')} onSubmit={submit}>
    <div className="standard-operation__grid">
      <label><span>{t('When was the inheritance received?')}</span><select value={timing} onChange={event=>setTiming(event.target.value as typeof timing)}><option value="BEFORE_WEALTHOS">{t('Before using WealthOS')}</option><option value="RECEIVED_AFTER_START">{t('After starting WealthOS')}</option></select></label>
      <label><span>{t('Inherited Asset Type')}</span><select value={assetType} onChange={event=>{setAssetType(event.target.value as typeof assetType);setBankId('');setPropertyUsage('');setIncomeType('')}}><option value="CASH_ON_HAND">{t('Cash On Hand')}</option><option value="BANK_ACCOUNT">{t('Funds received in a bank account')}</option><option value="PROPERTY">{t('Property')}</option><option value="VEHICLE">{t('Vehicle')}</option><option value="INVESTMENT">{t('Investment or securities value')}</option><option value="OTHER_ASSET">{t('Other Asset')}</option></select></label>
      {assetType==='BANK_ACCOUNT'&&<label><span>{t('Receiving Bank Account')}</span><select value={bankId} onChange={event=>setBankId(event.target.value)}><option value="">{t('Select a bank account')}</option>{banks.map(bank=><option value={bank.id} key={bank.id}>{bank.account_name} · {bank.bank_name} · {formatMoney(bank.current_balance,bank.currency_code as Currency)}</option>)}</select></label>}
      {!['CASH_ON_HAND','BANK_ACCOUNT'].includes(assetType)&&<label><span>{t('Asset Name')}</span><input value={assetName} onChange={event=>setAssetName(event.target.value)} placeholder={t('Asset name or identifying reference')}/></label>}
      {assetType==='PROPERTY'&&<label><span>{t('Property Usage')}</span><select value={propertyUsage} onChange={event=>{const usage=event.target.value as typeof propertyUsage;setPropertyUsage(usage);if(usage!=='INVESTMENT_PROPERTY')setIncomeType('')}}><option value="">{t('Select Property Usage')}</option><option value="PRIMARY_RESIDENCE">{t('Primary Residence')}</option><option value="INVESTMENT_PROPERTY">{t('Investment Property')}</option><option value="VACATION_HOME">{t('Vacation Home')}</option><option value="OTHER">{t('Other')}</option></select></label>}
      {assetType==='PROPERTY'&&propertyUsage==='INVESTMENT_PROPERTY'&&<label><span>{t('Property Income Type')}</span><select value={incomeType} onChange={event=>setIncomeType(event.target.value as PropertyIncomeType)}><option value="">{t('Select Income Type')}</option><option value="RESIDENTIAL_RENT">{t('Residential Rent')}</option><option value="COMMERCIAL_RENT">{t('Commercial Rent')}</option><option value="SHORT_TERM_RENT">{t('Short-term Rent')}</option></select></label>}
      <label><span>{t('Fair Value at Recognition')}</span><input inputMode="decimal" value={displayAmount(amount)} onChange={event=>setAmount(cleanAmount(event.target.value))} placeholder="0.00"/></label>
      <label><span>{t(timing==='BEFORE_WEALTHOS'?'Opening Balance Date':'Receipt Date')}</span><input type="datetime-local" value={date} onChange={event=>setDate(event.target.value)}/></label>
      <label><span>{t('Description / Estate Reference')}</span><input value={description} onChange={event=>setDescription(event.target.value)} placeholder={t('Add a clear supporting reference')} maxLength={255}/></label>
    </div>
    <div className="income-operation__smart-note"><p><strong>{t(timing==='BEFORE_WEALTHOS'?'Opening Wealth — Not Current Income':'Inherited Wealth — Non-operating')}</strong>{t(timing==='BEFORE_WEALTHOS'?'The asset is added against opening balance equity and does not affect current-period income or cash flow.':'The received asset increases wealth through inherited wealth equity and is not salary, recurring income, or operating revenue.')}</p></div>
    <div className="income-operation__actions"><span>{message||(financial.error?t('Unable to load financial data.'): '')}</span><button type="submit" disabled={!valid||saving||financial.loading}>{t(saving?'Recording…':'Record Inheritance')}</button></div>
  </OperationForm>
}
