import { useEffect, useMemo, useState, type FormEvent } from 'react'
import OperationForm from './OperationForm'
import { createLoan, getBankAccounts, type BankAccount } from '../services/accountingService'
import { useLanguage } from '../context/LanguageContext'
import { formatDisplayNumber, formatDisplayPercent } from '../utils/localeFormat'
import { useCurrency } from '../context/CurrencyContext'

export default function LoanOperation(){
  const {t,language}=useLanguage()
  const {formatMoney}=useCurrency()
  const[name,setName]=useState('');const[lender,setLender]=useState('');const[type,setType]=useState('LONG_TERM');const[principal,setPrincipal]=useState('');const[received,setReceived]=useState('');const[fees,setFees]=useState('0');const[rate,setRate]=useState('');const[term,setTerm]=useState('');const[payment,setPayment]=useState('');const[firstDate,setFirstDate]=useState('');const[status,setStatus]=useState('');const[saving,setSaving]=useState(false);const[bankAccounts,setBankAccounts]=useState<BankAccount[]>([]);const[bankAccountId,setBankAccountId]=useState('')
  useEffect(()=>{getBankAccounts().then(items=>{setBankAccounts(items);const primary=items.find(item=>item.is_primary)??items[0];if(primary)setBankAccountId(String(primary.id))}).catch(()=>setBankAccounts([]))},[])
  const balanced=useMemo(()=>Number(received||0)+Number(fees||0)===Number(principal||0),[received,fees,principal])
  const complete=Boolean(name.trim()&&lender.trim()&&bankAccountId&&Number(principal)>0&&Number(received)>0&&Number(term)>0&&Number(payment)>0&&firstDate)
  const ready=complete&&balanced
  const totalRepayment=Number(payment||0)*Number(term||0)
  const financingCost=Math.max(0,totalRepayment-Number(principal||0))
  const loanTypeLabel=t({SHORT_TERM:'Short-term loan',LONG_TERM:'Long-term loan',MORTGAGE:'Mortgage'}[type]??type)
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus('');const form=event.currentTarget;if(!form.checkValidity()){form.reportValidity();setStatus(t('Complete all required fields before creating the loan.'));return}if(!balanced){setStatus(t('The amount received plus fees must equal the loan principal.'));return}setSaving(true);try{await createLoan({name,lender,loan_type:type,principal_amount:Number(principal),amount_received:Number(received),fees:Number(fees),annual_rate:Number(rate||0),term_months:Number(term),monthly_payment:Number(payment),first_payment_date:firstDate,destination_account_code:1120,destination_bank_account_id:Number(bankAccountId)});setStatus(t('Loan created and posted to the General Ledger.'))}catch(error){setStatus(error instanceof Error?error.message:t('Unable to create the loan.'))}finally{setSaving(false)}}
  const preview=<><div className={`standard-operation__preview loan-preview ${ready?'is-ready':'is-pending'}`}><span>{loanTypeLabel}</span><strong>{t(ready?'Ready for review':'Needs attention')}</strong><small>{name||t('Enter loan details to build the preview.')}</small>{lender&&<small>{lender}</small>}</div><div className="income-operation__effects"><h4>{t('Financing Summary')}</h4><p><span>{t('Principal Amount')}</span><strong>{formatMoney(Number(principal||0),'SAR')}</strong></p><p><span>{t('Net Amount Received')}</span><strong>{formatMoney(Number(received||0),'SAR')}</strong></p><p><span>{t('Upfront Fees')}</span><strong>{formatMoney(Number(fees||0),'SAR')}</strong></p><p><span>{t('Monthly Payment')}</span><strong>{formatMoney(Number(payment||0),'SAR')}</strong></p><p><span>{t('Expected Total Repayment')}</span><strong>{formatMoney(totalRepayment,'SAR')}</strong></p><p><span>{t('Expected Financing Cost')}</span><strong>{formatMoney(financingCost,'SAR')}</strong></p></div><div className={`income-operation__smart-note loan-preview__check ${balanced?'is-balanced':'is-unbalanced'}`}><p><strong>{t(balanced?'Balanced accounting entry':'Amounts are not balanced')}</strong>{t(balanced?'Bank financing plus fees equals the loan liability.':'The amount received plus fees must equal the loan principal.')}</p></div><div className="income-operation__effects"><p><span>{t('Liability Account')}</span><strong>{loanTypeLabel}</strong></p><p><span>{t('First Payment')}</span><strong>{firstDate||t('Not set')}</strong></p><p><span>{t('Annual Rate')}</span><strong>{formatDisplayPercent(Number(rate||0),2,language)}</strong></p></div></>
  return <OperationForm title={t('New Loan')} preview={preview} onSubmit={submit}><div className="standard-operation__grid">
    <label><span>{t('Loan Name')}</span><input required value={name} onChange={e=>setName(e.target.value)} placeholder={t('Home financing')}/></label>
    <label><span>{t('Lender')}</span><input required value={lender} onChange={e=>setLender(e.target.value)} placeholder={t('Bank or finance company')}/></label>
    <label><span>{t('Loan Type')}</span><select value={type} onChange={e=>setType(e.target.value)}><option value="SHORT_TERM">{t('Short-term loan')}</option><option value="LONG_TERM">{t('Long-term loan')}</option><option value="MORTGAGE">{t('Mortgage')}</option></select></label>
    <label><span>{t('Loan Principal')}</span><input required min="0.01" step="0.01" type="number" value={principal} onChange={e=>{setPrincipal(e.target.value);if(!received||Number(received)===Number(principal))setReceived(e.target.value)}}/></label>
    <label><span>{t('Amount Received')}</span><input required min="0.01" step="0.01" type="number" value={received} onChange={e=>setReceived(e.target.value)}/></label>
    <label><span>{t('Receiving Bank Account')}</span><select required value={bankAccountId} onChange={e=>setBankAccountId(e.target.value)}><option value="">{t('Select a bank account')}</option>{bankAccounts.map(account=><option value={account.id} key={account.id}>{account.account_name} · {account.currency_code} {formatDisplayNumber(Number(account.current_balance),{minimumFractionDigits:2},language)}</option>)}</select></label>
    <label><span>{t('Upfront Fees')}</span><input min="0" step="0.01" type="number" value={fees} onChange={e=>setFees(e.target.value)}/></label>
    <label><span>{t('Annual Rate %')}</span><input min="0" max="100" step="0.01" type="number" value={rate} onChange={e=>setRate(e.target.value)}/></label>
    <label><span>{t('Term in Months')}</span><input required min="1" max="600" type="number" value={term} onChange={e=>setTerm(e.target.value)}/></label>
    <label><span>{t('Monthly Payment')}</span><input required min="0.01" step="0.01" type="number" value={payment} onChange={e=>setPayment(e.target.value)}/></label>
    <label><span>{t('First Payment Date')}</span><input required type="date" value={firstDate} onChange={e=>setFirstDate(e.target.value)}/></label>
  </div><div className="income-operation__actions"><span className={status===t('Loan created and posted to the General Ledger.')?'is-success':status?'is-error':''}>{status||t('Financing is posted to the primary bank account and the liability is created automatically.')}</span><button disabled={saving} type="submit">{t(saving?'Creating…':'Review & Create Loan')}</button></div></OperationForm>
}
