import { useEffect, useState, type FormEvent } from 'react'
import OperationForm from './OperationForm'
import { addOpeningCash, adjustOpeningCash, getOpeningCashStatus } from '../services/accountingService'
import { useFinancialSummary } from '../hooks/useFinancialSummary'
import { useCurrency } from '../context/CurrencyContext'
import { useLanguage } from '../context/LanguageContext'

const amountInput=(value:string)=>{const cleaned=value.replace(/[^\d.]/g,'');const[whole='',...decimal]=cleaned.split('.');const grouped=whole.replace(/\B(?=(\d{3})+(?!\d))/g,',');return cleaned.includes('.')?`${grouped}.${decimal.join('').slice(0,2)}`:grouped}
const amountValue=(value:string)=>value.replace(/,/g,'').replace(/[^\d.]/g,'')

export default function OpeningCashOperation(){
  const financial=useFinancialSummary();const{formatMoney}=useCurrency();const{t}=useLanguage();const[initialized,setInitialized]=useState(false);const[loadingStatus,setLoadingStatus]=useState(true);const[amount,setAmount]=useState('');const[date,setDate]=useState('');const[description,setDescription]=useState('Cash owned before WealthOS');const[message,setMessage]=useState('');const currentCash=financial.data?.asset_breakdown.find(item=>item.code===1110)?.balance??0
  useEffect(()=>{getOpeningCashStatus().then(status=>{setInitialized(status.initialized);if(status.initialized)setAmount(String(status.current_balance))}).catch(reason=>setMessage(t(reason instanceof Error?reason.message:'Unable to load Cash On Hand.'))).finally(()=>setLoadingStatus(false))},[t])
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage('');try{if(initialized){await adjustOpeningCash({corrected_balance:Number(amount),transaction_date:date,reason:description.trim()});setMessage(t('Cash On Hand balance adjusted successfully.'))}else{await addOpeningCash({amount:Number(amount),transaction_date:date,description:description.trim()||'Opening Cash On Hand'});setInitialized(true);setMessage(t('Cash On Hand opening asset created successfully.'))}await financial.refresh()}catch(reason){setMessage(t(reason instanceof Error?reason.message:'Unable to save the Cash On Hand asset.'))}}
  return <OperationForm title="Cash On Hand Asset" onSubmit={submit}><div className="standard-operation__grid"><label><span>{t('Current Cash On Hand')}</span><input readOnly value={formatMoney(currentCash,'SAR')}/></label><label><span>{t(initialized?'Corrected Balance':'Opening Cash Balance')}</span><input inputMode="decimal" value={amountInput(amount)} onChange={event=>setAmount(amountValue(event.target.value))} placeholder="0.00"/></label><label><span>{t(initialized?'Adjustment Date':'Balance Date')}</span><input type="datetime-local" value={date} onChange={event=>setDate(event.target.value)}/></label><label><span>{t(initialized?'Correction Reason':'Opening Balance Description')}</span><input value={description} onChange={event=>setDescription(event.target.value)} maxLength={255}/></label></div><div className="income-operation__smart-note"><p><strong>{t(initialized?'Protected Balance Correction':'Opening Asset — Not Income')}</strong>{t(initialized?'Use this only to correct the recorded Cash On Hand balance. The reason and accounting entry remain in the audit trail.':'Record only cash already owned before starting WealthOS. Future cash must come from a real operation such as a withdrawal, income, or asset sale.')}</p></div><div className="income-operation__actions"><span>{message||(financial.error?t(financial.error):'')}</span><button type="submit" disabled={financial.loading||loadingStatus||!amount||!date||!description.trim()}>{t(initialized?'Post Cash Correction':'Create Cash Asset')}</button></div></OperationForm>
}
