import { ArrowDownLeft, ArrowUpRight, CalendarRange, ChartNoAxesCombined, Landmark, RefreshCcw, Scale, WalletCards } from 'lucide-react'
import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import PageHeader from '../components/ui/PageHeader'
import { useCurrency } from '../context/CurrencyContext'
import './AccountingPage.css'
import './AccountingTabs.css'
import AccountingSummaryView from './AccountingSummaryView'
import LoansView from './LoansView'
import { useFinancialSummary } from '../hooks/useFinancialSummary'
import FormattedMoney from '../components/ui/FormattedMoney'
import { useLanguage } from '../context/LanguageContext'
import { displayLocale, formatDisplayPercent } from '../utils/localeFormat'

export default function AccountingPage(){const[searchParams]=useSearchParams();const requestedTab=searchParams.get('tab');const initialTab=requestedTab==='loans'?'loans':'cashflow';const[tab,setTab]=useState<'cashflow'|'position'|'income'|'reconciliation'|'loans'>(initialTab);const currency=useCurrency();const{t,language}=useLanguage();const formatMoney=(value:number)=><FormattedMoney value={currency.formatMoney(value)}/>;const financial=useFinancialSummary();const monthLabel=new Intl.DateTimeFormat(displayLocale(language),{month:'long',year:'numeric'}).format(new Date());const comparisonReport=tab==='position'?'balance_sheet':'cash_flow_statement';return <section className="accounting-page">
  <PageHeader title={t('Accounting')} subtitle={t('Understand your cash movement and consolidated financial position.')} icon={WalletCards}/>
  <nav className="accounting-page__tabs" aria-label={t('Accounting views')}><button className={tab==='cashflow'?'is-active':''} onClick={()=>setTab('cashflow')}><ArrowUpRight size={16}/>{t('Cash Flow')}</button><button className={tab==='position'?'is-active':''} onClick={()=>setTab('position')}><Scale size={16}/>{t('Balance Sheet')}</button><button className={tab==='income'?'is-active':''} onClick={()=>setTab('income')}><ChartNoAxesCombined size={16}/>{t('Income Statement')}</button><button className={tab==='loans'?'is-active':''} onClick={()=>setTab('loans')}><Landmark size={16}/>{t('Liabilities & Loans')}</button><button className={tab==='reconciliation'?'is-active':''} onClick={()=>setTab('reconciliation')}><RefreshCcw size={16}/>{t('Reconciliation')}</button></nav>
  {(tab==='cashflow'||tab==='position')&&<div className="accounting-page__period-bar"><div><CalendarRange size={16}/><span>{t('Displayed period')}</span><strong>{monthLabel}</strong><small>{t('Current live period')}</small></div><nav><Link to={`/reporting?report=${comparisonReport}&view=periodic`}>{t('Compare months, quarters, and years')} ←</Link><Link to="/accounting/month-close">{t('Monthly Snapshots')} ←</Link></nav></div>}

  {tab==='cashflow'?<div className="accounting-view">
    <div className="accounting-view__metrics"><article><span>{t('Cash Inflow')}</span><strong>{financial.data?formatMoney(financial.data.cash_inflow):t('Loading…')}</strong><small>{monthLabel} · {t('Posted')}</small></article><article><span>{t('Cash Outflow')}</span><strong>{financial.data?formatMoney(financial.data.cash_outflow):t('Loading…')}</strong><small>{monthLabel} · {t('Posted')}</small></article><article><span>{t('Net Cash Flow')}</span><strong>{financial.data?formatMoney(financial.data.net_cash_flow):t('Loading…')}</strong><small>{financial.data?t(financial.data.net_cash_flow>=0?'Positive':'Negative'):t('Posted operations')}</small></article></div>
    <div className="accounting-view__layout"><section className="accounting-panel"><header><div><h2>{t('Cash Flow Movement')}</h2><p>{t('Confirmed movements from posted operations')}</p></div><span>{monthLabel}</span></header><div className="accounting-table"><div><span><i className="is-in"><ArrowDownLeft size={14}/></i>{t('External cash inflow')}</span><strong>{financial.data?formatMoney(financial.data.cash_inflow):'—'}</strong><em>{t('In')}</em></div><div><span><i className="is-out"><ArrowUpRight size={14}/></i>{t('External cash outflow')}</span><strong>{financial.data?formatMoney(financial.data.cash_outflow):'—'}</strong><em>{t('Out')}</em></div><div><span><i className={financial.data&&financial.data.net_cash_flow>=0?'is-in':'is-out'}>{financial.data&&financial.data.net_cash_flow>=0?<ArrowDownLeft size={14}/>:<ArrowUpRight size={14}/>}</i>{t('Net Cash Movement')}</span><strong>{financial.data?formatMoney(financial.data.net_cash_flow):'—'}</strong><em>{t('Net')}</em></div></div></section><aside className="accounting-panel"><h2>{t('Income & Expenses')}</h2><div className="accounting-balance-list"><div><span>{t('Recognized Income')}</span><strong>{financial.data?formatMoney(financial.data.monthly_income):'—'}</strong></div><div><span>{t('Recognized Expenses')}</span><strong>{financial.data?formatMoney(financial.data.monthly_expenses):'—'}</strong></div><div><span>{t('Scheduled Debt Payments')}</span><strong>{financial.data?formatMoney(financial.data.monthly_debt_payments):'—'}</strong></div></div></aside></div>
  </div>:tab==='position'?<div className="accounting-view">
    <div className="accounting-view__metrics"><article><span>{t('Total Assets')}</span><strong>{financial.data?formatMoney(financial.data.total_assets):t('Loading…')}</strong><small>{t('From posted operations')}</small></article><article><span>{t('Total Liabilities')}</span><strong>{financial.data?formatMoney(financial.data.total_liabilities):t('Loading…')}</strong><small>{financial.data&&financial.data.total_assets>0?`${formatDisplayPercent((financial.data.total_liabilities/financial.data.total_assets)*100,1,language)} ${t('of assets')}`:t('From posted operations')}</small></article><article><span>{t('Net Worth')}</span><strong>{financial.data?formatMoney(financial.data.net_worth):t('Loading…')}</strong><small>{t('Assets minus liabilities')}</small></article></div>
    <div className="accounting-view__layout"><section className="accounting-panel"><header><div><h2>{t('Assets')}</h2><p>{t('Posted debit balances and reclassified items')}</p></div><Landmark size={17}/></header><div className="accounting-balance-list">{financial.data?.asset_breakdown.map(item=><div key={`${item.code}-${item.name}`}><span>{item.code} · {t(item.name)}</span><strong>{formatMoney(item.balance)}</strong></div>)}{financial.data&&!financial.data.asset_breakdown.length&&<div><span>{t('No posted assets')}</span><strong>{formatMoney(0)}</strong></div>}</div><div className="accounting-total"><span>{t('Total Assets')}</span><strong>{financial.data?formatMoney(financial.data.total_assets):'—'}</strong></div></section><aside className="accounting-panel"><header><div><h2>{t('Liabilities & Net Worth')}</h2><p>{t("Liabilities plus the owner's net position")}</p></div><Scale size={17}/></header><div className="accounting-balance-list">{financial.data?.liability_breakdown.map(item=><div key={`${item.code}-${item.name}`}><span>{item.code} · {t(item.name)}</span><strong>{formatMoney(item.balance)}</strong></div>)}{financial.data&&!financial.data.liability_breakdown.length&&<div><span>{t('No posted liabilities')}</span><strong>{formatMoney(0)}</strong></div>}<div><span>{t('Net Worth')}</span><strong>{financial.data?formatMoney(financial.data.net_worth):'—'}</strong></div></div><div className="accounting-total"><span>{t('Liabilities + Net Worth')}</span><strong>{financial.data?formatMoney(financial.data.total_liabilities+financial.data.net_worth):'—'}</strong></div></aside></div>
  </div>:tab==='loans'?<LoansView/>:<AccountingSummaryView type={tab} formatMoney={formatMoney}/>}
</section>}
