import { BookOpen, CheckCircle2, Download, FileText, RefreshCcw } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import PageHeader from '../components/ui/PageHeader'
import { useCurrency } from '../context/CurrencyContext'
import { useLanguage } from '../context/LanguageContext'
import { getJournalEntries, type JournalEntry } from '../services/accountingService'
import './AccountingToolPage.css'
import { formatDate } from '../utils/dateFormat'
import FormattedMoney from '../components/ui/FormattedMoney'

type Tool='ledger'|'journals'|'reconciliation'
const details={ledger:{title:'General Ledger',subtitle:'Search and review every posted debit and credit movement.',icon:BookOpen},journals:{title:'Journal Entries',subtitle:'Review balanced entries generated by actual operations.',icon:FileText},reconciliation:{title:'Reconciliation',subtitle:'Match account and card transactions with WealthOS records.',icon:RefreshCcw}}
const dateLabel=(value:string)=>formatDate(value)
const reference=(id:number)=>`JE-${String(id).padStart(4,'0')}`

export default function AccountingToolPage({tool}:{tool:Tool}){
  const config=details[tool];const Icon=config.icon;const{formatMoney}=useCurrency();const{t}=useLanguage()
  const[entries,setEntries]=useState<JournalEntry[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[query,setQuery]=useState('');const[thisMonth,setThisMonth]=useState(false);const[account,setAccount]=useState('ALL')
  useEffect(()=>{let active=true;getJournalEntries().then(value=>{if(active)setEntries(value)}).catch(()=>{if(active)setError(t('Unable to load posted journal entries.'))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[t])
  const accounts=useMemo(()=>[...new Set(entries.flatMap(entry=>entry.lines.map(line=>`${line.account_code}|${line.account_name}`)))].sort(),[entries])
  const filtered=useMemo(()=>entries.filter(entry=>{const needle=query.trim().toLowerCase();const matchesSearch=!needle||`${reference(entry.id)} ${entry.description} ${entry.related_reference??''} ${entry.lines.map(line=>`${line.account_code} ${line.account_name}`).join(' ')}`.toLowerCase().includes(needle);const date=new Date(entry.transaction_date);const now=new Date();const matchesMonth=!thisMonth||(date.getFullYear()===now.getFullYear()&&date.getMonth()===now.getMonth());const matchesAccount=account==='ALL'||entry.lines.some(line=>String(line.account_code)===account);return matchesSearch&&matchesMonth&&matchesAccount}),[entries,query,thisMonth,account])
  const ledgerRows=filtered.flatMap(entry=>entry.lines.filter(line=>account==='ALL'||String(line.account_code)===account).map(line=>({entry,line})))
  function exportCsv(){const rows=tool==='ledger'?ledgerRows.map(({entry,line})=>[dateLabel(entry.transaction_date),reference(entry.id),entry.description,line.account_code,t(line.account_name),line.debit,line.credit,entry.related_reference??'']):filtered.map(entry=>[dateLabel(entry.transaction_date),reference(entry.id),entry.description,entry.lines.reduce((sum,line)=>sum+Number(line.debit),0),entry.related_reference??'']);const header=tool==='ledger'?[t('Date'),t('Reference'),t('Description'),t('Account code'),t('Account'),t('Debit'),t('Credit'),t('Related reference')]:[t('Date'),t('Reference'),t('Description'),t('Total'),t('Related reference')];const csv=[header,...rows].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\uFEFF',csv],{type:'text/csv;charset=utf-8'}));link.download=`wealthos-${tool}.csv`;link.click();URL.revokeObjectURL(link.href)}
  const isEmpty=tool==='reconciliation'||(tool==='ledger'&&!ledgerRows.length)||(tool==='journals'&&!filtered.length)
  return <section className="accounting-tool"><PageHeader className="accounting-tool__header" title={t(config.title)} subtitle={t(config.subtitle)} icon={Icon}/>
    <div className="accounting-tool__toolbar"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={`${t('Search in')} ${t(config.title)}...`}/><button className={thisMonth?'is-active':''} type="button" onClick={()=>setThisMonth(value=>!value)}>{t(thisMonth?'This month':'All dates')}</button><select value={account} onChange={event=>setAccount(event.target.value)}><option value="ALL">{t('All accounts')}</option>{accounts.map(item=>{const[code,name]=item.split('|');return <option value={code} key={item}>{code} · {t(name)}</option>})}</select><button type="button" onClick={exportCsv} disabled={tool==='reconciliation'||!filtered.length}><Download size={13}/>{t('Export')}</button></div>
    <section className="accounting-tool__panel"><div className="accounting-tool__head"><span>{t('Date')}</span><span>{t('Reference')}</span><span>{t('Description')}</span><span>{t('Status')}</span><span>{t('Amount')}</span></div>
      {loading?<div className="accounting-tool__empty">{t('Loading posted records…')}</div>:error?<div className="accounting-tool__empty is-error">{error}</div>:tool==='ledger'?ledgerRows.map(({entry,line})=><div key={`${entry.id}-${line.id}`}><span>{dateLabel(entry.transaction_date)}</span><span>{reference(entry.id)}</span><span><b>{line.account_code} · {t(line.account_name)}</b><small>{entry.description}</small></span><em className={Number(line.debit)>0?'is-debit':'is-credit'}>{t(Number(line.debit)>0?'Debit':'Credit')}</em><strong><FormattedMoney value={formatMoney(Number(line.debit)||Number(line.credit))}/></strong></div>):tool==='journals'?filtered.map(entry=>{const debit=entry.lines.reduce((sum,line)=>sum+Number(line.debit),0);const credit=entry.lines.reduce((sum,line)=>sum+Number(line.credit),0);return <div key={entry.id}><span>{dateLabel(entry.transaction_date)}</span><span>{reference(entry.id)}</span><span><b>{entry.description}</b><small>{entry.related_reference??t('Posted operation')}</small></span><em><CheckCircle2 size={13}/>{t(Math.abs(debit-credit)<.01?'Balanced':'Review')}</em><strong><FormattedMoney value={formatMoney(debit)}/></strong></div>}):null}
      {!loading&&!error&&isEmpty?<div className="accounting-tool__empty">{t(tool==='reconciliation'?'No reconciliation items yet.':'No posted records match the filters.')}</div>:null}
    </section>
  </section>
}
