import { useState } from 'react'
import { Building2, ChartNoAxesCombined, ChevronDown, Pencil, Plus, Trash2, TriangleAlert, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import PageHeader from '../components/ui/PageHeader'
import { useBrokers } from '../hooks/useBrokers'
import { usePortfolios } from '../hooks/usePortfolios'
import { createPortfolio, removePortfolio, updatePortfolio, type PortfolioLookup } from '../services/portfolioService'
import { closeBroker, updateBrokerCommission, type BrokerLookup } from '../services/brokerService'
import { useCurrency } from '../context/CurrencyContext'
import './BrokersPage.css'
import './InvestingSubpages.css'
import './BrokersPageEnhancements.css'
import { useLanguage } from '../context/LanguageContext'
import { formatDisplayInteger } from '../utils/localeFormat'

export default function BrokersPage(){
  const[searchParams]=useSearchParams()
  const requestedBroker=Number(searchParams.get('addPortfolio'))||null
  const{brokers,loading,error}=useBrokers(),{portfolios,refresh:refreshPortfolios}=usePortfolios()
  const{enabledCurrencies,baseCurrency}=useCurrency()
  const{t,language}=useLanguage()
  const[openBroker,setOpenBroker]=useState<number|null>(requestedBroker),[name,setName]=useState(''),[portfolioNumber,setPortfolioNumber]=useState(''),[iban,setIban]=useState(''),[portfolioCurrency,setPortfolioCurrency]=useState(baseCurrency),[creating,setCreating]=useState(false),[message,setMessage]=useState(searchParams.get('created')==='1'?t('Broker added successfully. Create its first portfolio below.'):'')
  const[collapsedBrokers,setCollapsedBrokers]=useState<Set<number>>(()=>new Set())
  const[brokerToRemove,setBrokerToRemove]=useState<BrokerLookup|null>(null),[removing,setRemoving]=useState(false)
  const[brokerToEdit,setBrokerToEdit]=useState<BrokerLookup|null>(null),[editWebsite,setEditWebsite]=useState(''),[editRate,setEditRate]=useState(''),[editTax,setEditTax]=useState(''),[editDividendTax,setEditDividendTax]=useState(''),[savingEdit,setSavingEdit]=useState(false)
  const[portfolioToEdit,setPortfolioToEdit]=useState<PortfolioLookup|null>(null),[portfolioEditName,setPortfolioEditName]=useState(''),[portfolioEditNumber,setPortfolioEditNumber]=useState(''),[portfolioEditIban,setPortfolioEditIban]=useState(''),[portfolioEditCurrency,setPortfolioEditCurrency]=useState(baseCurrency),[savingPortfolio,setSavingPortfolio]=useState(false)
  const[portfolioToRemove,setPortfolioToRemove]=useState<PortfolioLookup|null>(null),[removingPortfolio,setRemovingPortfolio]=useState(false)
  async function addPortfolio(brokerId:number){if(name.trim().length<2||portfolioNumber.trim().length<2||creating)return;setCreating(true);setMessage('');try{await createPortfolio({name:name.trim(),broker_id:brokerId,portfolio_number:portfolioNumber.replace(/\s/g,''),iban:iban.replace(/\s/g,'')||undefined,currency_code:portfolioCurrency});await refreshPortfolios();setName('');setPortfolioNumber('');setIban('');setOpenBroker(null);setMessage(t('Portfolio created successfully.'))}catch(error){setMessage(t(error instanceof Error?error.message:'Unable to create portfolio.'))}finally{setCreating(false)}}
  async function removeBroker(){if(!brokerToRemove||removing)return;setRemoving(true);try{await closeBroker(brokerToRemove.id);setBrokerToRemove(null);window.location.reload()}catch(error){setMessage(t(error instanceof Error?error.message:'Unable to remove broker.'));setRemoving(false)}}
  function openBrokerEdit(broker:BrokerLookup){setBrokerToEdit(broker);setEditWebsite(broker.website??'');setEditRate(String(broker.commission_rate??''));setEditTax(String(broker.commission_tax_rate??''));setEditDividendTax(broker.dividend_withholding_tax_rate==null?'':String(broker.dividend_withholding_tax_rate))}
  async function saveBrokerEdit(){if(!brokerToEdit||editRate===''||editTax===''||savingEdit)return;setSavingEdit(true);try{await updateBrokerCommission(brokerToEdit.id,Number(editRate),Number(editTax),editDividendTax===''?null:Number(editDividendTax),editWebsite);setBrokerToEdit(null);window.location.reload()}catch(error){setMessage(t(error instanceof Error?error.message:'Unable to update broker details.'));setSavingEdit(false)}}
  function openPortfolioEdit(portfolio:PortfolioLookup){setPortfolioToEdit(portfolio);setPortfolioEditName(portfolio.name);setPortfolioEditNumber('');setPortfolioEditIban('');setPortfolioEditCurrency(portfolio.base_currency_code as typeof baseCurrency)}
  async function savePortfolio(){if(!portfolioToEdit||portfolioEditName.trim().length<2||savingPortfolio)return;setSavingPortfolio(true);try{await updatePortfolio(portfolioToEdit.id,{name:portfolioEditName.trim(),portfolio_number:portfolioEditNumber.trim()||undefined,iban:portfolioEditIban.trim()||undefined,currency_code:portfolioEditCurrency});setPortfolioToEdit(null);await refreshPortfolios();setMessage(t('Portfolio updated successfully.'))}catch(error){setMessage(t(error instanceof Error?error.message:'Unable to update portfolio.'))}finally{setSavingPortfolio(false)}}
  async function confirmRemovePortfolio(){if(!portfolioToRemove||removingPortfolio)return;setRemovingPortfolio(true);try{await removePortfolio(portfolioToRemove.id);setPortfolioToRemove(null);await refreshPortfolios();setMessage(t('Portfolio removed successfully.'))}catch(error){setMessage(t(error instanceof Error?error.message:'Unable to remove portfolio.'))}finally{setRemovingPortfolio(false)}}
  const orderedBrokers=[...brokers].sort((left,right)=>left.institution_name.localeCompare(right.institution_name)||left.name.localeCompare(right.name))
  return<section className="brokers-page">
    <PageHeader eyebrow={t('Portfolio Management')} title={t('Brokers')} subtitle={t('Manage brokers and the portfolios held with each provider.')} icon={Building2} actions={<Link className="page-header__primary-action" to="/operations/add-broker"><Plus size={15}/> {t('Add Broker')}</Link>}/>
    <section className="brokers-page__panel"><div className="brokers-page__panel-title"><div><h2>{t('Registered Brokers')}</h2><p>{formatDisplayInteger(brokers.length,language)} {t(brokers.length===1?'active broker':'active brokers')} · {formatDisplayInteger(portfolios.length,language)} {t(portfolios.length===1?'portfolio':'portfolios')}</p></div></div>
      {message&&<p className="brokers-page__message">{message}</p>}
      {loading?<p>{t('Loading brokers...')}</p>:error?<p className="brokers-page__error">{t(error)}</p>:!brokers.length?<div className="brokers-page__empty"><Building2 size={22}/><strong>{t('No Brokers Registered')}</strong><span>{t('Add a broker before creating an investment portfolio.')}</span></div>:<div className="brokers-page__list">{orderedBrokers.map((broker,index)=>{const items=portfolios.filter(portfolio=>portfolio.broker_id===broker.id),startsInstitution=index===0||orderedBrokers[index-1].institution_name!==broker.institution_name;return<div className="broker-institution__service" key={broker.id}>{startsInstitution?<div className="broker-institution__heading"><Building2 size={15}/><div><strong>{broker.institution_name}</strong><small>{t('Financial Institution')}</small></div></div>:null}<article className="broker-card">
        <div className="broker-card__header"><span><Building2 size={17}/></span><div className="broker-card__identity"><div><strong>{broker.name}</strong><small>{broker.country||t('Country not specified')} · {items.length} {t(items.length===1?'portfolio':'portfolios')}{broker.execution_partner?` · ${t('Via')} ${broker.execution_partner}`:''}</small></div>{items.length>0?<button className={collapsedBrokers.has(broker.id)?'is-collapsed':''} type="button" aria-label={`${t(collapsedBrokers.has(broker.id)?'Expand':'Collapse')} ${broker.name} ${t('portfolios')}`} onClick={()=>setCollapsedBrokers(current=>{const next=new Set(current);if(next.has(broker.id))next.delete(broker.id);else next.add(broker.id);return next})}><ChevronDown size={14}/></button>:null}</div><div className="broker-card__actions">{broker.website?<a href={broker.website} target="_blank" rel="noreferrer">{t('Website')}</a>:null}<button className={openBroker===broker.id?'is-open':''} type="button" onClick={()=>{setOpenBroker(openBroker===broker.id?null:broker.id);setName('');setPortfolioNumber('');setIban('');setMessage('')}}><span><Plus size={13}/></span> {t('Add Portfolio')}</button><button className="broker-card__edit" type="button" aria-label={`${t('Edit')} ${broker.name}`} onClick={()=>openBrokerEdit(broker)}><Pencil size={14}/></button><button className="broker-card__remove" type="button" aria-label={`${t('Remove')} ${broker.name}`} onClick={()=>setBrokerToRemove(broker)}><Trash2 size={14}/></button></div></div>
        {items.length>0&&!collapsedBrokers.has(broker.id)&&<div className="broker-card__portfolios">{items.map(portfolio=><div key={portfolio.id}><span><ChartNoAxesCombined size={15}/></span><div><strong>{portfolio.name}</strong><small>{t(portfolio.base_currency_code==='SAR'?'Saudi Equities':'Global Equities')} · {portfolio.base_currency_code}</small></div><small className="broker-card__portfolio-reference">{portfolio.portfolio_number_last4?`${t('Portfolio')} •• ${portfolio.portfolio_number_last4}`:t('Legacy Portfolio')}{portfolio.iban_last4?` · ${t('IBAN')} •• ${portfolio.iban_last4}`:''}</small><div className="broker-card__portfolio-actions"><button type="button" aria-label={`${t('Edit')} ${portfolio.name}`} onClick={()=>openPortfolioEdit(portfolio)}><Pencil size={13}/></button><button type="button" aria-label={`${t('Remove')} ${portfolio.name}`} onClick={()=>setPortfolioToRemove(portfolio)}><Trash2 size={13}/></button></div></div>)}</div>}
        {openBroker===broker.id&&<div className="broker-card__create"><div><strong>{t('Create A Portfolio With')} {broker.name}</strong><small>{t('Portfolio number is required. Select the currency actually used by this portfolio.')}</small></div><input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder={t('Portfolio Name')}/><input value={portfolioNumber} onChange={event=>setPortfolioNumber(event.target.value)} placeholder={t('Portfolio Number')}/><input value={iban} onChange={event=>setIban(event.target.value)} placeholder={t('IBAN (Optional)')}/><select aria-label={t('Portfolio Currency')} value={portfolioCurrency} onChange={event=>setPortfolioCurrency(event.target.value as typeof portfolioCurrency)}>{enabledCurrencies.map(currency=><option value={currency} key={currency}>{currency}</option>)}</select><button type="button" disabled={creating||name.trim().length<2||portfolioNumber.trim().length<2} onClick={()=>addPortfolio(broker.id)}>{t(creating?'Creating...':'Create Portfolio')}</button></div>}
      </article></div>})}</div>}
    </section>
    {brokerToRemove?<div className="broker-remove-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setBrokerToRemove(null)}}><section role="dialog" aria-modal="true" aria-labelledby="remove-broker-title"><header><span><TriangleAlert size={18}/></span><div><h2 id="remove-broker-title">{t('Remove')} {brokerToRemove.name}?</h2><p>{t('This permanently closes the broker and every portfolio held under it.')}</p></div><button type="button" aria-label={t('Close')} onClick={()=>setBrokerToRemove(null)}><X size={17}/></button></header><div><strong>{t('Financial Consequences')}</strong><ul><li>{t('All open positions under this broker will be closed and removed from your wealth.')}</li><li>{t('All brokerage cash under its portfolios will be removed.')}</li><li>{t('No money will be returned to any bank account or Cash On Hand.')}</li><li>{t('The written-off value will remain recorded in the accounting audit trail.')}</li></ul></div><footer><button type="button" onClick={()=>setBrokerToRemove(null)}>{t('Keep Broker')}</button><button type="button" disabled={removing} onClick={()=>void removeBroker()}>{t(removing?'Removing…':'Remove Broker And Write Off Value')}</button></footer></section></div>:null}
    {brokerToEdit?<div className="broker-edit-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setBrokerToEdit(null)}}><section role="dialog" aria-modal="true" aria-labelledby="edit-broker-title"><header><span><Pencil size={17}/></span><div><h2 id="edit-broker-title">{t('Edit')} {brokerToEdit.name}</h2><p>{t('Update the broker website and rates used for future activity.')}</p></div><button type="button" aria-label={t('Close')} onClick={()=>setBrokerToEdit(null)}><X size={17}/></button></header><div className="broker-edit-modal__fields"><label className="broker-edit-modal__website"><span>{t('Website')}</span><div><input autoFocus type="url" value={editWebsite} onChange={event=>setEditWebsite(event.target.value)} placeholder={t('Website URL example')}/></div></label><label><span>{t('Commission Rate')}</span><div><input type="number" min="0" max="100" step="0.00001" value={editRate} onChange={event=>setEditRate(event.target.value)}/><b>%</b></div></label><label><span>{t('VAT On Commission')}</span><div><input type="number" min="0" max="100" step="0.01" value={editTax} onChange={event=>setEditTax(event.target.value)}/><b>%</b></div></label><label className="broker-edit-modal__website"><span>{t('Dividend Withholding Tax')} <small>{t('Leave blank to use profile default')}</small></span><div><input type="number" min="0" max="100" step="0.01" value={editDividendTax} onChange={event=>setEditDividendTax(event.target.value)}/><b>%</b></div></label></div><p className="broker-edit-modal__note">{t('VAT applies to the brokerage service, while dividend withholding tax applies to eligible distributions. Leave the withholding field blank to follow the investor profile. Previously posted activity remains unchanged.')}</p><footer><button type="button" onClick={()=>setBrokerToEdit(null)}>{t('Cancel')}</button><button type="button" disabled={savingEdit||editRate===''||editTax===''} onClick={()=>void saveBrokerEdit()}>{t(savingEdit?'Saving…':'Save Changes')}</button></footer></section></div>:null}
    {portfolioToEdit?<div className="broker-edit-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setPortfolioToEdit(null)}}><section role="dialog" aria-modal="true" aria-labelledby="edit-portfolio-title"><header><span><Pencil size={17}/></span><div><h2 id="edit-portfolio-title">{t('Edit')} {portfolioToEdit.name}</h2><p>{t('Update this portfolio without changing its broker.')}</p></div><button type="button" aria-label={t('Close')} onClick={()=>setPortfolioToEdit(null)}><X size={17}/></button></header><div className="broker-edit-modal__fields"><label className="broker-edit-modal__website"><span>{t('Portfolio Name')}</span><div><input autoFocus value={portfolioEditName} onChange={event=>setPortfolioEditName(event.target.value)}/></div></label><label><span>{t('Portfolio Number')}</span><div><input value={portfolioEditNumber} onChange={event=>setPortfolioEditNumber(event.target.value)} placeholder={portfolioToEdit.portfolio_number_last4?`${t('Keep')} •• ${portfolioToEdit.portfolio_number_last4}`:t('Enter number')}/></div></label><label><span>{t('IBAN')} <small>{t('Optional')}</small></span><div><input value={portfolioEditIban} onChange={event=>setPortfolioEditIban(event.target.value)} placeholder={portfolioToEdit.iban_last4?`${t('Keep')} •• ${portfolioToEdit.iban_last4}`:t('Leave blank')}/></div></label><label className="broker-edit-modal__website"><span>{t('Portfolio Currency')}</span><div><select value={portfolioEditCurrency} onChange={event=>setPortfolioEditCurrency(event.target.value as typeof baseCurrency)}>{enabledCurrencies.map(currency=><option value={currency} key={currency}>{currency}</option>)}</select></div></label></div><p className="broker-edit-modal__note">{t('Leave the portfolio number and IBAN blank to keep their current values. Currency can change only before funding or trading.')}</p><footer><button type="button" onClick={()=>setPortfolioToEdit(null)}>{t('Cancel')}</button><button type="button" disabled={savingPortfolio||portfolioEditName.trim().length<2} onClick={()=>void savePortfolio()}>{t(savingPortfolio?'Saving…':'Save Changes')}</button></footer></section></div>:null}
    {portfolioToRemove?<div className="broker-remove-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setPortfolioToRemove(null)}}><section role="dialog" aria-modal="true" aria-labelledby="remove-portfolio-title"><header><span><TriangleAlert size={18}/></span><div><h2 id="remove-portfolio-title">{t('Remove')} {portfolioToRemove.name}?</h2><p>{t('This removes the portfolio from')} {portfolioToRemove.broker_name}.</p></div><button type="button" aria-label={t('Close')} onClick={()=>setPortfolioToRemove(null)}><X size={17}/></button></header><div><strong>{t('Protection Check')}</strong><ul><li>{t('The portfolio must have no open positions.')}</li><li>{t('Its brokerage cash balance must be zero.')}</li><li>{t('Historical trades remain preserved in the audit trail.')}</li></ul></div><footer><button type="button" onClick={()=>setPortfolioToRemove(null)}>{t('Keep Portfolio')}</button><button type="button" disabled={removingPortfolio} onClick={()=>void confirmRemovePortfolio()}>{t(removingPortfolio?'Removing…':'Remove Portfolio')}</button></footer></section></div>:null}
  </section>
}
