import { Check, Coins, Info, ShieldCheck } from 'lucide-react'
import PageNavigation from '../components/ui/PageNavigation'
import CurrencyMark from '../components/ui/CurrencyMark'
import { supportedCurrencies, useCurrency } from '../context/CurrencyContext'
import { useLanguage } from '../context/LanguageContext'
import './CurrencySettingsPage.css'
import './CurrencySettingsNavigation.css'

export default function CurrencySettingsPage(){const{baseCurrency,enabledCurrencies,setBaseCurrency,toggleEnabledCurrency}=useCurrency();const{t}=useLanguage();return <section className="currency-settings"><header><PageNavigation/><div className="currency-settings__identity"><span><Coins size={21}/></span><div><p>{t('Financial preferences')}</p><h1>{t('Currencies')}</h1><small>{t('Choose your reporting currency and every currency used across your wealth.')}</small></div></div></header><div className="currency-settings__layout"><main><section className="currency-settings__base"><div><h2>{t('Base reporting currency')}</h2><p>{t('Net worth and consolidated financial statements use this currency.')}</p></div><select value={baseCurrency} onChange={e=>setBaseCurrency(e.target.value as typeof baseCurrency)}>{supportedCurrencies.map(c=><option value={c.code} key={c.code}>{c.code} — {t(c.name)}</option>)}</select></section><section className="currency-settings__currencies"><div><h2>{t('Enabled currencies')}</h2><p>{t('Select every currency you expect to use. You can change this later.')}</p></div><div className="currency-settings__grid">{supportedCurrencies.map(c=>{const active=enabledCurrencies.includes(c.code);const base=c.code===baseCurrency;return <button type="button" className={active?'is-active':''} onClick={()=>toggleEnabledCurrency(c.code)} key={c.code}><i><CurrencyMark currency={c.code}/></i><span><strong>{c.code}</strong><small>{t(c.name)}</small></span><em>{base?t('Base'):active?<Check size={13}/>:null}</em></button>})}</div></section></main><aside><div><ShieldCheck size={18}/><h3>{t('Multi-currency accounting')}</h3><p>{t('Every transaction keeps its original currency, exchange rate, and value in your base currency.')}</p></div><div><Info size={18}/><h3>{t('Exchange rates')}</h3><p>{t('Rates shown in this prototype are indicative. A live rate provider will replace them before production use.')}</p></div></aside></div></section>}
