/* eslint-disable react-hooks/set-state-in-effect */
import { ChevronDown, FileSpreadsheet, FileText, Image, LibraryBig, RefreshCw, Search, Trash2, Upload, X } from 'lucide-react'
import { useEffect, useRef, useState, type ChangeEvent } from 'react'
import { Link } from 'react-router-dom'
import PageHeader from '../components/ui/PageHeader'
import { useLanguage } from '../context/LanguageContext'
import { analyzeFinancialDocument } from '../services/documentImportService'
import { deleteImportBatch, getImportBatches, saveImportBatch, type SavedImportBatch } from '../services/importReviewService'
import { formatDisplayInteger, formatDisplayNumber, formatDisplayPercent } from '../utils/localeFormat'
import './LibraryPage.css'

const fileSize=(bytes:number,language:'en'|'ar')=>bytes>=1048576?`${formatDisplayNumber(bytes/1048576,{minimumFractionDigits:1,maximumFractionDigits:1},language)} MB`:`${formatDisplayInteger(Math.max(1,Math.round(bytes/1024)),language)} KB`
const fileIcon=(type:string,name:string)=>type.includes('image')||/\.(png|jpe?g|webp)$/i.test(name)?Image:type.includes('sheet')||/\.(xlsx?|csv)$/i.test(name)?FileSpreadsheet:FileText

export default function LibraryPage(){
  const{language,t}=useLanguage()
  const[batches,setBatches]=useState<SavedImportBatch[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState<number|null>(null),[deleting,setDeleting]=useState<SavedImportBatch|null>(null),[deleteBusy,setDeleteBusy]=useState(false),[query,setQuery]=useState(''),[importing,setImporting]=useState(false),[importProgress,setImportProgress]=useState(0)
  const fileInput=useRef<HTMLInputElement>(null)
  async function load(){setLoading(true);setError('');try{setBatches(await getImportBatches())}catch(reason){setError(t(reason instanceof Error?reason.message:'Unable to load the document library.'))}finally{setLoading(false)}}
  async function importDocument(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;setImporting(true);setImportProgress(0);setError('');try{const analysis=await analyzeFinancialDocument(file,setImportProgress);const saved=await saveImportBatch(file,analysis.operations,[],[]);setBatches(current=>[saved,...current.filter(item=>item.id!==saved.id)]);setOpen(saved.id)}catch(reason){setError(t(reason instanceof Error?reason.message:'The document could not be analyzed.'))}finally{setImporting(false)}}
  async function removeDocument(){if(!deleting)return;setDeleteBusy(true);setError('');try{await deleteImportBatch(deleting.id);setBatches(current=>current.filter(batch=>batch.id!==deleting.id));setOpen(value=>value===deleting.id?null:value);setDeleting(null)}catch(reason){setError(t(reason instanceof Error?reason.message:'The document could not be deleted.'));setDeleting(null)}finally{setDeleteBusy(false)}}
  useEffect(()=>{void load()},[])
  const operations=batches.reduce((sum,batch)=>sum+batch.operations.length,0),pending=batches.reduce((sum,batch)=>sum+batch.operations.filter(item=>item.status==='PENDING').length,0),needle=query.trim().toLowerCase()
  const visibleBatches=needle?batches.filter(batch=>`${batch.filename} ${batch.file_type} ${batch.status} ${batch.operations.map(item=>`${item.operation_type} ${item.description} ${item.amount??''} ${item.currency??''}`).join(' ')}`.toLowerCase().includes(needle)):batches
  const actions=<div className="library-page__actions"><input ref={fileInput} hidden type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.xlsx,.xls,.csv" onChange={event=>void importDocument(event)}/><button type="button" disabled={importing} onClick={()=>fileInput.current?.click()}><Upload size={14}/>{importing?`${t('Reading')} ${formatDisplayPercent(importProgress*100,0,language)}`:t('Add Document')}</button><button type="button" onClick={()=>void load()}><RefreshCw size={14}/>{t('Refresh')}</button></div>
  return <section className="library-page">
    <PageHeader title={t('Library')} subtitle={t('Every financial document analyzed by WealthOS and the operations found inside it.')} icon={LibraryBig} actions={actions}/>
    <div className="library-page__metrics"><article><span>{t('Documents')}</span><strong>{formatDisplayInteger(batches.length,language)}</strong><small>{t('Analyzed Files')}</small></article><article><span>{t('Extracted Operations')}</span><strong>{formatDisplayInteger(operations,language)}</strong><small>{t('Across All Documents')}</small></article><article><span>{t('Awaiting Review')}</span><strong>{formatDisplayInteger(pending,language)}</strong><small>{pending?<Link to="/accounting/review-queue">{t('Open Review Queue')}</Link>:t('Library Is Clear')}</small></article></div>
    <div className="library-page__note"><LibraryBig size={17}/><p><strong>{t('Privacy-First Library')}</strong>{t('The original document is read locally in your browser. WealthOS stores its file record and extracted financial operations for review and audit.')}</p></div>
    <section className="library-page__panel"><header><div><h2>{t('Uploaded Documents')}</h2><p>{t('Newest documents appear first.')}</p></div><label><Search size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('Search Documents Or Amounts')}/></label></header>
      {loading?<div className="library-page__empty">{t('Loading Your Library…')}</div>:error?<div className="library-page__empty is-error">{error}</div>:!batches.length?<div className="library-page__empty"><LibraryBig size={24}/><strong>{t('No Documents Yet')}</strong><span>{t('Add your first PDF, image, spreadsheet, or CSV from this page.')}</span><button type="button" onClick={()=>fileInput.current?.click()}><Upload size={14}/>{t('Add First Document')}</button></div>:!visibleBatches.length?<div className="library-page__empty"><Search size={24}/><strong>{t('No Matching Documents')}</strong><span>{t('Try a file name, operation, amount, or currency.')}</span></div>:<div className="library-page__list">{visibleBatches.map(batch=>{const Icon=fileIcon(batch.file_type,batch.filename),isOpen=open===batch.id,counts={pending:batch.operations.filter(item=>item.status==='PENDING').length,confirmed:batch.operations.filter(item=>item.status==='CONFIRMED').length,ignored:batch.operations.filter(item=>item.status==='IGNORED').length};return <article className={isOpen?'is-open':''} key={batch.id}>
        <button type="button" onClick={()=>setOpen(value=>value===batch.id?null:batch.id)}><span><Icon size={18}/></span><div><strong>{batch.filename}</strong><small>{fileSize(batch.file_size,language)} · {new Date(batch.created_at).toLocaleString(language==='ar'?'ar-SA':'en-GB')}</small></div><div><strong>{formatDisplayInteger(batch.operations.length,language)} {t('Operations')}</strong><small>{formatDisplayInteger(counts.pending,language)} {t('Pending')} · {formatDisplayInteger(counts.confirmed,language)} {t('Confirmed')} · {formatDisplayInteger(counts.ignored,language)} {t('Ignored')}</small></div><em className={`is-${batch.status.toLowerCase()}`}>{t(batch.status.replaceAll('_',' '))}</em><ChevronDown className={isOpen?'is-open':''} size={16}/></button>
        {isOpen&&<div className="library-page__operations"><div className="library-page__document-actions"><span><strong>{t('Document Actions')}</strong><small>{t('Posted accounting records remain protected after removal.')}</small></span><button type="button" onClick={()=>setDeleting(batch)}><Trash2 size={14}/>{t('Delete Document')}</button></div>{batch.operations.length?batch.operations.map(item=><div key={item.id}><span><strong>{t(item.operation_type.replaceAll('_',' '))}</strong><small>{item.description}</small></span><span><strong>{item.amount===null?t('Amount Not Found'):`${item.currency??''} ${formatDisplayNumber(item.amount,undefined,language)}`.trim()}</strong><small>{item.transaction_date||t('Date Not Found')}</small></span><em className={`is-${item.status.toLowerCase()}`}>{t(item.status==='DUPLICATE'?'ALREADY POSTED':item.status)}</em></div>):<p>{t('No operations were extracted from this document.')}</p>}</div>}
      </article>})}</div>}
    </section>
    {deleting&&<div className="library-delete-modal" role="dialog" aria-modal="true" aria-labelledby="delete-document-title" onMouseDown={event=>{if(event.currentTarget===event.target&&!deleteBusy)setDeleting(null)}}><section><header><span><Trash2 size={18}/></span><div><h2 id="delete-document-title">{t('Delete Imported Document?')}</h2><p>{deleting.filename}</p></div><button type="button" disabled={deleteBusy} aria-label={t('Close')} onClick={()=>setDeleting(null)}><X size={16}/></button></header><div><strong>{t('This removes the document and every unposted review draft extracted from it.')}</strong><p>{t('Posted operations, ledger entries, and their duplicate-protection fingerprints remain safely preserved.')}</p></div><footer><button type="button" disabled={deleteBusy} onClick={()=>setDeleting(null)}>{t('Keep Document')}</button><button type="button" disabled={deleteBusy} onClick={()=>void removeDocument()}>{t(deleteBusy?'Deleting…':'Delete Document')}</button></footer></section></div>}
  </section>
}
