import { CalendarRange, CheckCircle2, RefreshCw, Save, ShieldCheck, XCircle } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'

import FormattedMoney from '../components/ui/FormattedMoney'
import PageHeader from '../components/ui/PageHeader'
import { useCurrency } from '../context/CurrencyContext'
import { useLanguage } from '../context/LanguageContext'
import { closeMonth, getMonthClosePreview, getMonthCloses, type MonthClosePreview, type MonthCloseRecord } from '../services/accountingService'
import { formatDate } from '../utils/dateFormat'
import './MonthClosePage.css'

const localMonth=()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`}
const total=(preview:MonthClosePreview|null,report:string,label:string)=>preview?.reports[report]?.rows.find(row=>row.label===label)?.value??0

export default function MonthClosePage(){
  const[period,setPeriod]=useState(localMonth());const[preview,setPreview]=useState<MonthClosePreview|null>(null);const[history,setHistory]=useState<MonthCloseRecord[]>([]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const{formatMoney}=useCurrency();const{t}=useLanguage()
  const[year,month]=period.split('-').map(Number)
  const load=useCallback(async()=>{setLoading(true);setMessage('');try{const[review,records]=await Promise.all([getMonthClosePreview(year,month),getMonthCloses()]);setPreview(review);setHistory(records)}catch{setMessage(t('Unable to prepare the monthly snapshot.'))}finally{setLoading(false)}},[month,year,t])
  useEffect(()=>{const request=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(request)},[load])
  const snapshotSaved=preview?.existing_close?.status==='CLOSED'
  const submitClose=async()=>{setMessage(t('Saving monthly snapshot…'));try{await closeMonth(year,month);setMessage(t('Monthly snapshot saved. You can continue editing operations and save a newer version when needed.'));await load()}catch{setMessage(t('Unable to save this monthly snapshot.'))}}
  return <section className="month-close-page"><PageHeader eyebrow={t('Personal Wealth Record')} title={t('Monthly Snapshots')} subtitle={t('Review and save a flexible summary for each month without locking your operations.')} icon={CalendarRange} actions={<button type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/>{t('Refresh')}</button>}/>
    <section className="month-close-control"><label>{t('Snapshot Month')}<input type="month" value={period} onChange={event=>setPeriod(event.target.value)}/></label><div><span>{preview?`${formatDate(preview.period_start)} — ${formatDate(preview.period_end)}`:t('Preparing period…')}</span><strong className={preview?.ready?'is-ready':'is-blocked'}>{preview?.ready?<><CheckCircle2 size={15}/>{t('Data matches')}</>:<><XCircle size={15}/>{t('Review required')}</>}</strong></div><button type="button" disabled={loading} onClick={()=>void submitClose()}><Save size={15}/>{t(snapshotSaved?'Save Newer Version':'Save Snapshot')}</button></section>
    {message&&<p className="month-close-message">{message}</p>}
    <div className="month-close-metrics"><article><span>{t('Operating Cash Flow')}</span><strong><FormattedMoney value={formatMoney(total(preview,'cash_flow_statement','Net Cash From Operating Activities'))}/></strong><small>{t('Posted cash movements')}</small></article><article><span>{t('Investing Cash Flow')}</span><strong><FormattedMoney value={formatMoney(total(preview,'cash_flow_statement','Net Cash From Investing Activities'))}/></strong><small>{t('Asset purchases and proceeds')}</small></article><article><span>{t('Net Change in Cash')}</span><strong><FormattedMoney value={formatMoney(total(preview,'cash_flow_statement','Net Change In Cash'))}/></strong><small>{t('For the selected month')}</small></article><article><span>{t('Closing Net Worth')}</span><strong><FormattedMoney value={formatMoney(total(preview,'balance_sheet','Net Worth'))}/></strong><small>{t('Balance sheet snapshot')}</small></article></div>
    <div className="month-close-layout"><section className="month-close-panel"><header><div><h2>{t('Data Quality Check')}</h2><p>{t('Differences must be resolved before saving the snapshot.')}</p></div><ShieldCheck size={18}/></header>{preview?.comparisons.map(item=><div className="month-close-check" key={item.label}><span className={item.matches?'is-match':'is-difference'}>{item.matches?<CheckCircle2 size={15}/>:<XCircle size={15}/>}</span><div><strong>{t(item.label)}</strong><small>{t('Ledger')} <FormattedMoney value={formatMoney(item.ledger)}/> · {t('Records')} <FormattedMoney value={formatMoney(item.operational)}/></small></div><em><FormattedMoney value={formatMoney(item.variance)}/></em></div>)}{preview&&<div className="month-close-check"><span className={!preview.unbalanced_entries.length?'is-match':'is-difference'}>{!preview.unbalanced_entries.length?<CheckCircle2 size={15}/>:<XCircle size={15}/>}</span><div><strong>{t('Balanced Journal Entries')}</strong><small>{preview.unbalanced_entries.length?`${preview.unbalanced_entries.length} ${t('entries need review')}`:t('All posted entries are balanced')}</small></div><em>{preview.unbalanced_entries.length}</em></div>}</section>
      <section className="month-close-panel"><header><div><h2>{t('Snapshot History')}</h2><p>{t('Saved versions do not prevent you from correcting personal operations.')}</p></div><Save size={18}/></header>{history.length?history.map(item=><article className="month-close-history" key={item.id}><div><strong>{formatDate(item.period_end)}</strong><small>{t('Saved at')} {formatDate(item.closed_at)} · {t('Verification code')} {item.checksum.slice(0,10)}</small></div><span className={`is-${item.status.toLowerCase()}`}>{t(item.status==='CLOSED'?'Saved':'Draft')}</span></article>):<div className="month-close-empty">{t('No monthly snapshots have been saved yet.')}</div>}</section></div>
  </section>
}
