import { useEffect, useState } from 'react'
import { Save, UserRound } from 'lucide-react'
import PageNavigation from '../components/ui/PageNavigation'
import { getAccountProfile, updateAccountProfile } from '../services/accountService'
import { saveUserProfile } from './userProfile'
import './SettingsSubpage.css'
import { useLanguage } from '../context/LanguageContext'

export default function ProfileSettingsPage(){
  const{t}=useLanguage()
  const[fullName,setFullName]=useState(''),[email,setEmail]=useState(''),[nationality,setNationality]=useState(''),[residence,setResidence]=useState(''),[taxResidence,setTaxResidence]=useState(''),[investorType,setInvestorType]=useState<'INDIVIDUAL'|'ENTITY'>('INDIVIDUAL'),[dividendTax,setDividendTax]=useState('0'),[message,setMessage]=useState(''),[busy,setBusy]=useState(true)
  useEffect(()=>{getAccountProfile().then(profile=>{setFullName(profile.full_name);setEmail(profile.email);setNationality(profile.nationality??'');setResidence(profile.country_of_residence??'');setTaxResidence(profile.tax_residence??'');setInvestorType(profile.investor_type);setDividendTax(String(profile.default_dividend_withholding_tax_rate??0))}).catch(()=>setMessage('Unable to load the profile.')).finally(()=>setBusy(false))},[])
  async function save(){if(!fullName.trim()||!/^\S+@\S+\.\S+$/.test(email)||dividendTax===''){setMessage('Enter valid profile and tax information.');return}setBusy(true);setMessage('');try{const profile=await updateAccountProfile({full_name:fullName.trim(),email:email.trim(),nationality:nationality.trim()||null,country_of_residence:residence.trim()||null,tax_residence:taxResidence.trim()||null,investor_type:investorType,default_dividend_withholding_tax_rate:Number(dividendTax)});saveUserProfile({fullName:profile.full_name,email:profile.email},profile.id);setMessage('Profile and tax settings saved.')}catch{setMessage('Unable to save the profile.')}finally{setBusy(false)}}
  return <section className="settings-subpage"><header><PageNavigation/><div className="settings-subpage__identity"><span><UserRound size={21}/></span><div><p>{t('Account Settings')}</p><h1>{t('Profile')}</h1><small>{t('Manage your identity, residence, and default investment tax treatment.')}</small></div></div></header>
    <section className="settings-subpage__panel"><div className="settings-subpage__title"><h2>{t('Personal Information')}</h2><p>{t('These details identify you across WealthOS.')}</p></div><div className="settings-subpage__fields"><label>{t('Full Name')}<input value={fullName} disabled={busy} onChange={e=>setFullName(e.target.value)} autoComplete="name"/></label><label>{t('Email Address')}<input type="email" value={email} disabled={busy} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>{t('Nationality')}<input value={nationality} disabled={busy} onChange={e=>setNationality(e.target.value)} placeholder={t('e.g. Saudi Arabian')}/></label><label>{t('Country Of Residence')}<input value={residence} disabled={busy} onChange={e=>setResidence(e.target.value)} placeholder={t('e.g. Saudi Arabia')}/></label></div></section>
    <section className="settings-subpage__panel"><div className="settings-subpage__title"><h2>{t('Tax Profile')}</h2><p>{t('The default applies to future distributions unless a broker has its own override.')}</p></div><div className="settings-subpage__fields is-three"><label>{t('Tax Residence')}<input value={taxResidence} disabled={busy} onChange={e=>setTaxResidence(e.target.value)} placeholder={t('Country of tax residence')}/></label><label>{t('Investor Type')}<select value={investorType} disabled={busy} onChange={e=>setInvestorType(e.target.value as 'INDIVIDUAL'|'ENTITY')}><option value="INDIVIDUAL">{t('Individual')}</option><option value="ENTITY">{t('Entity')}</option></select></label><label>{t('Default Dividend Withholding Tax %')}<input type="number" min="0" max="100" step="0.01" value={dividendTax} disabled={busy} onChange={e=>setDividendTax(e.target.value)}/></label></div><footer><span className={message.includes('saved')?'is-success':'is-error'}>{t(message)}</span><button type="button" disabled={busy} onClick={()=>void save()}><Save size={15}/>{t('Save Changes')}</button></footer></section>
  </section>
}
