import { Eye, EyeOff, LockKeyhole, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import PageNavigation from '../components/ui/PageNavigation'
import { useLanguage } from '../context/LanguageContext'
import { changeLocalPassword, disableLocalPassword } from '../services/accountService'
import './SettingsSubpage.css'

export default function SecuritySettingsPage(){
  const{t,language,direction}=useLanguage()
  const[current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[message,setMessage]=useState(''),[recovery,setRecovery]=useState(''),[confirmDisable,setConfirmDisable]=useState(false)
  const disableCopy=language==='ar'
    ?{title:'تأكيد تعطيل كلمة المرور',body:'سيؤدي هذا إلى إزالة حماية كلمة المرور المحلية وإنهاء الجلسة الحالية. ستحتاج إلى إعداد كلمة مرور جديدة لاستعادة هذه الحماية.',cancel:'إلغاء',action:'تعطيل كلمة المرور'}
    :{title:'Confirm password protection removal',body:'This removes local password protection and ends the current session. You will need to set a new password to restore this protection.',cancel:'Cancel',action:'Disable password'}
  async function update(){if(!current||next.length<12){setMessage('Use your current password and at least 12 characters for the new password.');return}if(next!==confirm){setMessage('New passwords do not match.');return}try{const result=await changeLocalPassword(current,next);setRecovery(result.recovery_code);setCurrent('');setNext('');setConfirm('');setMessage('Password changed. Save the new recovery code.')}catch{setMessage('Password change failed.')}}
  async function disable(){setMessage('');try{await disableLocalPassword(current);window.location.reload()}catch{setConfirmDisable(false);setMessage('Password disable failed.')}}
  return <section className="settings-subpage" dir={direction}><header><PageNavigation/><div className="settings-subpage__identity"><span><LockKeyhole size={21}/></span><div><p>{t('Account security')}</p><h1>{t('Email & Password')}</h1><small>{t('Control your local password and account protection.')}</small></div></div></header><section className="settings-subpage__panel"><div className="settings-subpage__title"><h2>{t('Change password')}</h2><p>{t('Your password is never stored in the browser.')}</p></div><div className="settings-subpage__fields is-three"><label>{t('Current password')}<input type={show?'text':'password'} value={current} onChange={e=>setCurrent(e.target.value)} autoComplete="current-password"/></label><label>{t('New password')}<input type={show?'text':'password'} value={next} onChange={e=>setNext(e.target.value)} autoComplete="new-password"/></label><label>{t('Confirm password')}<input type={show?'text':'password'} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label></div>{recovery&&<div className="setup-wizard__notice"><strong dir="ltr">{recovery}</strong><p>{t('Save this replacement recovery code offline. It is shown only here.')}</p></div>}{confirmDisable&&<div className="setup-wizard__notice" role="alert"><strong>{disableCopy.title}</strong><p>{disableCopy.body}</p></div>}<footer><button className="is-secondary" type="button" onClick={()=>setShow(value=>!value)}>{show?<EyeOff size={14}/>:<Eye size={14}/>} {t(show?'Hide':'Show')} {t('passwords')}</button><span className={message.startsWith('Password changed')?'is-success':'is-error'}>{t(message)}</span>{confirmDisable?<><button className="is-secondary" type="button" onClick={()=>setConfirmDisable(false)}>{disableCopy.cancel}</button><button type="button" onClick={()=>void disable()}>{disableCopy.action}</button></>:<button className="is-secondary" type="button" onClick={()=>setConfirmDisable(true)}>{t('Disable password')}</button>}<button type="button" onClick={update}><ShieldCheck size={15}/>{t('Update password')}</button></footer></section></section>
}
