import { BookOpen, BriefcaseBusiness, ChevronRight, ListTree, Search, Settings, Workflow } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import PageHeader from '../components/ui/PageHeader'
import { operationRegistry } from '../operations/operationRegistry'
import './SystemIndexPage.css'
import { useLanguage } from '../context/LanguageContext'

const groups=[
  {title:'Workspace',icon:ListTree,links:[['Home','Your consolidated wealth dashboard','/'],['Search','Search every record and destination','/search'],['Library','Uploaded financial documents and extracted operations','/library'],['Operations','All available financial operations','/operations'],['Priorities','Items that need your attention','/focus'],['Recent Activity','Posted financial activity','/activity']]},
  {title:'Wealth',icon:BriefcaseBusiness,links:[['Investing','Wealth allocation, deposits, and investments','/investing'],['Stocks','Listed securities and market positions','/investing/positions'],['Investment Cash Flows','Distributions, rent, yield, principal returns, and maturities','/investing/cash-flows'],['Properties','Property executive summary and values','/properties'],['Property Income','Rental income linked to properties','/properties/income'],['Property Expenses','Maintenance and investment-property costs','/properties/expenses'],['Deposits','Deposit balances, returns, and maturities','/investing/deposits'],['Alternative Investments','Crowdfunding, private sukuk, private credit, and managed portfolios','/investing/alternative-investments'],['Saving Circles','Contributions, payout order, and circle receivables','/investing/saving-circles'],['Financial Platforms','Managed portfolios, crowdfunding, sukuk, and saving providers','/investing/platforms'],['Cash','Cash on hand, bank balances, and brokerage cash','/investing/cash'],['Brokers','Registered investment brokers','/investing/brokers'],['Bank Accounts','Bank balances and cash movement','/bank-accounts'],['Credit Cards','Credit balances, limits, statements, and upcoming payments','/credit-cards']]},
  {title:'Accounting & Intelligence',icon:BookOpen,links:[['Accounting','Cash flow, balance sheet, and income statement','/accounting'],['Review Queue','Imported operations awaiting review','/accounting/review-queue'],['General Ledger','Every posted debit and credit','/accounting/ledger'],['Journal Entries','Balanced entries from real operations','/accounting/journals'],['Reconciliation','Bank and card matching','/accounting/reconciliation'],['Monthly Snapshots','Save flexible monthly summaries without locking transactions','/accounting/month-close'],['Reporting','Live reports from posted entries','/reporting']]},
  {title:'Settings',icon:Settings,links:[['Settings','Workspace settings overview','/settings'],['Profile','Personal details and user identity','/settings/profile'],['Security','Password and account protection','/settings/security'],['Currencies','Enabled and base currencies','/settings/currencies'],['Data & Account','Backup and account deletion','/settings/data-account']]},
] as const

export default function SystemIndexPage(){
  const{t}=useLanguage()
  const[query,setQuery]=useState('');const needle=query.trim().toLowerCase();const operations=Object.values(operationRegistry).sort((a,b)=>a.order-b.order)
  const visibleGroups=useMemo(()=>groups.map(group=>({...group,links:group.links.filter(([title,note])=>!needle||`${title} ${note} ${group.title}`.toLowerCase().includes(needle))})).filter(group=>group.links.length),[needle])
  const visibleOperations=operations.filter(item=>!needle||`${item.title} ${item.description} ${item.status} operation`.toLowerCase().includes(needle))
  const resultCount=visibleGroups.reduce((sum,group)=>sum+group.links.length,0)+visibleOperations.length
  return <section className="system-index-page"><PageHeader title={t('Index')} subtitle={t('Every WealthOS page and operation in one place.')} icon={ListTree}/><div className="system-index-page__search"><Search size={17}/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('Find Any Page Or Operation')}/><span>{needle?`${resultCount} ${t('Results')}`:`${groups.reduce((sum,group)=>sum+group.links.length,0)} ${t('Pages')} · ${operations.length} ${t('Operations')}`}</span></div>{visibleGroups.length>0&&<div className="system-index-page__groups">{visibleGroups.map(group=>{const Icon=group.icon;return <section key={group.title}><header><span><Icon size={17}/></span><div><h2>{t(group.title)}</h2><p>{group.links.length} {t('Destinations')}</p></div></header><div>{group.links.map(([title,note,route])=><Link to={route} key={route}><span><strong>{t(title)}</strong><small>{t(note)}</small></span><ChevronRight size={15}/></Link>)}</div></section>})}</div>}{visibleOperations.length>0&&<section className="system-index-page__operations"><header><span><Workflow size={17}/></span><div><h2>{t('Financial Operations')}</h2><p>{visibleOperations.length} {t('Operations')}</p></div></header><div>{visibleOperations.map(item=>{const Icon=item.icon;return <Link className={item.status!=='active'?'is-planned':''} to={item.route} key={item.id}><i><Icon size={16}/></i><span><strong>{t(item.title)}</strong><small>{t(item.description)}</small></span><em>{t(item.status==='active'?'Available':'Coming Soon')}</em><ChevronRight size={15}/></Link>})}</div></section>}{needle&&resultCount===0&&<div className="system-index-page__empty"><Search size={25}/><strong>{t('No Matching Destination')}</strong><span>{t('Try the name of a page, task, or financial operation.')}</span></div>}</section>
}
